SELECT
    celebrity_id,
    celebrity_code,
    celebrity_status,
    user_id,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(celebrity_name), '\r', ''),'\n',''),'\t',''),'\"', '') as celebrity_name,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(celebrity_arabic_name), '\r', ''),'\n',''),'\t',''),'\"', '') as celebrity_arabic_name,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(celebrity_description), '\r', ''),'\n',''),'\t',''),'\"', '') as celebrity_description,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(celebrity_arabic_description), '\r', ''),'\n',''),'\t',''),'\"', '') as celebrity_arabic_description,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(meta_keyword), '\r', ''),'\n',''),'\t',''),'\"', '') as meta_keyword,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(meta_description), '\r', ''),'\n',''),'\t',''),'\"', '') as meta_description,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(boutique_name), '\r', ''),'\n',''),'\t',''),'\"', '') as boutique_name,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(boutique_arabic_name), '\r', ''),'\n',''),'\t',''),'\"', '') as boutique_arabic_name,
    erp_account_number,
    nationality,
    include_home_slider,
    mobile_banner_image_arabic,
    banner_image_arabic,
    main_image,
    main_image_arabic,
    banner_image,
    web_banner_image,
    web_banner_url,
    mobile_banner_image,
    main_image_v2,
    banner_image_v2,
    banner_image_arabic_v2,
    banner_url_value,
    banner_url_key,
    banner_filter_key,
    banner_filter_value,
    celebrity_email_id,
    instagram,
    facebook,
    snapchat,
    twitter,
    last_ad_number,
    store_ids,
    created_at,
    updated_at,
    celebrity_cache_expiration_time,
    celebrity_gender,
    celebrity_type
FROM aoi.celebrity_master
WHERE \$CONDITIONS