SELECT
    [timestamp] as ts,
    No_ as no,
    [Buy-from Vendor No_] as buy_from_vendor_no,
    [Pay-to Vendor No_] as pay_to_vendor_no,
    [Pay-to Name] as pay_to_name,
    [Pay-to Name 2] as pay_to_name_2,
    [Pay-to Address] as pay_to_address,
    [Pay-to Address 2] as pay_to_address_2,
    [Pay-to City] as pay_to_city,
    [Pay-to Contact] as pay_to_contact,
    [Your Reference] as your_reference,
    [Ship-to Code] as ship_to_code,
    [Ship-to Name] as ship_to_name,
    [Ship-to Name 2] as ship_to_name_2,
    [Ship-to Address] as ship_to_address,
    [Ship-to Address 2] as ship_to_address_2,
    [Ship-to City] as ship_to_city,
    [Ship-to Contact] as ship_to_contact,
    [Order Date] as order_date,
    [Posting Date] as posting_date,
    [Expected Receipt Date] as expected_receipt_date,
    [Posting Description] as posting_description,
    [Payment Terms Code] as payment_terms_code,
    [Due Date] as due_date,
    [Payment Discount _] as payment_discount,
    [Pmt_ Discount Date] as pmt_discount_date,
    [Shipment Method Code] as shipment_method_code,
    [Location Code] as location_code,
    [Shortcut Dimension 1 Code] as shortcut_dimension_1_code,
    [Shortcut Dimension 2 Code] as shortcut_dimension_2_code,
    [Vendor Posting Group] as vendor_posting_group,
    [Currency Code] as currency_code,
    [Currency Factor] as currency_factor,
    [Invoice Disc_ Code] as invoice_disc_code,
    [Language Code] as language_code,
    [Purchaser Code] as purchaser_code,
    [Order No_] as order_no,
    [No_ Printed] as no_printed,
    [On Hold] as on_hold,
    [Applies-to Doc_ Type] as applies_to_doc_type,
    [Applies-to Doc_ No_] as applies_to_doc_no,
    [Bal_ Account No_] as bal_account_no,
    [Vendor Order No_] as vendor_order_no,
    [Vendor Shipment No_] as vendor_shipment_no,
    [VAT Registration No_] as vat_registration_no,
    [Sell-to Customer No_] as sell_to_customer_no,
    [Reason Code] as reason_code,
    [Gen_ Bus_ Posting Group] as gen_bus_posting_group,
    [Transaction Type] as transaction_type,
    [Transport Method] as transport_method,
    [VAT Country_Region Code] as vat_country_region_code,
    [Buy-from Vendor Name] as buy_from_vendor_name,
    [Buy-from Vendor Name 2] as buy_from_vendor_name_2,
    [Buy-from Address] as buy_from_address,
    [Buy-from Address 2] as buy_from_address_2,
    [Buy-from City] as buy_from_city,
    [Buy-from Contact] as buy_from_contact,
    [Pay-to Post Code] as pay_to_post_code,
    [Pay-to County] as pay_to_county,
    [Pay-to Country_Region Code] as pay_to_country_region_code,
    [Buy-from Post Code] as buy_from_post_code,
    [Buy-from County] as buy_from_county,
    [Buy-from Country_Region Code] as buy_from_country_region_code,
    [Ship-to Post Code] as ship_to_post_code,
    [Ship-to County] as ship_to_county,
    [Ship-to Country_Region Code] as ship_to_country_region_code,
    [Bal_ Account Type] as bal_account_type,
    [Order Address Code] as order_address_code,
    [Entry Point] as entry_point,
    Correction as correction,
    [Document Date] as document_date,
    Area as area,
    [Transaction Specification] as transaction_specification,
    [Payment Method Code] as payment_method_code,
    [No_ Series] as no_series,
    [Order No_ Series] as order_no_series,
    [User ID] as user_id,
    [Source Code] as source_code,
    [Tax Area Code] as tax_area_code,
    [Tax Liable] as tax_liable,
    [VAT Bus_ Posting Group] as vat_bus_posting_group,
    [VAT Base Discount _] as vat_base_discount,
    [Quote No_] as quote_no,
    [Dimension Set ID] as dimension_set_id,
    [Campaign No_] as campaign_no,
    [Buy-from Contact No_] as buy_from_contact_no,
    [Pay-to Contact no_] as pay_to_contact_no,
    [Responsibility Center] as responsibility_center,
    [Requested Receipt Date] as requested_receipt_date,
    [Promised Receipt Date] as promised_receipt_date,
    [Lead Time Calculation] as lead_time_calculation,
    [Inbound Whse_ Handling Time] as inbound_whse_handling_time,
    [Quality Status] as quality_status,
    [Exchange PO] as exchange_po,
    [Return Order No_] as return_order_no,
    [Vendor Invoice No] as vendor_invoice_no
FROM Boutiqaat_Live.dbo.[Boutiqaat Kuwait\$Purch_ Rcpt_ Header]
WHERE \$CONDITIONS