BEGIN;
DROP TABLE IF EXISTS tmp_purch_rcpt_header;
CREATE TEMP TABLE tmp_purch_rcpt_header(
    ts VARCHAR(40),
	no VARCHAR(40),
	buy_from_vendor_no VARCHAR(40),
	pay_to_vendor_no VARCHAR(40),
	pay_to_name VARCHAR(200),
	pay_to_name_2 VARCHAR(200),
	pay_to_address VARCHAR(100),
	pay_to_address_2 VARCHAR(100),
	pay_to_city VARCHAR(60),
	pay_to_contact VARCHAR(100),
	your_reference VARCHAR(70),
	ship_to_code VARCHAR(20),
	ship_to_name VARCHAR(200),
	ship_to_name_2 VARCHAR(200),
	ship_to_address VARCHAR(100),
	ship_to_address_2 VARCHAR(100),
	ship_to_city VARCHAR(60),
	ship_to_contact VARCHAR(100),
	order_date timestamp,
	posting_date timestamp,
	expected_receipt_date timestamp,
	posting_description VARCHAR(100),
	payment_terms_code VARCHAR(20),
	due_date timestamp,
	payment_discount decimal(38,20),
	pmt_discount_date timestamp,
	shipment_method_code VARCHAR(20),
	location_code VARCHAR(20),
	shortcut_dimension_1_code VARCHAR(40),
	shortcut_dimension_2_code VARCHAR(40),
	vendor_posting_group VARCHAR(20),
	currency_code VARCHAR(20),
	currency_factor decimal(38,20),
	invoice_disc_code VARCHAR(40),
	language_code VARCHAR(20),
	purchaser_code VARCHAR(40),
	order_no VARCHAR(40),
	no_printed INTEGER,
	on_hold VARCHAR(6),
	applies_to_doc_type INTEGER,
	applies_to_doc_no VARCHAR(40),
	bal_account_no VARCHAR(40),
	vendor_order_no VARCHAR(70),
	vendor_shipment_no VARCHAR(70),
	vat_registration_no VARCHAR(40),
	sell_to_customer_no VARCHAR(40),
	reason_code VARCHAR(20),
	gen_bus_posting_group VARCHAR(20),
	transaction_type VARCHAR(20),
	transport_method VARCHAR(20),
	vat_country_region_code VARCHAR(20),
	buy_from_vendor_name VARCHAR(200),
	buy_from_vendor_name_2 VARCHAR(200),
	buy_from_address VARCHAR(100),
	buy_from_address_2 VARCHAR(100),
	buy_from_city VARCHAR(60),
	buy_from_contact VARCHAR(100),
	pay_to_post_code VARCHAR(40),
	pay_to_county VARCHAR(60),
	pay_to_country_region_code VARCHAR(20),
	buy_from_post_code VARCHAR(40),
	buy_from_county VARCHAR(60),
	buy_from_country_region_code VARCHAR(20),
	ship_to_post_code VARCHAR(40),
	ship_to_county VARCHAR(60),
	ship_to_country_region_code VARCHAR(20),
	bal_account_type INTEGER,
	order_address_code VARCHAR(20),
	entry_point VARCHAR(20),
	correction SMALLINT,
	document_date timestamp,
	area VARCHAR(20),
	transaction_specification VARCHAR(20),
	payment_method_code VARCHAR(20),
	no_series VARCHAR(20),
	order_no_series VARCHAR(20),
	user_id VARCHAR(100),
	source_code VARCHAR(20),
	tax_area_code VARCHAR(40),
	tax_liable SMALLINT,
	vat_bus_posting_group VARCHAR(20),
	vat_base_discount decimal(38,20),
	quote_no VARCHAR(40),
	dimension_set_id INTEGER,
	campaign_no VARCHAR(40),
	buy_from_contact_no VARCHAR(40),
	pay_to_contact_no VARCHAR(40),
	responsibility_center VARCHAR(20),
	requested_receipt_date timestamp,
	promised_receipt_date timestamp,
	lead_time_calculation varchar(32),
	inbound_whse_handling_time varchar(32),
	quality_status INTEGER,
	exchange_po SMALLINT,
	return_order_no VARCHAR(40),
	vendor_invoice_no VARCHAR(40)
);

copy tmp_purch_rcpt_header from '{{S3PATH}}'
iam_role 'arn:aws:iam::652586300051:role/Redshift-athena-S3-readonly'
delimiter '\t'
region 'eu-west-1' 
acceptinvchars
CSV 
GZIP 
NULL AS 'null';


DROP TABLE IF EXISTS NAV.purch_rcpt_header;
CREATE TABLE NAV.purch_rcpt_header (
	ts VARCHAR(40) NOT NULL ENCODE LZO,
	no VARCHAR(40) NOT NULL ENCODE LZO PRIMARY KEY SORTKEY DISTKEY,
	buy_from_vendor_no VARCHAR(40) NOT NULL ENCODE LZO,
	pay_to_vendor_no VARCHAR(40) NOT NULL ENCODE LZO,
	pay_to_name VARCHAR(200) NOT NULL ENCODE LZO,
	pay_to_name_2 VARCHAR(200) NOT NULL ENCODE LZO,
	pay_to_address VARCHAR(100) NOT NULL ENCODE LZO,
	pay_to_address_2 VARCHAR(100) NOT NULL ENCODE LZO,
	pay_to_city VARCHAR(60) NOT NULL ENCODE LZO,
	pay_to_contact VARCHAR(100) NOT NULL ENCODE LZO,
	your_reference VARCHAR(70) NOT NULL ENCODE LZO,
	ship_to_code VARCHAR(20) NOT NULL ENCODE LZO,
	ship_to_name VARCHAR(200) NOT NULL ENCODE LZO,
	ship_to_name_2 VARCHAR(200) NOT NULL ENCODE LZO,
	ship_to_address VARCHAR(100) NOT NULL ENCODE LZO,
	ship_to_address_2 VARCHAR(100) NOT NULL ENCODE LZO,
	ship_to_city VARCHAR(60) NOT NULL ENCODE LZO,
	ship_to_contact VARCHAR(100) NOT NULL ENCODE LZO,
	order_date timestamp NOT NULL ENCODE LZO,
	posting_date timestamp NOT NULL ENCODE LZO,
	expected_receipt_date timestamp NOT NULL ENCODE LZO,
	posting_description VARCHAR(100) NOT NULL ENCODE LZO,
	payment_terms_code VARCHAR(20) NOT NULL ENCODE LZO,
	due_date timestamp NOT NULL ENCODE LZO,
	payment_discount decimal(38,20) NOT NULL ENCODE LZO,
	pmt_discount_date timestamp NOT NULL ENCODE LZO,
	shipment_method_code VARCHAR(20) NOT NULL ENCODE LZO,
	location_code VARCHAR(20) NOT NULL ENCODE LZO,
	shortcut_dimension_1_code VARCHAR(40) NOT NULL ENCODE LZO,
	shortcut_dimension_2_code VARCHAR(40) NOT NULL ENCODE LZO,
	vendor_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	currency_code VARCHAR(20) NOT NULL ENCODE LZO,
	currency_factor decimal(38,20) NOT NULL ENCODE LZO,
	invoice_disc_code VARCHAR(40) NOT NULL ENCODE LZO,
	language_code VARCHAR(20) NOT NULL ENCODE LZO,
	purchaser_code VARCHAR(40) NOT NULL ENCODE LZO,
	order_no VARCHAR(40) NOT NULL ENCODE LZO,
	no_printed INTEGER NOT NULL ENCODE DELTA,
	on_hold VARCHAR(6) NOT NULL ENCODE LZO,
	applies_to_doc_type INTEGER NOT NULL ENCODE DELTA,
	applies_to_doc_no VARCHAR(40) NOT NULL ENCODE LZO,
	bal_account_no VARCHAR(40) NOT NULL ENCODE LZO,
	vendor_order_no VARCHAR(70) NOT NULL ENCODE LZO,
	vendor_shipment_no VARCHAR(70) NOT NULL ENCODE LZO,
	vat_registration_no VARCHAR(40) NOT NULL ENCODE LZO,
	sell_to_customer_no VARCHAR(40) NOT NULL ENCODE LZO,
	reason_code VARCHAR(20) NOT NULL ENCODE LZO,
	gen_bus_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	transaction_type VARCHAR(20) NOT NULL ENCODE LZO,
	transport_method VARCHAR(20) NOT NULL ENCODE LZO,
	vat_country_region_code VARCHAR(20) NOT NULL ENCODE LZO,
	buy_from_vendor_name VARCHAR(200) NOT NULL ENCODE LZO,
	buy_from_vendor_name_2 VARCHAR(200) NOT NULL ENCODE LZO,
	buy_from_address VARCHAR(100) NOT NULL ENCODE LZO,
	buy_from_address_2 VARCHAR(100) NOT NULL ENCODE LZO,
	buy_from_city VARCHAR(60) NOT NULL ENCODE LZO,
	buy_from_contact VARCHAR(100) NOT NULL ENCODE LZO,
	pay_to_post_code VARCHAR(40) NOT NULL ENCODE LZO,
	pay_to_county VARCHAR(60) NOT NULL ENCODE LZO,
	pay_to_country_region_code VARCHAR(20) NOT NULL ENCODE LZO,
	buy_from_post_code VARCHAR(40) NOT NULL ENCODE LZO,
	buy_from_county VARCHAR(60) NOT NULL ENCODE LZO,
	buy_from_country_region_code VARCHAR(20) NOT NULL ENCODE LZO,
	ship_to_post_code VARCHAR(40) NOT NULL ENCODE LZO,
	ship_to_county VARCHAR(60) NOT NULL ENCODE LZO,
	ship_to_country_region_code VARCHAR(20) NOT NULL ENCODE LZO,
	bal_account_type INTEGER NOT NULL ENCODE DELTA,
	order_address_code VARCHAR(20) NOT NULL ENCODE LZO,
	entry_point VARCHAR(20) NOT NULL ENCODE LZO,
	correction SMALLINT NOT NULL ENCODE DELTA,
	document_date timestamp NOT NULL ENCODE LZO,
	area VARCHAR(20) NOT NULL ENCODE LZO,
	transaction_specification VARCHAR(20) NOT NULL ENCODE LZO,
	payment_method_code VARCHAR(20) NOT NULL ENCODE LZO,
	no_series VARCHAR(20) NOT NULL ENCODE LZO,
	order_no_series VARCHAR(20) NOT NULL ENCODE LZO,
	user_id VARCHAR(100) NOT NULL ENCODE LZO,
	source_code VARCHAR(20) NOT NULL ENCODE LZO,
	tax_area_code VARCHAR(40) NOT NULL ENCODE LZO,
	tax_liable SMALLINT NOT NULL ENCODE DELTA,
	vat_bus_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	vat_base_discount decimal(38,20) NOT NULL ENCODE LZO,
	quote_no VARCHAR(40) NOT NULL ENCODE LZO,
	dimension_set_id INTEGER NOT NULL ENCODE DELTA,
	campaign_no VARCHAR(40) NOT NULL ENCODE LZO,
	buy_from_contact_no VARCHAR(40) NOT NULL ENCODE LZO,
	pay_to_contact_no VARCHAR(40) NOT NULL ENCODE LZO,
	responsibility_center VARCHAR(20) NOT NULL ENCODE LZO,
	requested_receipt_date timestamp NOT NULL ENCODE LZO,
	promised_receipt_date timestamp NOT NULL ENCODE LZO,
	lead_time_calculation varchar(32) NOT NULL ENCODE LZO,
	inbound_whse_handling_time varchar(32) NOT NULL ENCODE LZO,
	quality_status INTEGER NOT NULL ENCODE DELTA,
	exchange_po SMALLINT NOT NULL ENCODE DELTA,
	return_order_no VARCHAR(40) NOT NULL ENCODE LZO,
	vendor_invoice_no VARCHAR(40) NOT NULL ENCODE LZO
);


INSERT INTO NAV.purch_rcpt_header 
SELECT ts, no, buy_from_vendor_no, pay_to_vendor_no, pay_to_name, pay_to_name_2, pay_to_address, pay_to_address_2, pay_to_city, pay_to_contact, your_reference, ship_to_code, ship_to_name, ship_to_name_2, ship_to_address, ship_to_address_2, ship_to_city, ship_to_contact, order_date, posting_date, expected_receipt_date, posting_description, payment_terms_code, due_date, payment_discount, pmt_discount_date, shipment_method_code, location_code, shortcut_dimension_1_code, shortcut_dimension_2_code, vendor_posting_group, currency_code, currency_factor, invoice_disc_code, language_code, purchaser_code, order_no, no_printed, on_hold, applies_to_doc_type, applies_to_doc_no, bal_account_no, vendor_order_no, vendor_shipment_no, vat_registration_no, sell_to_customer_no, reason_code, gen_bus_posting_group, transaction_type, transport_method, vat_country_region_code, buy_from_vendor_name, buy_from_vendor_name_2, buy_from_address, buy_from_address_2, buy_from_city, buy_from_contact, pay_to_post_code, pay_to_county, pay_to_country_region_code, buy_from_post_code, buy_from_county, buy_from_country_region_code, ship_to_post_code, ship_to_county, ship_to_country_region_code, bal_account_type, order_address_code, entry_point, correction, document_date, area, transaction_specification, payment_method_code, no_series, order_no_series, user_id, source_code, tax_area_code, tax_liable, vat_bus_posting_group, vat_base_discount, quote_no, dimension_set_id, campaign_no, buy_from_contact_no, pay_to_contact_no, responsibility_center, requested_receipt_date, promised_receipt_date, lead_time_calculation, inbound_whse_handling_time, quality_status, exchange_po, return_order_no, vendor_invoice_no
FROM tmp_purch_rcpt_header;
COMMIT;