SELECT
    [timestamp] as ts,
    [Document Type] as document_type,
    No_ as no,
    [Buy-from Vendor No_] as buy_from_vendor_no,
    [Pay-to Vendor No_] as pay_to_vendor_no,
    [Pay-to Name] as pay_to_name,
    [Pay-to Name 2] as pay_to_name_2,
    [Pay-to Address] as pay_to_address,
    [Pay-to Address 2] as pay_to_address_2,
    [Pay-to City] as pay_to_city,
    [Pay-to Contact] as pay_to_contact,
    [Your Reference] as your_reference,
    [Ship-to Code] as ship_to_code,
    [Ship-to Name] as ship_to_name,
    [Ship-to Name 2] as ship_to_name_2,
    [Ship-to Address] as ship_to_address,
    [Ship-to Address 2] as ship_to_address_2,
    [Ship-to City] as ship_to_city,
    [Ship-to Contact] as ship_to_contact,
    [Order Date] as order_date,
    [Posting Date] as posting_date,
    [Expected Receipt Date] as expected_receipt_date,
    [Posting Description] as posting_description,
    [Payment Terms Code] as payment_terms_code,
    [Due Date] as due_date,
    [Payment Discount _] as payment_discount,
    [Pmt_ Discount Date] as pmt_discount_date,
    [Shipment Method Code] as shipment_method_code,
    [Location Code] as location_code,
    [Shortcut Dimension 1 Code] as shortcut_dimension_1_code,
    [Shortcut Dimension 2 Code] as shortcut_dimension_2_code,
    [Vendor Posting Group] as vendor_posting_group,
    [Currency Code] as currency_code,
    [Currency Factor] as currency_factor,
    [Prices Including VAT] as prices_including_vat,
    [Invoice Disc_ Code] as invoice_disc_code,
    [Language Code] as language_code,
    [Purchaser Code] as purchaser_code,
    [Order Class] as order_class,
    [No_ Printed] as no_printed,
    [On Hold] as on_hold,
    [Applies-to Doc_ Type] as applies_to_doc_type,
    [Applies-to Doc_ No_] as applies_to_doc_no,
    [Bal_ Account No_] as bal_account_no,
    Receive as receive,
    Invoice as invoice,
    [Print Posted Documents] as print_posted_documents,
    [Receiving No_] as receiving_no,
    [Posting No_] as posting_no,
    [Last Receiving No_] as last_receiving_no,
    [Last Posting No_] as last_posting_no,
    [Vendor Order No_] as vendor_order_no,
    [Vendor Shipment No_] as vendor_shipment_no,
    [Vendor Invoice No_] as vendor_invoice_no,
    [Vendor Cr_ Memo No_] as vendor_cr_memo_no,
    [VAT Registration No_] as vat_registration_no,
    [Sell-to Customer No_] as sell_to_customer_no,
    [Reason Code] as reason_code,
    [Gen_ Bus_ Posting Group] as gen_bus_posting_group,
    [Transaction Type] as transaction_type,
    [Transport Method] as transport_method,
    [VAT Country_Region Code] as vat_country_region_code,
    [Buy-from Vendor Name] as buy_from_vendor_name,
    [Buy-from Vendor Name 2] as buy_from_vendor_name_2,
    [Buy-from Address] as buy_from_address,
    [Buy-from Address 2] as buy_from_address_2,
    [Buy-from City] as buy_from_city,
    [Buy-from Contact] as buy_from_contact,
    [Pay-to Post Code] as pay_to_post_code,
    [Pay-to County] as pay_to_county,
    [Pay-to Country_Region Code] as pay_to_country_region_code,
    [Buy-from Post Code] as buy_from_post_code,
    [Buy-from County] as buy_from_county,
    [Buy-from Country_Region Code] as buy_from_country_region_code,
    [Ship-to Post Code] as ship_to_post_code,
    [Ship-to County] as ship_to_county,
    [Ship-to Country_Region Code] as ship_to_country_region_code,
    [Bal_ Account Type] as bal_account_type,
    [Order Address Code] as order_address_code,
    [Entry Point] as entry_point,
    Correction as correction,
    [Document Date] as document_date,
    Area as area,
    [Transaction Specification] as transaction_specification,
    [Payment Method Code] as payment_method_code,
    [No_ Series] as no_series,
    [Posting No_ Series] as posting_no_series,
    [Receiving No_ Series] as receiving_no_series,
    [Tax Area Code] as tax_area_code,
    [Tax Liable] as tax_liable,
    [VAT Bus_ Posting Group] as vat_bus_posting_group,
    [Applies-to ID] as applies_to_id,
    [VAT Base Discount _] as vat_base_discount,
    Status as status,
    [Invoice Discount Calculation] as invoice_discount_calculation,
    [Invoice Discount Value] as invoice_discount_value,
    [Send IC Document] as send_ic_document,
    [IC Status] as ic_status,
    [Buy-from IC Partner Code] as buy_from_ic_partner_code,
    [Pay-to IC Partner Code] as pay_to_ic_partner_code,
    [IC Direction] as ic_direction,
    [Prepayment No_] as prepayment_no,
    [Last Prepayment No_] as last_prepayment_no,
    [Prepmt_ Cr_ Memo No_] as prepmt_cr_memo_no,
    [Last Prepmt_ Cr_ Memo No_] as last_prepmt_cr_memo_no,
    [Prepayment _] as prepayment,
    [Prepayment No_ Series] as prepayment_no_series,
    [Compress Prepayment] as compress_prepayment,
    [Prepayment Due Date] as prepayment_due_date,
    [Prepmt_ Cr_ Memo No_ Series] as prepmt_cr_memo_no_series,
    [Prepmt_ Posting Description] as prepmt_posting_description,
    [Prepmt_ Pmt_ Discount Date] as prepmt_pmt_discount_date,
    [Prepmt_ Payment Terms Code] as prepmt_payment_terms_code,
    [Prepmt_ Payment Discount _] as prepmt_payment_discount,
    [Quote No_] as quote_no,
    [Job Queue Status] as job_queue_status,
    [Job Queue Entry ID] as job_queue_entry_id,
    [Incoming Document Entry No_] as incoming_document_entry_no,
    [Creditor No_] as creditor_no,
    [Payment Reference] as payment_reference,
    [Dimension Set ID] as dimension_set_id,
    [Doc_ No_ Occurrence] as doc_no_occurrence,
    [Campaign No_] as campaign_no,
    [Buy-from Contact No_] as buy_from_contact_no,
    [Pay-to Contact No_] as pay_to_contact_no,
    [Responsibility Center] as responsibility_center,
    [Posting from Whse_ Ref_] as posting_from_whse_ref,
    [Requested Receipt Date] as requested_receipt_date,
    [Promised Receipt Date] as promised_receipt_date,
    [Lead Time Calculation] as lead_time_calculation,
    [Inbound Whse_ Handling Time] as inbound_whse_handling_time,
    [Vendor Authorization No_] as vendor_authorization_no,
    [Return Shipment No_] as return_shipment_no,
    [Return Shipment No_ Series] as return_shipment_no_series,
    Ship as ship,
    [Last Return Shipment No_] as last_return_shipment_no,
    [Assigned User ID] as assigned_user_id,
    Region as region,
    [FOC Calculated] as foc_calculated,
    [Expiry Date] as expiry_date,
    Brand as brand,
    [Purchase Type] as purchase_type,
    [Short Close] as short_close,
    [Purchase Order Type] as purchase_order_type,
    [Purchase Department] as purchase_department,
    [PO Status] as po_status,
    [Contract No_] as contract_no,
    [Currency BTQ] as currency_btq,
    [Expiry Status] as expiry_status,
    [Exchange PO] as exchange_po,
    [Return Order No_] as return_order_no,
    [FOC PO] as foc_po
FROM Boutiqaat_Live.dbo.[Boutiqaat Kuwait\$Purchase Header]
WHERE \$CONDITIONS