BEGIN;
DROP TABLE IF EXISTS tmp_purchase_header;
CREATE TEMP TABLE tmp_purchase_header(
	ts VARCHAR(40),
	document_type INTEGER,
	no VARCHAR(40),
	buy_from_vendor_no VARCHAR(40),
	pay_to_vendor_no VARCHAR(40),
	pay_to_name VARCHAR(200),
	pay_to_name_2 VARCHAR(200),
	pay_to_address VARCHAR(100),
	pay_to_address_2 VARCHAR(100),
	pay_to_city VARCHAR(60),
	pay_to_contact VARCHAR(100),
	your_reference VARCHAR(70),
	ship_to_code VARCHAR(20),
	ship_to_name VARCHAR(200),
	ship_to_name_2 VARCHAR(200),
	ship_to_address VARCHAR(100),
	ship_to_address_2 VARCHAR(100),
	ship_to_city VARCHAR(60),
	ship_to_contact VARCHAR(100),
	order_date timestamp,
	posting_date timestamp,
	expected_receipt_date timestamp,
	posting_description VARCHAR(100),
	payment_terms_code VARCHAR(20),
	due_date timestamp,
	payment_discount decimal(38,20),
	pmt_discount_date timestamp,
	shipment_method_code VARCHAR(20),
	location_code VARCHAR(20),
	shortcut_dimension_1_code VARCHAR(40),
	shortcut_dimension_2_code VARCHAR(40),
	vendor_posting_group VARCHAR(20),
	currency_code VARCHAR(20),
	currency_factor decimal(38,20),
	prices_including_vat SMALLINT,
	invoice_disc_code VARCHAR(40),
	language_code VARCHAR(20),
	purchaser_code VARCHAR(40),
	order_class VARCHAR(20),
	no_printed INTEGER,
	on_hold VARCHAR(6),
	applies_to_doc_type INTEGER,
	applies_to_doc_no VARCHAR(40),
	bal_account_no VARCHAR(40),
	receive SMALLINT,
	invoice SMALLINT,
	print_posted_documents SMALLINT,
	receiving_no VARCHAR(40),
	posting_no VARCHAR(40),
	last_receiving_no VARCHAR(40),
	last_posting_no VARCHAR(40),
	vendor_order_no VARCHAR(70),
	vendor_shipment_no VARCHAR(70),
	vendor_invoice_no VARCHAR(70),
	vendor_cr_memo_no VARCHAR(70),
	vat_registration_no VARCHAR(40),
	sell_to_customer_no VARCHAR(40),
	reason_code VARCHAR(20),
	gen_bus_posting_group VARCHAR(20),
	transaction_type VARCHAR(20),
	transport_method VARCHAR(20),
	vat_country_region_code VARCHAR(20),
	buy_from_vendor_name VARCHAR(200),
	buy_from_vendor_name_2 VARCHAR(200),
	buy_from_address VARCHAR(100),
	buy_from_address_2 VARCHAR(100),
	buy_from_city VARCHAR(60),
	buy_from_contact VARCHAR(100),
	pay_to_post_code VARCHAR(40),
	pay_to_county VARCHAR(60),
	pay_to_country_region_code VARCHAR(20),
	buy_from_post_code VARCHAR(40),
	buy_from_county VARCHAR(60),
	buy_from_country_region_code VARCHAR(20),
	ship_to_post_code VARCHAR(40),
	ship_to_county VARCHAR(60),
	ship_to_country_region_code VARCHAR(20),
	bal_account_type INTEGER,
	order_address_code VARCHAR(20),
	entry_point VARCHAR(20),
	correction SMALLINT,
	document_date timestamp,
	area VARCHAR(20),
	transaction_specification VARCHAR(20),
	payment_method_code VARCHAR(20),
	no_series VARCHAR(20),
	posting_no_series VARCHAR(20),
	receiving_no_series VARCHAR(20),
	tax_area_code VARCHAR(40),
	tax_liable SMALLINT,
	vat_bus_posting_group VARCHAR(20),
	applies_to_id VARCHAR(100),
	vat_base_discount decimal(38,20),
	status INTEGER,
	invoice_discount_calculation INTEGER,
	invoice_discount_value decimal(38,20),
	send_ic_document SMALLINT,
	ic_status INTEGER,
	buy_from_ic_partner_code VARCHAR(40),
	pay_to_ic_partner_code VARCHAR(40),
	ic_direction INTEGER,
	prepayment_no VARCHAR(40),
	last_prepayment_no VARCHAR(40),
	prepmt_cr_memo_no VARCHAR(40),
	last_prepmt_cr_memo_no VARCHAR(40),
	prepayment decimal(38,20),
	prepayment_no_series VARCHAR(20),
	compress_prepayment SMALLINT,
	prepayment_due_date timestamp,
	prepmt_cr_memo_no_series VARCHAR(20),
	prepmt_posting_description VARCHAR(100),
	prepmt_pmt_discount_date timestamp,
	prepmt_payment_terms_code VARCHAR(20),
	prepmt_payment_discount decimal(38,20),
	quote_no VARCHAR(40),
	job_queue_status INTEGER,
	job_queue_entry_id VARCHAR(40),
	incoming_document_entry_no INTEGER,
	creditor_no VARCHAR(40),
	payment_reference VARCHAR(100),
	dimension_set_id INTEGER,
	doc_no_occurrence INTEGER,
	campaign_no VARCHAR(40),
	buy_from_contact_no VARCHAR(40),
	pay_to_contact_no VARCHAR(40),
	responsibility_center VARCHAR(20),
	posting_from_whse_ref INTEGER,
	requested_receipt_date timestamp,
	promised_receipt_date timestamp,
	lead_time_calculation varchar(32),
	inbound_whse_handling_time varchar(32),
	vendor_authorization_no VARCHAR(70),
	return_shipment_no VARCHAR(40),
	return_shipment_no_series VARCHAR(20),
	ship SMALLINT,
	last_return_shipment_no VARCHAR(40),
	assigned_user_id VARCHAR(100),
	region INTEGER,
	foc_calculated SMALLINT,
	expiry_date timestamp,
	brand VARCHAR(40),
	purchase_type INTEGER,
	short_close SMALLINT,
	purchase_order_type INTEGER,
	purchase_department VARCHAR(40),
	po_status INTEGER,
	contract_no VARCHAR(40),
	currency_btq VARCHAR(20),
	expiry_status VARCHAR(100),
	exchange_po SMALLINT,
	return_order_no VARCHAR(40),
	foc_po SMALLINT
);

copy tmp_purchase_header from '{{S3PATH}}'
iam_role 'arn:aws:iam::652586300051:role/Redshift-athena-S3-readonly'
delimiter '\t'
region 'eu-west-1' 
acceptinvchars
CSV 
GZIP 
NULL AS 'null';


DROP TABLE IF EXISTS NAV.purchase_header;
CREATE TABLE NAV.purchase_header (
	ts VARCHAR(40) NOT NULL ENCODE LZO,
	document_type INTEGER NOT NULL ENCODE DELTA,
	no VARCHAR(40) NOT NULL ENCODE LZO,
	buy_from_vendor_no VARCHAR(40) NOT NULL ENCODE LZO,
	pay_to_vendor_no VARCHAR(40) NOT NULL ENCODE LZO,
	pay_to_name VARCHAR(200) NOT NULL ENCODE LZO,
	pay_to_name_2 VARCHAR(200) NOT NULL ENCODE LZO,
	pay_to_address VARCHAR(100) NOT NULL ENCODE LZO,
	pay_to_address_2 VARCHAR(100) NOT NULL ENCODE LZO,
	pay_to_city VARCHAR(60) NOT NULL ENCODE LZO,
	pay_to_contact VARCHAR(100) NOT NULL ENCODE LZO,
	your_reference VARCHAR(70) NOT NULL ENCODE LZO,
	ship_to_code VARCHAR(20) NOT NULL ENCODE LZO,
	ship_to_name VARCHAR(200) NOT NULL ENCODE LZO,
	ship_to_name_2 VARCHAR(200) NOT NULL ENCODE LZO,
	ship_to_address VARCHAR(100) NOT NULL ENCODE LZO,
	ship_to_address_2 VARCHAR(100) NOT NULL ENCODE LZO,
	ship_to_city VARCHAR(60) NOT NULL ENCODE LZO,
	ship_to_contact VARCHAR(100) NOT NULL ENCODE LZO,
	order_date timestamp NOT NULL ENCODE LZO,
	posting_date timestamp NOT NULL ENCODE LZO,
	expected_receipt_date timestamp NOT NULL ENCODE LZO,
	posting_description VARCHAR(100) NOT NULL ENCODE LZO,
	payment_terms_code VARCHAR(20) NOT NULL ENCODE LZO,
	due_date timestamp NOT NULL ENCODE LZO,
	payment_discount decimal(38,20) NOT NULL ENCODE LZO,
	pmt_discount_date timestamp NOT NULL ENCODE LZO,
	shipment_method_code VARCHAR(20) NOT NULL ENCODE LZO,
	location_code VARCHAR(20) NOT NULL ENCODE LZO,
	shortcut_dimension_1_code VARCHAR(40) NOT NULL ENCODE LZO,
	shortcut_dimension_2_code VARCHAR(40) NOT NULL ENCODE LZO,
	vendor_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	currency_code VARCHAR(20) NOT NULL ENCODE LZO,
	currency_factor decimal(38,20) NOT NULL ENCODE LZO,
	prices_including_vat SMALLINT NOT NULL ENCODE DELTA,
	invoice_disc_code VARCHAR(40) NOT NULL ENCODE LZO,
	language_code VARCHAR(20) NOT NULL ENCODE LZO,
	purchaser_code VARCHAR(40) NOT NULL ENCODE LZO,
	order_class VARCHAR(20) NOT NULL ENCODE LZO,
	no_printed INTEGER NOT NULL ENCODE DELTA,
	on_hold VARCHAR(6) NOT NULL ENCODE LZO,
	applies_to_doc_type INTEGER NOT NULL ENCODE DELTA,
	applies_to_doc_no VARCHAR(40) NOT NULL ENCODE LZO,
	bal_account_no VARCHAR(40) NOT NULL ENCODE LZO,
	receive SMALLINT NOT NULL ENCODE DELTA,
	invoice SMALLINT NOT NULL ENCODE DELTA,
	print_posted_documents SMALLINT NOT NULL ENCODE DELTA,
	receiving_no VARCHAR(40) NOT NULL ENCODE LZO,
	posting_no VARCHAR(40) NOT NULL ENCODE LZO,
	last_receiving_no VARCHAR(40) NOT NULL ENCODE LZO,
	last_posting_no VARCHAR(40) NOT NULL ENCODE LZO,
	vendor_order_no VARCHAR(70) NOT NULL ENCODE LZO,
	vendor_shipment_no VARCHAR(70) NOT NULL ENCODE LZO,
	vendor_invoice_no VARCHAR(70) NOT NULL ENCODE LZO,
	vendor_cr_memo_no VARCHAR(70) NOT NULL ENCODE LZO,
	vat_registration_no VARCHAR(40) NOT NULL ENCODE LZO,
	sell_to_customer_no VARCHAR(40) NOT NULL ENCODE LZO,
	reason_code VARCHAR(20) NOT NULL ENCODE LZO,
	gen_bus_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	transaction_type VARCHAR(20) NOT NULL ENCODE LZO,
	transport_method VARCHAR(20) NOT NULL ENCODE LZO,
	vat_country_region_code VARCHAR(20) NOT NULL ENCODE LZO,
	buy_from_vendor_name VARCHAR(200) NOT NULL ENCODE LZO,
	buy_from_vendor_name_2 VARCHAR(200) NOT NULL ENCODE LZO,
	buy_from_address VARCHAR(100) NOT NULL ENCODE LZO,
	buy_from_address_2 VARCHAR(100) NOT NULL ENCODE LZO,
	buy_from_city VARCHAR(60) NOT NULL ENCODE LZO,
	buy_from_contact VARCHAR(100) NOT NULL ENCODE LZO,
	pay_to_post_code VARCHAR(40) NOT NULL ENCODE LZO,
	pay_to_county VARCHAR(60) NOT NULL ENCODE LZO,
	pay_to_country_region_code VARCHAR(20) NOT NULL ENCODE LZO,
	buy_from_post_code VARCHAR(40) NOT NULL ENCODE LZO,
	buy_from_county VARCHAR(60) NOT NULL ENCODE LZO,
	buy_from_country_region_code VARCHAR(20) NOT NULL ENCODE LZO,
	ship_to_post_code VARCHAR(40) NOT NULL ENCODE LZO,
	ship_to_county VARCHAR(60) NOT NULL ENCODE LZO,
	ship_to_country_region_code VARCHAR(20) NOT NULL ENCODE LZO,
	bal_account_type INTEGER NOT NULL ENCODE DELTA,
	order_address_code VARCHAR(20) NOT NULL ENCODE LZO,
	entry_point VARCHAR(20) NOT NULL ENCODE LZO,
	correction SMALLINT NOT NULL ENCODE DELTA,
	document_date timestamp NOT NULL ENCODE LZO,
	area VARCHAR(20) NOT NULL ENCODE LZO,
	transaction_specification VARCHAR(20) NOT NULL ENCODE LZO,
	payment_method_code VARCHAR(20) NOT NULL ENCODE LZO,
	no_series VARCHAR(20) NOT NULL ENCODE LZO,
	posting_no_series VARCHAR(20) NOT NULL ENCODE LZO,
	receiving_no_series VARCHAR(20) NOT NULL ENCODE LZO,
	tax_area_code VARCHAR(40) NOT NULL ENCODE LZO,
	tax_liable SMALLINT NOT NULL ENCODE DELTA,
	vat_bus_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	applies_to_id VARCHAR(100) NOT NULL ENCODE LZO,
	vat_base_discount decimal(38,20) NOT NULL ENCODE LZO,
	status INTEGER NOT NULL ENCODE DELTA,
	invoice_discount_calculation INTEGER NOT NULL ENCODE DELTA,
	invoice_discount_value decimal(38,20) NOT NULL ENCODE LZO,
	send_ic_document SMALLINT NOT NULL ENCODE DELTA,
	ic_status INTEGER NOT NULL ENCODE DELTA,
	buy_from_ic_partner_code VARCHAR(40) NOT NULL ENCODE LZO,
	pay_to_ic_partner_code VARCHAR(40) NOT NULL ENCODE LZO,
	ic_direction INTEGER NOT NULL ENCODE DELTA,
	prepayment_no VARCHAR(40) NOT NULL ENCODE LZO,
	last_prepayment_no VARCHAR(40) NOT NULL ENCODE LZO,
	prepmt_cr_memo_no VARCHAR(40) NOT NULL ENCODE LZO,
	last_prepmt_cr_memo_no VARCHAR(40) NOT NULL ENCODE LZO,
	prepayment decimal(38,20) NOT NULL ENCODE LZO,
	prepayment_no_series VARCHAR(20) NOT NULL ENCODE LZO,
	compress_prepayment SMALLINT NOT NULL ENCODE DELTA,
	prepayment_due_date timestamp NOT NULL ENCODE LZO,
	prepmt_cr_memo_no_series VARCHAR(20) NOT NULL ENCODE LZO,
	prepmt_posting_description VARCHAR(100) NOT NULL ENCODE LZO,
	prepmt_pmt_discount_date timestamp NOT NULL ENCODE LZO,
	prepmt_payment_terms_code VARCHAR(20) NOT NULL ENCODE LZO,
	prepmt_payment_discount decimal(38,20) NOT NULL ENCODE LZO,
	quote_no VARCHAR(40) NOT NULL ENCODE LZO,
	job_queue_status INTEGER NOT NULL ENCODE DELTA,
	job_queue_entry_id VARCHAR(40) NOT NULL ENCODE LZO,
	incoming_document_entry_no INTEGER NOT NULL ENCODE DELTA,
	creditor_no VARCHAR(40) NOT NULL ENCODE LZO,
	payment_reference VARCHAR(100) NOT NULL ENCODE LZO,
	dimension_set_id INTEGER NOT NULL ENCODE DELTA,
	doc_no_occurrence INTEGER NOT NULL ENCODE DELTA,
	campaign_no VARCHAR(40) NOT NULL ENCODE LZO,
	buy_from_contact_no VARCHAR(40) NOT NULL ENCODE LZO,
	pay_to_contact_no VARCHAR(40) NOT NULL ENCODE LZO,
	responsibility_center VARCHAR(20) NOT NULL ENCODE LZO,
	posting_from_whse_ref INTEGER NOT NULL ENCODE DELTA,
	requested_receipt_date timestamp NOT NULL ENCODE LZO,
	promised_receipt_date timestamp NOT NULL ENCODE LZO,
	lead_time_calculation varchar(32) NOT NULL ENCODE LZO,
	inbound_whse_handling_time varchar(32) NOT NULL ENCODE LZO,
	vendor_authorization_no VARCHAR(70) NOT NULL ENCODE LZO,
	return_shipment_no VARCHAR(40) NOT NULL ENCODE LZO,
	return_shipment_no_series VARCHAR(20) NOT NULL ENCODE LZO,
	ship SMALLINT NOT NULL ENCODE DELTA,
	last_return_shipment_no VARCHAR(40) NOT NULL ENCODE LZO,
	assigned_user_id VARCHAR(100) NOT NULL ENCODE LZO,
	region INTEGER NOT NULL ENCODE DELTA,
	foc_calculated SMALLINT NOT NULL ENCODE DELTA,
	expiry_date timestamp NOT NULL ENCODE LZO,
	brand VARCHAR(40) NOT NULL ENCODE LZO,
	purchase_type INTEGER NOT NULL ENCODE DELTA,
	short_close SMALLINT NOT NULL ENCODE DELTA,
	purchase_order_type INTEGER NOT NULL ENCODE DELTA,
	purchase_department VARCHAR(40) NOT NULL ENCODE LZO,
	po_status INTEGER NOT NULL ENCODE DELTA,
	contract_no VARCHAR(40) NOT NULL ENCODE LZO,
	currency_btq VARCHAR(20) NOT NULL ENCODE LZO,
	expiry_status VARCHAR(100) NOT NULL ENCODE LZO,
	exchange_po SMALLINT NOT NULL ENCODE DELTA,
	return_order_no VARCHAR(40) NOT NULL ENCODE LZO,
	foc_po SMALLINT NOT NULL ENCODE DELTA
);


INSERT INTO NAV.purchase_header 
SELECT ts, document_type, no, buy_from_vendor_no, pay_to_vendor_no, pay_to_name, pay_to_name_2, pay_to_address, pay_to_address_2, pay_to_city, pay_to_contact, your_reference, ship_to_code, ship_to_name, ship_to_name_2, ship_to_address, ship_to_address_2, ship_to_city, ship_to_contact, order_date, posting_date, expected_receipt_date, posting_description, payment_terms_code, due_date, payment_discount, pmt_discount_date, shipment_method_code, location_code, shortcut_dimension_1_code, shortcut_dimension_2_code, vendor_posting_group, currency_code, currency_factor, prices_including_vat, invoice_disc_code, language_code, purchaser_code, order_class, no_printed, on_hold, applies_to_doc_type, applies_to_doc_no, bal_account_no, receive, invoice, print_posted_documents, receiving_no, posting_no, last_receiving_no, last_posting_no, vendor_order_no, vendor_shipment_no, vendor_invoice_no, vendor_cr_memo_no, vat_registration_no, sell_to_customer_no, reason_code, gen_bus_posting_group, transaction_type, transport_method, vat_country_region_code, buy_from_vendor_name, buy_from_vendor_name_2, buy_from_address, buy_from_address_2, buy_from_city, buy_from_contact, pay_to_post_code, pay_to_county, pay_to_country_region_code, buy_from_post_code, buy_from_county, buy_from_country_region_code, ship_to_post_code, ship_to_county, ship_to_country_region_code, bal_account_type, order_address_code, entry_point, correction, document_date, area, transaction_specification, payment_method_code, no_series, posting_no_series, receiving_no_series, tax_area_code, tax_liable, vat_bus_posting_group, applies_to_id, vat_base_discount, status, invoice_discount_calculation, invoice_discount_value, send_ic_document, ic_status, buy_from_ic_partner_code, pay_to_ic_partner_code, ic_direction, prepayment_no, last_prepayment_no, prepmt_cr_memo_no, last_prepmt_cr_memo_no, prepayment, prepayment_no_series, compress_prepayment, prepayment_due_date, prepmt_cr_memo_no_series, prepmt_posting_description, prepmt_pmt_discount_date, prepmt_payment_terms_code, prepmt_payment_discount, quote_no, job_queue_status, job_queue_entry_id, incoming_document_entry_no, creditor_no, payment_reference, dimension_set_id, doc_no_occurrence, campaign_no, buy_from_contact_no, pay_to_contact_no, responsibility_center, posting_from_whse_ref, requested_receipt_date, promised_receipt_date, lead_time_calculation, inbound_whse_handling_time, vendor_authorization_no, return_shipment_no, return_shipment_no_series, ship, last_return_shipment_no, assigned_user_id, region, foc_calculated, expiry_date, brand, purchase_type, short_close, purchase_order_type, purchase_department, po_status, contract_no, currency_btq, expiry_status, exchange_po, return_order_no, foc_po
FROM tmp_purchase_header;
COMMIT;