SELECT *
FROM (SELECT 
    CAST((@row_number:=@row_number + 1) as UNSIGNED) AS num,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(location), '\r', ''),'\n',''),'\t',''),'\"', '') as location,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(supplier), '\r', ''),'\n',''),'\t',''),'\"', '') as supplier,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(supplier_item_no), '\r', ''),'\n',''),'\t',''),'\"', '') as supplier_item_no,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(vendor_code), '\r', ''),'\n',''),'\t',''),'\"', '') as vendor_code,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(brand), '\r', ''),'\n',''),'\t',''),'\"', '') as brand,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(brand_code), '\r', ''),'\n',''),'\t',''),'\"', '') as brand_code,
    sku,
    sku2,
    barcode,
    category1,
    category2,
    category3,
    category4,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(sku_name), '\r', ''),'\n',''),'\t',''),'\"', '') as sku_name,
    retail_price,
    cost_price,
    soh,
    open_po_total_qty,
    open_po_pending_receipt_qty,
    open_po_partially_received_qty,
    open_po_pending_cancellation_qty,
    reserved_qty,
    first_grn_date,
    last_grn_date,
    payment_term_code,
    country,
    stock_entry_synched_at,
    sale_entry_synched_at,
    report_date,
    sold_qty_today,
    sold_qty_yesterday,
    sold_qty_7days,
    sold_qty_14days,
    sold_qty_mtd,
    sold_qty_m1,
    sold_qty_m2,
    sold_qty_m3,
    sold_qty_m4,
    sold_qty_m5,
    sold_qty_lifetime,
    sellable_quantity,
    not_sellable_quantity,
    nav_total_quantity,
    department,
    category_manager,
    hod
FROM aoi.soh_report, (SELECT @row_number:=0) AS t) as sub
WHERE \$CONDITIONS