SELECT 
    id, 
    store_id, 
    device_token, 
    device_type, 
    lang, 
    payment, 
    myfatoorah_payment, 
    shipping_address_id, 
    shipping_method, 
    customer_id, 
    transaction_id, 
    tx_amount, 
    currency, 
    reference_order_id, 
    FROM_UNIXTIME(created_time) as created_time,
    state, 
    FROM_UNIXTIME(last_updated) as last_updated,
    increment_id, 
    payment_id,
    result, 
    payment_method, 
    qty_revert, 
    cod_charge, 
    shipping_charge, 
    shipping_address, 
    billing_address, 
    customer_email, 
    custom_duty, 
    vat, 
    clearance_charge, 
    converted_order_total, 
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(notes), '\r', ''),'\n',''),'\t',''),'\"', '') as notes, 
    use_customer_balance, 
    base_customer_bal_amount_used, 
    customer_balance_amount_used, 
    credit_revert, 
    coupon_code
FROM boutiqaat_middlelayer.order_queue
WHERE \$CONDITIONS