SELECT
    [timestamp] as ts,
    [Document No_] as document_no,
    [Line No_] as line_no,
    [Buy-from Vendor No_] as buy_from_vendor_no,
    [Type] as type,
    No_ as no,
    [Location Code] as location_code,
    [Posting Group] as posting_group,
    [Expected Receipt Date] as expected_receipt_date,
    REPLACE(REPLACE(REPLACE(REPLACE(Description, CHAR(13), ''), CHAR(10), ''), CHAR(9), ''),'\"', '') as description,
    REPLACE(REPLACE(REPLACE(REPLACE([Description 2], CHAR(13), ''), CHAR(10), ''), CHAR(9), ''),'\"', '') as description_2,
    [Unit of Measure] as unit_of_measure,
    Quantity as quantity,
    [Direct Unit Cost] as direct_unit_cost,
    [Unit Cost (LCY)] as unit_cost_lcy,
    [VAT _] as vat,
    [Line Discount _] as line_discount,
    [Unit Price (LCY)] as unit_price_lcy,
    [Allow Invoice Disc_] as allow_invoice_disc,
    [Gross Weight] as gross_weight,
    [Net Weight] as net_weight,
    [Units per Parcel] as units_per_parcel,
    [Unit Volume] as unit_volume,
    [Appl_-to Item Entry] as appl_to_item_entry,
    [Item Rcpt_ Entry No_] as item_rcpt_entry_no,
    [Shortcut Dimension 1 Code] as shortcut_dimension_1_code,
    [Shortcut Dimension 2 Code] as shortcut_dimension_2_code,
    [Job No_] as job_no,
    [Indirect Cost _] as indirect_cost,
    [Qty_ Rcd_ Not Invoiced] as qty_rcd_not_invoiced,
    [Quantity Invoiced] as quantity_invoiced,
    [Order No_] as order_no,
    [Order Line No_] as order_line_no,
    [Pay-to Vendor No_] as pay_to_vendor_no,
    [Vendor Item No_] as vendor_item_no,
    [Sales Order No_] as sales_order_no,
    [Sales Order Line No_] as sales_order_line_no,
    [Gen_ Bus_ Posting Group] as gen_bus_posting_group,
    [Gen_ Prod_ Posting Group] as gen_prod_posting_group,
    [VAT Calculation Type] as vat_calculation_type,
    [Transaction Type] as transaction_type,
    [Transport Method] as transport_method,
    [Attached to Line No_] as attached_to_line_no,
    [Entry Point] as entry_point,
    Area as area,
    [Transaction Specification] as transaction_specification,
    [Tax Area Code] as tax_area_code,
    [Tax Liable] as tax_liable,
    [Tax Group Code] as tax_group_code,
    [Use Tax] as use_tax,
    [VAT Bus_ Posting Group] as vat_bus_posting_group,
    [VAT Prod_ Posting Group] as vat_prod_posting_group,
    [Blanket Order No_] as blanket_order_no,
    [Blanket Order Line No_] as blanket_order_line_no,
    [VAT Base Amount] as vat_base_amount,
    [Unit Cost] as unit_cost,
    [Posting Date] as posting_date,
    [Dimension Set ID] as dimension_set_id,
    [Job Task No_] as job_task_no,
    [Job Line Type] as job_line_type,
    [Job Unit Price] as job_unit_price,
    [Job Total Price] as job_total_price,
    [Job Line Amount] as job_line_amount,
    [Job Line Discount Amount] as job_line_discount_amount,
    [Job Line Discount _] as job_line_discount,
    [Job Unit Price (LCY)] as job_unit_price_lcy,
    [Job Total Price (LCY)] as job_total_price_lcy,
    [Job Line Amount (LCY)] as job_line_amount_lcy,
    [Job Line Disc_ Amount (LCY)] as job_line_disc_amount_lcy,
    [Job Currency Factor] as job_currency_factor,
    [Job Currency Code] as job_currency_code,
    [Prod_ Order No_] as prod_order_no,
    [Variant Code] as variant_code,
    [Bin Code] as bin_code,
    [Qty_ per Unit of Measure] as qty_per_unit_of_measure,
    [Unit of Measure Code] as unit_of_measure_code,
    [Quantity (Base)] as quantity_base,
    [Qty_ Invoiced (Base)] as qty_invoiced_base,
    [FA Posting Date] as fa_posting_date,
    [FA Posting Type] as fa_posting_type,
    [Depreciation Book Code] as depreciation_book_code,
    [Salvage Value] as salvage_value,
    [Depr_ until FA Posting Date] as depr_until_fa_posting_date,
    [Depr_ Acquisition Cost] as depr_acquisition_cost,
    [Maintenance Code] as maintenance_code,
    [Insurance No_] as insurance_no,
    [Budgeted FA No_] as budgeted_fa_no,
    [Duplicate in Depreciation Book] as duplicate_in_depreciation_book,
    [Use Duplication List] as use_duplication_list,
    [Responsibility Center] as responsibility_center,
    [Cross-Reference No_] as cross_reference_no,
    [Unit of Measure (Cross Ref_)] as unit_of_measure_cross_ref,
    [Cross-Reference Type] as cross_reference_type,
    [Cross-Reference Type No_] as cross_reference_type_no,
    [Item Category Code] as item_category_code,
    Nonstock as nonstock,
    [Purchasing Code] as purchasing_code,
    [Product Group Code] as product_group_code,
    [Special Order Sales No_] as special_order_sales_no,
    [Special Order Sales Line No_] as special_order_sales_line_no,
    [Requested Receipt Date] as requested_receipt_date,
    [Promised Receipt Date] as promised_receipt_date,
    [Lead Time Calculation] as lead_time_calculation,
    [Inbound Whse_ Handling Time] as inbound_whse_handling_time,
    [Planned Receipt Date] as planned_receipt_date,
    [Order Date] as order_date,
    [Item Charge Base Amount] as item_charge_base_amount,
    Correction as correction,
    [Return Reason Code] as return_reason_code,
    FOC as foc,
    [Contract No_] as contract_no,
    Margin as margin,
    [Add_ Margin] as add_margin,
    [Add_ FOC Quantity] as add_foc_quantity,
    [Purchase Cost] as purchase_cost,
    Tester as tester,
    [EAN Code] as ean_code,
    Narration as narration,
    [Inventory Type] as inventory_type,
    [Routing No_] as routing_no,
    [Operation No_] as operation_no,
    [Work Center No_] as work_center_no,
    [Prod_ Order Line No_] as prod_order_line_no,
    [Overhead Rate] as overhead_rate,
    [Routing Reference No_] as routing_reference_no
FROM Boutiqaat_Live.dbo.[Boutiqaat Kuwait\$Purch_ Rcpt_ Line]
WHERE \$CONDITIONS