BEGIN;
DROP TABLE IF EXISTS tmp_purch_rcpt_line;
CREATE TEMP TABLE tmp_purch_rcpt_line(
	ts VARCHAR(40),
	document_no VARCHAR(40),
	line_no INTEGER,
	buy_from_vendor_no VARCHAR(40),
	type INTEGER,
	no VARCHAR(40),
	location_code VARCHAR(20),
	posting_group VARCHAR(20),
	expected_receipt_date timestamp,
	description VARCHAR(400),
	description_2 VARCHAR(400),
	unit_of_measure VARCHAR(20),
	quantity decimal(38,20),
	direct_unit_cost decimal(38,20),
	unit_cost_lcy decimal(38,20),
	vat decimal(38,20),
	line_discount decimal(38,20),
	unit_price_lcy decimal(38,20),
	allow_invoice_disc SMALLINT,
	gross_weight decimal(38,20),
	net_weight decimal(38,20),
	units_per_parcel decimal(38,20),
	unit_volume decimal(38,20),
	appl_to_item_entry INTEGER,
	item_rcpt_entry_no INTEGER,
	shortcut_dimension_1_code VARCHAR(40),
	shortcut_dimension_2_code VARCHAR(40),
	job_no VARCHAR(40),
	indirect_cost decimal(38,20),
	qty_rcd_not_invoiced decimal(38,20),
	quantity_invoiced decimal(38,20),
	order_no VARCHAR(40),
	order_line_no INTEGER,
	pay_to_vendor_no VARCHAR(40),
	vendor_item_no VARCHAR(40),
	sales_order_no VARCHAR(40),
	sales_order_line_no INTEGER,
	gen_bus_posting_group VARCHAR(20),
	gen_prod_posting_group VARCHAR(20),
	vat_calculation_type INTEGER,
	transaction_type VARCHAR(20),
	transport_method VARCHAR(20),
	attached_to_line_no INTEGER,
	entry_point VARCHAR(20),
	area VARCHAR(20),
	transaction_specification VARCHAR(20),
	tax_area_code VARCHAR(40),
	tax_liable SMALLINT,
	tax_group_code VARCHAR(20),
	use_tax SMALLINT,
	vat_bus_posting_group VARCHAR(20),
	vat_prod_posting_group VARCHAR(20),
	blanket_order_no VARCHAR(40),
	blanket_order_line_no INTEGER,
	vat_base_amount decimal(38,20),
	unit_cost decimal(38,20),
	posting_date timestamp,
	dimension_set_id INTEGER,
	job_task_no VARCHAR(40),
	job_line_type INTEGER,
	job_unit_price decimal(38,20),
	job_total_price decimal(38,20),
	job_line_amount decimal(38,20),
	job_line_discount_amount decimal(38,20),
	job_line_discount decimal(38,20),
	job_unit_price_lcy decimal(38,20),
	job_total_price_lcy decimal(38,20),
	job_line_amount_lcy decimal(38,20),
	job_line_disc_amount_lcy decimal(38,20),
	job_currency_factor decimal(38,20),
	job_currency_code VARCHAR(40),
	prod_order_no VARCHAR(40),
	variant_code VARCHAR(20),
	bin_code VARCHAR(40),
	qty_per_unit_of_measure decimal(38,20),
	unit_of_measure_code VARCHAR(20),
	quantity_base decimal(38,20),
	qty_invoiced_base decimal(38,20),
	fa_posting_date timestamp,
	fa_posting_type INTEGER,
	depreciation_book_code VARCHAR(20),
	salvage_value decimal(38,20),
	depr_until_fa_posting_date SMALLINT,
	depr_acquisition_cost SMALLINT,
	maintenance_code VARCHAR(20),
	insurance_no VARCHAR(40),
	budgeted_fa_no VARCHAR(40),
	duplicate_in_depreciation_book VARCHAR(20),
	use_duplication_list SMALLINT,
	responsibility_center VARCHAR(20),
	cross_reference_no VARCHAR(40),
	unit_of_measure_cross_ref VARCHAR(20),
	cross_reference_type INTEGER,
	cross_reference_type_no VARCHAR(60),
	item_category_code VARCHAR(40),
	nonstock SMALLINT,
	purchasing_code VARCHAR(20),
	product_group_code VARCHAR(40),
	special_order_sales_no VARCHAR(40),
	special_order_sales_line_no INTEGER,
	requested_receipt_date timestamp,
	promised_receipt_date timestamp,
	lead_time_calculation varchar(32),
	inbound_whse_handling_time varchar(32),
	planned_receipt_date timestamp,
	order_date timestamp,
	item_charge_base_amount decimal(38,20),
	correction SMALLINT,
	return_reason_code VARCHAR(20),
	foc SMALLINT,
	contract_no VARCHAR(40),
	margin decimal(38,20),
	add_margin decimal(38,20),
	add_foc_quantity decimal(38,20),
	purchase_cost decimal(38,20),
	tester SMALLINT,
	ean_code VARCHAR(60),
	narration VARCHAR(500),
	inventory_type INTEGER,
	routing_no VARCHAR(40),
	operation_no VARCHAR(20),
	work_center_no VARCHAR(40),
	prod_order_line_no INTEGER,
	overhead_rate decimal(38,20),
	routing_reference_no INTEGER
);

copy tmp_purch_rcpt_line from '{{S3PATH}}'
iam_role 'arn:aws:iam::652586300051:role/Redshift-athena-S3-readonly'
delimiter '\t'
region 'eu-west-1' 
acceptinvchars
CSV 
GZIP 
NULL AS 'null';


DROP TABLE IF EXISTS NAV.purch_rcpt_line;
CREATE TABLE NAV.purch_rcpt_line (
    ts VARCHAR(40) NOT NULL ENCODE LZO,
	document_no VARCHAR(40) NOT NULL ENCODE LZO,
	line_no INTEGER NOT NULL ENCODE DELTA,
	buy_from_vendor_no VARCHAR(40) NOT NULL ENCODE LZO,
	type INTEGER NOT NULL ENCODE DELTA,
	no VARCHAR(40) NOT NULL ENCODE LZO,
	location_code VARCHAR(20) NOT NULL ENCODE LZO,
	posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	expected_receipt_date timestamp NOT NULL ENCODE LZO,
	description VARCHAR(400) NOT NULL ENCODE LZO,
	description_2 VARCHAR(400) NOT NULL ENCODE LZO,
	unit_of_measure VARCHAR(20) NOT NULL ENCODE LZO,
	quantity decimal(38,20) NOT NULL ENCODE LZO,
	direct_unit_cost decimal(38,20) NOT NULL ENCODE LZO,
	unit_cost_lcy decimal(38,20) NOT NULL ENCODE LZO,
	vat decimal(38,20) NOT NULL ENCODE LZO,
	line_discount decimal(38,20) NOT NULL ENCODE LZO,
	unit_price_lcy decimal(38,20) NOT NULL ENCODE LZO,
	allow_invoice_disc SMALLINT NOT NULL ENCODE DELTA,
	gross_weight decimal(38,20) NOT NULL ENCODE LZO,
	net_weight decimal(38,20) NOT NULL ENCODE LZO,
	units_per_parcel decimal(38,20) NOT NULL ENCODE LZO,
	unit_volume decimal(38,20) NOT NULL ENCODE LZO,
	appl_to_item_entry INTEGER NOT NULL ENCODE DELTA,
	item_rcpt_entry_no INTEGER NOT NULL ENCODE DELTA,
	shortcut_dimension_1_code VARCHAR(40) NOT NULL ENCODE LZO,
	shortcut_dimension_2_code VARCHAR(40) NOT NULL ENCODE LZO,
	job_no VARCHAR(40) NOT NULL ENCODE LZO,
	indirect_cost decimal(38,20) NOT NULL ENCODE LZO,
	qty_rcd_not_invoiced decimal(38,20) NOT NULL ENCODE LZO,
	quantity_invoiced decimal(38,20) NOT NULL ENCODE LZO,
	order_no VARCHAR(40) NOT NULL ENCODE LZO,
	order_line_no INTEGER NOT NULL ENCODE DELTA,
	pay_to_vendor_no VARCHAR(40) NOT NULL ENCODE LZO,
	vendor_item_no VARCHAR(40) NOT NULL ENCODE LZO,
	sales_order_no VARCHAR(40) NOT NULL ENCODE LZO,
	sales_order_line_no INTEGER NOT NULL ENCODE DELTA,
	gen_bus_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	gen_prod_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	vat_calculation_type INTEGER NOT NULL ENCODE DELTA,
	transaction_type VARCHAR(20) NOT NULL ENCODE LZO,
	transport_method VARCHAR(20) NOT NULL ENCODE LZO,
	attached_to_line_no INTEGER NOT NULL ENCODE DELTA,
	entry_point VARCHAR(20) NOT NULL ENCODE LZO,
	area VARCHAR(20) NOT NULL ENCODE LZO,
	transaction_specification VARCHAR(20) NOT NULL ENCODE LZO,
	tax_area_code VARCHAR(40) NOT NULL ENCODE LZO,
	tax_liable SMALLINT NOT NULL ENCODE DELTA,
	tax_group_code VARCHAR(20) NOT NULL ENCODE LZO,
	use_tax SMALLINT NOT NULL ENCODE DELTA,
	vat_bus_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	vat_prod_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	blanket_order_no VARCHAR(40) NOT NULL ENCODE LZO,
	blanket_order_line_no INTEGER NOT NULL ENCODE DELTA,
	vat_base_amount decimal(38,20) NOT NULL ENCODE LZO,
	unit_cost decimal(38,20) NOT NULL ENCODE LZO,
	posting_date timestamp NOT NULL ENCODE LZO,
	dimension_set_id INTEGER NOT NULL ENCODE DELTA,
	job_task_no VARCHAR(40) NOT NULL ENCODE LZO,
	job_line_type INTEGER NOT NULL ENCODE DELTA,
	job_unit_price decimal(38,20) NOT NULL ENCODE LZO,
	job_total_price decimal(38,20) NOT NULL ENCODE LZO,
	job_line_amount decimal(38,20) NOT NULL ENCODE LZO,
	job_line_discount_amount decimal(38,20) NOT NULL ENCODE LZO,
	job_line_discount decimal(38,20) NOT NULL ENCODE LZO,
	job_unit_price_lcy decimal(38,20) NOT NULL ENCODE LZO,
	job_total_price_lcy decimal(38,20) NOT NULL ENCODE LZO,
	job_line_amount_lcy decimal(38,20) NOT NULL ENCODE LZO,
	job_line_disc_amount_lcy decimal(38,20) NOT NULL ENCODE LZO,
	job_currency_factor decimal(38,20) NOT NULL ENCODE LZO,
	job_currency_code VARCHAR(40) NOT NULL ENCODE LZO,
	prod_order_no VARCHAR(40) NOT NULL ENCODE LZO,
	variant_code VARCHAR(20) NOT NULL ENCODE LZO,
	bin_code VARCHAR(40) NOT NULL ENCODE LZO,
	qty_per_unit_of_measure decimal(38,20) NOT NULL ENCODE LZO,
	unit_of_measure_code VARCHAR(20) NOT NULL ENCODE LZO,
	quantity_base decimal(38,20) NOT NULL ENCODE LZO,
	qty_invoiced_base decimal(38,20) NOT NULL ENCODE LZO,
	fa_posting_date timestamp NOT NULL ENCODE LZO,
	fa_posting_type INTEGER NOT NULL ENCODE DELTA,
	depreciation_book_code VARCHAR(20) NOT NULL ENCODE LZO,
	salvage_value decimal(38,20) NOT NULL ENCODE LZO,
	depr_until_fa_posting_date SMALLINT NOT NULL ENCODE DELTA,
	depr_acquisition_cost SMALLINT NOT NULL ENCODE DELTA,
	maintenance_code VARCHAR(20) NOT NULL ENCODE LZO,
	insurance_no VARCHAR(40) NOT NULL ENCODE LZO,
	budgeted_fa_no VARCHAR(40) NOT NULL ENCODE LZO,
	duplicate_in_depreciation_book VARCHAR(20) NOT NULL ENCODE LZO,
	use_duplication_list SMALLINT NOT NULL ENCODE DELTA,
	responsibility_center VARCHAR(20) NOT NULL ENCODE LZO,
	cross_reference_no VARCHAR(40) NOT NULL ENCODE LZO,
	unit_of_measure_cross_ref VARCHAR(20) NOT NULL ENCODE LZO,
	cross_reference_type INTEGER NOT NULL ENCODE DELTA,
	cross_reference_type_no VARCHAR(60) NOT NULL ENCODE LZO,
	item_category_code VARCHAR(40) NOT NULL ENCODE LZO,
	nonstock SMALLINT NOT NULL ENCODE DELTA,
	purchasing_code VARCHAR(20) NOT NULL ENCODE LZO,
	product_group_code VARCHAR(40) NOT NULL ENCODE LZO,
	special_order_sales_no VARCHAR(40) NOT NULL ENCODE LZO,
	special_order_sales_line_no INTEGER NOT NULL ENCODE DELTA,
	requested_receipt_date timestamp NOT NULL ENCODE LZO,
	promised_receipt_date timestamp NOT NULL ENCODE LZO,
	lead_time_calculation varchar(32) NOT NULL ENCODE LZO,
	inbound_whse_handling_time varchar(32) NOT NULL ENCODE LZO,
	planned_receipt_date timestamp NOT NULL ENCODE LZO,
	order_date timestamp NOT NULL ENCODE LZO,
	item_charge_base_amount decimal(38,20) NOT NULL ENCODE LZO,
	correction SMALLINT NOT NULL ENCODE DELTA,
	return_reason_code VARCHAR(20) NOT NULL ENCODE LZO,
	foc SMALLINT NOT NULL ENCODE DELTA,
	contract_no VARCHAR(40) NOT NULL ENCODE LZO,
	margin decimal(38,20) NOT NULL ENCODE LZO,
	add_margin decimal(38,20) NOT NULL ENCODE LZO,
	add_foc_quantity decimal(38,20) NOT NULL ENCODE LZO,
	purchase_cost decimal(38,20) NOT NULL ENCODE LZO,
	tester SMALLINT NOT NULL ENCODE DELTA,
	ean_code VARCHAR(60) NOT NULL ENCODE LZO,
	narration VARCHAR(500) NOT NULL ENCODE LZO,
	inventory_type INTEGER NOT NULL ENCODE DELTA,
	routing_no VARCHAR(40) NOT NULL ENCODE LZO,
	operation_no VARCHAR(20) NOT NULL ENCODE LZO,
	work_center_no VARCHAR(40) NOT NULL ENCODE LZO,
	prod_order_line_no INTEGER NOT NULL ENCODE DELTA,
	overhead_rate decimal(38,20) NOT NULL ENCODE LZO,
	routing_reference_no INTEGER NOT NULL ENCODE DELTA
);


INSERT INTO NAV.purch_rcpt_line 
SELECT ts, document_no, line_no, buy_from_vendor_no, type, no, location_code, posting_group, expected_receipt_date, description, description_2, unit_of_measure, quantity, direct_unit_cost, unit_cost_lcy, vat, line_discount, unit_price_lcy, allow_invoice_disc, gross_weight, net_weight, units_per_parcel, unit_volume, appl_to_item_entry, item_rcpt_entry_no, shortcut_dimension_1_code, shortcut_dimension_2_code, job_no, indirect_cost, qty_rcd_not_invoiced, quantity_invoiced, order_no, order_line_no, pay_to_vendor_no, vendor_item_no, sales_order_no, sales_order_line_no, gen_bus_posting_group, gen_prod_posting_group, vat_calculation_type, transaction_type, transport_method, attached_to_line_no, entry_point, area, transaction_specification, tax_area_code, tax_liable, tax_group_code, use_tax, vat_bus_posting_group, vat_prod_posting_group, blanket_order_no, blanket_order_line_no, vat_base_amount, unit_cost, posting_date, dimension_set_id, job_task_no, job_line_type, job_unit_price, job_total_price, job_line_amount, job_line_discount_amount, job_line_discount, job_unit_price_lcy, job_total_price_lcy, job_line_amount_lcy, job_line_disc_amount_lcy, job_currency_factor, job_currency_code, prod_order_no, variant_code, bin_code, qty_per_unit_of_measure, unit_of_measure_code, quantity_base, qty_invoiced_base, fa_posting_date, fa_posting_type, depreciation_book_code, salvage_value, depr_until_fa_posting_date, depr_acquisition_cost, maintenance_code, insurance_no, budgeted_fa_no, duplicate_in_depreciation_book, use_duplication_list, responsibility_center, cross_reference_no, unit_of_measure_cross_ref, cross_reference_type, cross_reference_type_no, item_category_code, nonstock, purchasing_code, product_group_code, special_order_sales_no, special_order_sales_line_no, requested_receipt_date, promised_receipt_date, lead_time_calculation, inbound_whse_handling_time, planned_receipt_date, order_date, item_charge_base_amount, correction, return_reason_code, foc, contract_no, margin, add_margin, add_foc_quantity, purchase_cost, tester, ean_code, narration, inventory_type, routing_no, operation_no, work_center_no, prod_order_line_no, overhead_rate, routing_reference_no
FROM tmp_purch_rcpt_line;
COMMIT;