drop table if exists cohort_kwd;
create table cohort_kwd select customer_id, country,
DATE(first_order_date) first_order_date, 
MONTH(first_order_date) AS Month_Of_First_Purchase, 
YEAR(first_order_date) AS Year_Of_First_Purchase, 
extract(year_month from first_order_date) cohort, 

COUNT(DISTINCT IF(order_date=first_order_date,customer_id,NULL)) m0,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 1 DAY) AND DATE_ADD(first_order_date , INTERVAL 30 DAY),customer_id,NULL)) m1,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 31 DAY) AND DATE_ADD(first_order_date , INTERVAL 60 DAY),customer_id,NULL)) m2,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 61 DAY) AND DATE_ADD(first_order_date , INTERVAL 90 DAY),customer_id,NULL)) m3,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 91 DAY) AND DATE_ADD(first_order_date , INTERVAL 120 DAY),customer_id,NULL)) m4,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 121 DAY) AND DATE_ADD(first_order_date , INTERVAL 150 DAY),customer_id,NULL)) m5,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 151 DAY) AND DATE_ADD(first_order_date , INTERVAL 180 DAY),customer_id,NULL)) m6,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 181 DAY) AND DATE_ADD(first_order_date , INTERVAL 210 DAY),customer_id,NULL)) m7,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 211 DAY) AND DATE_ADD(first_order_date , INTERVAL 240 DAY),customer_id,NULL)) m8,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 241 DAY) AND DATE_ADD(first_order_date , INTERVAL 270 DAY),customer_id,NULL)) m9,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 271 DAY) AND DATE_ADD(first_order_date , INTERVAL 300 DAY),customer_id,NULL)) m10,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 301 DAY) AND DATE_ADD(first_order_date , INTERVAL 330 DAY),customer_id,NULL)) m11,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 331 DAY) AND DATE_ADD(first_order_date , INTERVAL 360 DAY),customer_id,NULL)) m12,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 361 DAY) AND DATE_ADD(first_order_date , INTERVAL 390 DAY),customer_id,NULL)) m13,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 391 DAY) AND DATE_ADD(first_order_date , INTERVAL 420 DAY),customer_id,NULL)) m14,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 421 DAY) AND DATE_ADD(first_order_date , INTERVAL 450 DAY),customer_id,NULL)) m15,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 451 DAY) AND DATE_ADD(first_order_date , INTERVAL 480 DAY),customer_id,NULL)) m16,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 481 DAY) AND DATE_ADD(first_order_date , INTERVAL 510 DAY),customer_id,NULL)) m17,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 511 DAY) AND DATE_ADD(first_order_date , INTERVAL 540 DAY),customer_id,NULL)) m18,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 541 DAY) AND DATE_ADD(first_order_date , INTERVAL 570 DAY),customer_id,NULL)) m19,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 571 DAY) AND DATE_ADD(first_order_date , INTERVAL 600 DAY),customer_id,NULL)) m20,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 601 DAY) AND DATE_ADD(first_order_date , INTERVAL 630 DAY),customer_id,NULL)) m21,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 631 DAY) AND DATE_ADD(first_order_date , INTERVAL 660 DAY),customer_id,NULL)) m22,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 661 DAY) AND DATE_ADD(first_order_date , INTERVAL 690 DAY),customer_id,NULL)) m23,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 691 DAY) AND DATE_ADD(first_order_date , INTERVAL 720 DAY),customer_id,NULL)) m24,
COUNT(DISTINCT IF(order_date > DATE_ADD(first_order_date , INTERVAL 720 DAY),customer_id,NULL)) m25andmore,

SUM(IF(order_date=first_order_date,gmv,0)) m0_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 1 DAY) AND DATE_ADD(first_order_date , INTERVAL 30 DAY),gmv,0)) m1_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 31 DAY) AND DATE_ADD(first_order_date , INTERVAL 60 DAY),gmv,0)) m2_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 61 DAY) AND DATE_ADD(first_order_date , INTERVAL 90 DAY),gmv,0)) m3_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 91 DAY) AND DATE_ADD(first_order_date , INTERVAL 120 DAY),gmv,0)) m4_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 121 DAY) AND DATE_ADD(first_order_date , INTERVAL 150 DAY),gmv,0)) m5_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 151 DAY) AND DATE_ADD(first_order_date , INTERVAL 180 DAY),gmv,0)) m6_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 181 DAY) AND DATE_ADD(first_order_date , INTERVAL 210 DAY),gmv,0)) m7_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 211 DAY) AND DATE_ADD(first_order_date , INTERVAL 240 DAY),gmv,0)) m8_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 241 DAY) AND DATE_ADD(first_order_date , INTERVAL 270 DAY),gmv,0)) m9_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 271 DAY) AND DATE_ADD(first_order_date , INTERVAL 300 DAY),gmv,0)) m10_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 301 DAY) AND DATE_ADD(first_order_date , INTERVAL 330 DAY),gmv,0)) m11_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 331 DAY) AND DATE_ADD(first_order_date , INTERVAL 360 DAY),gmv,0)) m12_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 361 DAY) AND DATE_ADD(first_order_date , INTERVAL 390 DAY),gmv,0)) m13_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 391 DAY) AND DATE_ADD(first_order_date , INTERVAL 420 DAY),gmv,0)) m14_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 421 DAY) AND DATE_ADD(first_order_date , INTERVAL 450 DAY),gmv,0)) m15_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 451 DAY) AND DATE_ADD(first_order_date , INTERVAL 480 DAY),gmv,0)) m16_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 481 DAY) AND DATE_ADD(first_order_date , INTERVAL 510 DAY),gmv,0)) m17_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 511 DAY) AND DATE_ADD(first_order_date , INTERVAL 540 DAY),gmv,0)) m18_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 541 DAY) AND DATE_ADD(first_order_date , INTERVAL 570 DAY),gmv,0)) m19_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 571 DAY) AND DATE_ADD(first_order_date , INTERVAL 600 DAY),gmv,0)) m20_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 601 DAY) AND DATE_ADD(first_order_date , INTERVAL 630 DAY),gmv,0)) m21_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 631 DAY) AND DATE_ADD(first_order_date , INTERVAL 660 DAY),gmv,0)) m22_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 661 DAY) AND DATE_ADD(first_order_date , INTERVAL 690 DAY),gmv,0)) m23_gmv,
SUM(IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 691 DAY) AND DATE_ADD(first_order_date , INTERVAL 720 DAY),gmv,0)) m24_gmv,
SUM(IF(order_date > DATE_ADD(first_order_date , INTERVAL 720 DAY),gmv,0)) m25andmore_gmv,

COUNT(DISTINCT IF(order_date=first_order_date,order_id,NULL)) m0_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 1 DAY) AND DATE_ADD(first_order_date , INTERVAL 30 DAY),order_id,NULL)) m1_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 31 DAY) AND DATE_ADD(first_order_date , INTERVAL 60 DAY),order_id,NULL)) m2_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 61 DAY) AND DATE_ADD(first_order_date , INTERVAL 90 DAY),order_id,NULL)) m3_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 91 DAY) AND DATE_ADD(first_order_date , INTERVAL 120 DAY),order_id,NULL)) m4_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 121 DAY) AND DATE_ADD(first_order_date , INTERVAL 150 DAY),order_id,NULL)) m5_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 151 DAY) AND DATE_ADD(first_order_date , INTERVAL 180 DAY),order_id,NULL)) m6_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 181 DAY) AND DATE_ADD(first_order_date , INTERVAL 210 DAY),order_id,NULL)) m7_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 211 DAY) AND DATE_ADD(first_order_date , INTERVAL 240 DAY),order_id,NULL)) m8_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 241 DAY) AND DATE_ADD(first_order_date , INTERVAL 270 DAY),order_id,NULL)) m9_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 271 DAY) AND DATE_ADD(first_order_date , INTERVAL 300 DAY),order_id,NULL)) m10_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 301 DAY) AND DATE_ADD(first_order_date , INTERVAL 330 DAY),order_id,NULL)) m11_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 331 DAY) AND DATE_ADD(first_order_date , INTERVAL 360 DAY),order_id,NULL)) m12_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 361 DAY) AND DATE_ADD(first_order_date , INTERVAL 390 DAY),order_id,NULL)) m13_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 391 DAY) AND DATE_ADD(first_order_date , INTERVAL 420 DAY),order_id,NULL)) m14_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 421 DAY) AND DATE_ADD(first_order_date , INTERVAL 450 DAY),order_id,NULL)) m15_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 451 DAY) AND DATE_ADD(first_order_date , INTERVAL 480 DAY),order_id,NULL)) m16_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 481 DAY) AND DATE_ADD(first_order_date , INTERVAL 510 DAY),order_id,NULL)) m17_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 511 DAY) AND DATE_ADD(first_order_date , INTERVAL 540 DAY),order_id,NULL)) m18_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 541 DAY) AND DATE_ADD(first_order_date , INTERVAL 570 DAY),order_id,NULL)) m19_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 571 DAY) AND DATE_ADD(first_order_date , INTERVAL 600 DAY),order_id,NULL)) m20_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 601 DAY) AND DATE_ADD(first_order_date , INTERVAL 630 DAY),order_id,NULL)) m21_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 631 DAY) AND DATE_ADD(first_order_date , INTERVAL 660 DAY),order_id,NULL)) m22_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 661 DAY) AND DATE_ADD(first_order_date , INTERVAL 690 DAY),order_id,NULL)) m23_order,
COUNT(DISTINCT IF(order_date BETWEEN DATE_ADD(first_order_date , INTERVAL 691 DAY) AND DATE_ADD(first_order_date , INTERVAL 720 DAY),order_id,NULL)) m24_order,
COUNT(DISTINCT IF(order_date > DATE_ADD(first_order_date , INTERVAL 720 DAY),order_id,NULL)) m25andmore_order
from (select sales_order_grid.customer_id, sales_order_grid.increment_id order_id, sales_order_grid.grand_total gmv, DATE(sales_order_grid.created_at) order_date, DATE(first_order_date) first_order_date, customer_first_order.country from sales_order_grid  join customer_first_order on sales_order_grid.customer_id = customer_first_order.customer_id ) e group by customer_id;
