#GOOGLE to ERP Mapping on Product
drop table if exists product_google_cat;
create table product_google_cat as select cpf.sku id, cat1.ID cat1,cat2.ID cat2,cat3.ID cat3, coalesce(map1.code, map2.code, map3.code, map4.code) google_cat_code, cat1.NAME_E cat1_name  from (select sku from catalog_product_flat_1 group by sku) as cpf LEFT JOIN (select PRODN, CAT1, CAT2, CAT3, CAT4 from ITEMS group by PRODN) i on i.PRODN=cpf.sku LEFT JOIN PRODUCT_CAT1 cat1 on i.CAT1=cat1.ID LEFT JOIN PRODUCT_CAT2 cat2 on i.CAT2=cat2.ID LEFT JOIN PRODUCT_CAT3 cat3 on i.CAT3=cat3.ID left join google_erp_category_mapping map1 on map1.cat1_id =  cat1.ID and map1.cat2_id =  cat2.ID and map1.cat3_id = cat3.ID left join google_erp_category_mapping map2 on  map2.cat1_id =  cat1.ID and map2.cat2_id =  cat2.ID  left join (select code,cat1_id from google_erp_category_mapping where cat2_id is NULL and cat3_id is NULL) map3 on map3.cat1_id =  cat1.ID left join google_erp_category_mapping map4 on map4.cat2_id =  cat2.ID GROUP BY cpf.sku;
create index product_google_cat_idx on product_google_cat (id);



#KWD
#======
drop table if exists fb_feed_kwd;
create table fb_feed_kwd as  
SELECT cpf.sku id, replace(cpf.name,'"','') as title, concat("boutiqaat://product_id/", cpf.entity_id) `ios_url`,  concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) `android_url`,"1021268294" as `ios_app_store_id`, "Boutiqaat: Beauty Shopping" as `ios_app_name`, "com.lezasolutions.boutiqaat" as `android_package`, "Boutiqaat: Beauty Shopping" as `android_app_name`, cpf.description  as description, concat("https://www.boutiqaat.com/en-kw/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat(cpf.price, " KWD") price, concat(coalesce(cpf.special_price, cpf.price), " KWD") as sale_price, cpf.special_to_date as sale_price_effective_date, gcat.google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, cpf.manufacturer_value as brand_name, 'new' as `condition` FROM catalog_product_flat_1 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id  LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="KWD" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code') GROUP BY cpf.sku ORDER BY cpf.entity_id  ;


#AED
#======
drop table if exists fb_feed_aed;
create table fb_feed_aed as 
SELECT cpf.sku id, replace(cpf.name,'"','') as title, concat("boutiqaat://product_id/", cpf.entity_id) `ios_url`,  concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) `android_url`,"1021268294" as `ios_app_store_id`, "Boutiqaat: Beauty Shopping" as `ios_app_name`, "com.lezasolutions.boutiqaat" as `android_package`, "Boutiqaat: Beauty Shopping" as `android_app_name`, cpf.description  as description, concat("https://www.boutiqaat.com/en-ae/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1,"in stock","out of stock") as availability,   concat(FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0), " AED") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " AED") as sale_price, cpf.special_to_date as sale_price_effective_date, gcat.google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, cpf.manufacturer_value as brand_name, 'new' as `condition` FROM catalog_product_flat_1 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="AED" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code')  GROUP BY cpf.sku ORDER BY cpf.entity_id  ;



#BHD
#======
drop table if exists fb_feed_bhd;
create table fb_feed_bhd as  
SELECT cpf.sku id, replace(cpf.name,'"','') as title, concat("boutiqaat://product_id/", cpf.entity_id) `ios_url`,  concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) `android_url`,"1021268294" as `ios_app_store_id`, "Boutiqaat: Beauty Shopping" as `ios_app_name`, "com.lezasolutions.boutiqaat" as `android_package`, "Boutiqaat: Beauty Shopping" as `android_app_name`, cpf.description  as description, concat("https://www.boutiqaat.com/en-bh/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat(FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0), " BHD") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " BHD") as sale_price, cpf.special_to_date as sale_price_effective_date, google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, cpf.manufacturer_value as brand_name, 'new' as `condition` FROM catalog_product_flat_1 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="BHD" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code')  GROUP BY cpf.sku ORDER BY cpf.entity_id  ;

#OMR
#======
drop table if exists fb_feed_omr;
create table fb_feed_omr as  
SELECT cpf.sku id, replace(cpf.name,'"','') as title, concat("boutiqaat://product_id/", cpf.entity_id) `ios_url`,  concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) `android_url`,"1021268294" as `ios_app_store_id`, "Boutiqaat: Beauty Shopping" as `ios_app_name`, "com.lezasolutions.boutiqaat" as `android_package`, "Boutiqaat: Beauty Shopping" as `android_app_name`, cpf.description  as description, concat("https://www.boutiqaat.com/en-om/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat(FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0), " OMR") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " OMR") as sale_price, cpf.special_to_date as sale_price_effective_date, google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, cpf.manufacturer_value as brand_name, 'new' as `condition` FROM catalog_product_flat_1 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="OMR" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code')  GROUP BY cpf.sku ORDER BY cpf.entity_id  ;

#QAR
#======
drop table if exists fb_feed_qar;
create table fb_feed_qar as  
SELECT cpf.sku id, replace(cpf.name,'"','') as title, concat("boutiqaat://product_id/", cpf.entity_id) `ios_url`,  concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) `android_url`,"1021268294" as `ios_app_store_id`, "Boutiqaat: Beauty Shopping" as `ios_app_name`, "com.lezasolutions.boutiqaat" as `android_package`, "Boutiqaat: Beauty Shopping" as `android_app_name`, cpf.description  as description, concat("https://www.boutiqaat.com/en-qa/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat(FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0), " QAR") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " QAR") as sale_price, cpf.special_to_date as sale_price_effective_date, google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, cpf.manufacturer_value as brand_name, 'new' as `condition` FROM catalog_product_flat_1 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="QAR" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code')  GROUP BY cpf.sku ORDER BY cpf.entity_id  ;

#SAR
#======
drop table if exists fb_feed_sar;
create table fb_feed_sar as  
SELECT cpf.sku id, replace(cpf.name,'"','') as title, concat("boutiqaat://product_id/", cpf.entity_id) `ios_url`,  concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) `android_url`,"1021268294" as `ios_app_store_id`, "Boutiqaat: Beauty Shopping" as `ios_app_name`, "com.lezasolutions.boutiqaat" as `android_package`, "Boutiqaat: Beauty Shopping" as `android_app_name`, cpf.description  as description, concat("https://www.boutiqaat.com/en-sa/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat(FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0), " SAR") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " SAR") as sale_price, cpf.special_to_date as sale_price_effective_date, google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, cpf.manufacturer_value as brand_name, 'new' as `condition` FROM catalog_product_flat_1 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="SAR" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code')  GROUP BY cpf.sku ORDER BY cpf.entity_id  ;

#USD
#======
drop table if exists fb_feed_usd;
create table fb_feed_usd as  
SELECT cpf.sku id, replace(cpf.name,'"','') as title, concat("boutiqaat://product_id/", cpf.entity_id) `ios_url`,  concat("android-app://com.lezasolutions.boutiqaat/boutiqaat/product_id/", cpf.entity_id) `android_url`,"1021268294" as `ios_app_store_id`, "Boutiqaat: Beauty Shopping" as `ios_app_name`, "com.lezasolutions.boutiqaat" as `android_package`, "Boutiqaat: Beauty Shopping" as `android_app_name`, cpf.description  as description, concat("https://www.boutiqaat.com/en-kw/", cpf.url_key, "/p/") as link, concat("https://v2cdn.boutiqaat.com/media/catalog/product", small_image) as image_link, if(ci.stock_status=1, "in stock", "out of stock") as availability, concat(FLOOR(cpf.price*curr.rate)+IF(MOD((cpf.price*curr.rate),1)>0.25,1,0), " USD") price, concat((FLOOR(coalesce(cpf.special_price, cpf.price)*curr.rate)+IF(MOD((coalesce(cpf.special_price, cpf.price)*curr.rate),1)>0.25,1,0)), " USD") as sale_price, cpf.special_to_date as sale_price_effective_date, google_cat_code as google_product_category, gcat.cat1_name, cpev.value as gtin, cpf.manufacturer_value as brand_name, 'new' as `condition` FROM catalog_product_flat_1 as cpf LEFT JOIN product_google_cat gcat on gcat.id = cpf.sku LEFT JOIN cataloginventory_stock_status as ci ON ci.product_id = cpf.entity_id LEFT JOIN catalog_category_product as cat on cpf.entity_id = cat.product_id LEFT JOIN directory_currency_rate curr on curr.currency_from = "KWD" and curr.currency_to="USD" LEFT JOIN catalog_product_entity_varchar as cpev on cpf.entity_id = cpev.row_id AND cpev.attribute_id = (SELECT attribute_id FROM eav_attribute WHERE attribute_code = 'bar_code')  GROUP BY cpf.sku ORDER BY cpf.entity_id  ;

update fb_feed_aed           f left join huda_sku_barcode h on f.id=h.sku set f.gtin=h.barcode where brand_name='Huda Beauty';
update fb_feed_bhd           f left join huda_sku_barcode h on f.id=h.sku set f.gtin=h.barcode where brand_name='Huda Beauty';
update fb_feed_kwd           f left join huda_sku_barcode h on f.id=h.sku set f.gtin=h.barcode where brand_name='Huda Beauty';
update fb_feed_omr           f left join huda_sku_barcode h on f.id=h.sku set f.gtin=h.barcode where brand_name='Huda Beauty';
update fb_feed_qar           f left join huda_sku_barcode h on f.id=h.sku set f.gtin=h.barcode where brand_name='Huda Beauty';
update fb_feed_sar           f left join huda_sku_barcode h on f.id=h.sku set f.gtin=h.barcode where brand_name='Huda Beauty';
update fb_feed_usd           f left join huda_sku_barcode h on f.id=h.sku set f.gtin=h.barcode where brand_name='Huda Beauty';

