(/usr/local/bin/mysql -v --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB < /opt/feeds/scripts/google_feed_create.sql && echo 'DONE' && echo `date -u`)
(/usr/local/bin/mysql -v --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB < /opt/feeds/scripts/fb_feed_create.sql && echo 'DONE' && echo `date -u`)
cd /opt/feeds
mkdir "$(date +"%Y-%m-%d")"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,android_url,ios_app_name,android_package,android_app_name,link,image_link,availability,price,sale_price, google_product_category,gtin,brand_name Brand, cat1_name product_type,  \`condition\` as \"condition\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_aed where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_aed_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,android_url,ios_app_name,android_package,android_app_name,link,image_link,availability,price,sale_price, google_product_category,gtin,brand_name Brand, cat1_name product_type,  \`condition\` as \"condition\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_bhd where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_bhd_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,android_url,ios_app_name,android_package,android_app_name,link,image_link,availability,price,sale_price, google_product_category,gtin,brand_name Brand, cat1_name product_type,  \`condition\` as \"condition\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_kwd where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_kwd_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,android_url,ios_app_name,android_package,android_app_name,link,image_link,availability,price,sale_price, google_product_category,gtin,brand_name Brand, cat1_name product_type,  \`condition\` as \"condition\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_omr where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_omr_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,android_url,ios_app_name,android_package,android_app_name,link,image_link,availability,price,sale_price, google_product_category,gtin,brand_name Brand, cat1_name product_type,  \`condition\` as \"condition\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_qar where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_qar_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,android_url,ios_app_name,android_package,android_app_name,link,image_link,availability,price,sale_price, google_product_category,gtin,brand_name Brand, cat1_name product_type,  \`condition\` as \"condition\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_sar where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_sar_$(date +"%Y-%m-%d").tsv"


/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id ID, mobile_ios_app_store_id \"iOS App Store ID\",title \"Item Title\",mobile_ios_app_link \"iOS App Link\",mobile_android_app_link \"Android App Link\",link \"Final URL\", image_link \"Image URL\", price \"Price\", google_product_category \"Item Category\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as \"Item Description\" from google_feed_bhd where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_bhd_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id ID, mobile_ios_app_store_id \"iOS App Store ID\",title \"Item Title\",mobile_ios_app_link \"iOS App Link\",mobile_android_app_link \"Android App Link\",link \"Final URL\", image_link \"Image URL\", price \"Price\", google_product_category \"Item Category\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as \"Item Description\" from google_feed_kwd where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_kwd_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id ID, mobile_ios_app_store_id \"iOS App Store ID\",title \"Item Title\",mobile_ios_app_link \"iOS App Link\",mobile_android_app_link \"Android App Link\",link \"Final URL\", image_link \"Image URL\", price \"Price\", google_product_category \"Item Category\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as \"Item Description\" from google_feed_omr where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_omr_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id ID, mobile_ios_app_store_id \"iOS App Store ID\",title \"Item Title\",mobile_ios_app_link \"iOS App Link\",mobile_android_app_link \"Android App Link\",link \"Final URL\", image_link \"Image URL\", price \"Price\", google_product_category \"Item Category\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as \"Item Description\" from google_feed_qar where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_qar_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id, mobile_ios_app_store_id,title,mobile_ios_app_link,mobile_android_app_link,link,image_link,availability,price,sale_price,sale_price as effective_sale_price, google_product_category,IF(identifier_exists='Yes',gtin,'') as gtin,identifier_exists,brand_name brand, cat1_name product_type,  \`condition\` as \"condition\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from google_feed_aed where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_aed_$(date +"%Y-%m-%d").txt"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id, mobile_ios_app_store_id,title,mobile_ios_app_link,mobile_android_app_link,link,image_link,availability,price,sale_price,sale_price as effective_sale_price, google_product_category,IF(identifier_exists='Yes',gtin,'') as gtin,identifier_exists,brand_name brand, cat1_name product_type,  \`condition\` as \"condition\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from google_feed_sar where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/\"//g;s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_sar_$(date +"%Y-%m-%d").txt"

yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_aed_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_aed.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_bhd_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_bhd.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_kwd_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_kwd.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_omr_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_omr.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_qar_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_qar.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/fb_feed_sar_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_sar.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_bhd_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/google_feed_bhd.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_kwd_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/google_feed_kwd.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_omr_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/google_feed_omr.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_qar_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/google_feed_qar.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_aed_$(date +"%Y-%m-%d").txt" /var/mktg-feeds/google_feed_aed.txt
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/google_feed_sar_$(date +"%Y-%m-%d").txt" /var/mktg-feeds/google_feed_sar.txt

aws s3 cp /var/mktg-feeds/ s3://mktg-feeds/ --region ap-south-1 --recursive

