(/usr/local/bin/mysql -v --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB < /opt/feeds/scripts/google_feed_create.sql && echo 'DONE' && echo `date -u`)
(/usr/local/bin/mysql -v --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB < /opt/feeds/scripts/fb_feed_create.sql && echo 'DONE' && echo `date -u`)
cd /opt/feeds
mkdir "$(date +"%Y-%m-%d")"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,ios_url as android_url,ios_app_name,android_package,android_app_name,link,image_link,availability, price, sale_price, google_product_category,gtin,brand_name Brand, \`condition\` as \"condition\", IF(bf_sale_sku.sku IS NULL,\"\",\"Black Friday\") \"custom label 0\", IF(bf_sale_sku.sku IS NULL,sale_price_effective_date,\"2018-12-24T23:59:59+03:00/2018-12-29T23:59:59+03:00\") as sale_price_effective_date, coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_aed left join bf_sale_sku on bf_sale_sku.sku=fb_feed_aed.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_aed_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,ios_url as android_url,ios_app_name,android_package,android_app_name,link,image_link,availability, price, sale_price, google_product_category,gtin,brand_name Brand,  \`condition\` as \"condition\", IF(bf_sale_sku.sku IS NULL,\"\",\"Black Friday\") \"custom label 0\", IF(bf_sale_sku.sku IS NULL,sale_price_effective_date,\"2018-12-24T23:59:59+03:00/2018-12-29T23:59:59+03:00\") as sale_price_effective_date, coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_bhd left join bf_sale_sku on bf_sale_sku.sku=fb_feed_bhd.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_bhd_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,ios_url as android_url,ios_app_name,android_package,android_app_name,link,image_link,availability, price, sale_price, google_product_category,gtin,brand_name Brand,  \`condition\` as \"condition\", IF(bf_sale_sku.sku IS NULL,\"\",\"Black Friday\") \"custom label 0\", IF(bf_sale_sku.sku IS NULL,sale_price_effective_date,\"2018-12-24T23:59:59+03:00/2018-12-29T23:59:59+03:00\") as sale_price_effective_date, coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_kwd left join bf_sale_sku on bf_sale_sku.sku=fb_feed_kwd.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_kwd_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,ios_url as android_url,ios_app_name,android_package,android_app_name,link,image_link,availability, price, sale_price, google_product_category,gtin,brand_name Brand,  \`condition\` as \"condition\", IF(bf_sale_sku.sku IS NULL,\"\",\"Black Friday\") \"custom label 0\", IF(bf_sale_sku.sku IS NULL,sale_price_effective_date,\"2018-12-24T23:59:59+03:00/2018-12-29T23:59:59+03:00\") as sale_price_effective_date, coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_omr left join bf_sale_sku on bf_sale_sku.sku=fb_feed_omr.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_omr_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,ios_url as android_url,ios_app_name,android_package,android_app_name,link,image_link,availability, price, sale_price, google_product_category,gtin,brand_name Brand,  \`condition\` as \"condition\", IF(bf_sale_sku.sku IS NULL,\"\",\"Black Friday\") \"custom label 0\", IF(bf_sale_sku.sku IS NULL,sale_price_effective_date,\"2018-12-24T23:59:59+03:00/2018-12-29T23:59:59+03:00\") as sale_price_effective_date, coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_qar left join bf_sale_sku on bf_sale_sku.sku=fb_feed_qar.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_qar_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id,ios_app_store_id,title,ios_url,ios_url as android_url,ios_app_name,android_package,android_app_name,link,image_link,availability, price, sale_price, google_product_category,gtin,brand_name Brand,  \`condition\` as \"condition\", IF(bf_sale_sku.sku IS NULL,\"\",\"Black Friday\") \"custom label 0\", IF(bf_sale_sku.sku IS NULL,sale_price_effective_date,\"2018-12-24T23:59:59+03:00/2018-12-29T23:59:59+03:00\") as sale_price_effective_date, coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from fb_feed_sar left join bf_sale_sku on bf_sale_sku.sku=fb_feed_sar.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_sar_$(date +"%Y-%m-%d").tsv"


/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id ID, mobile_ios_app_store_id \"iOS App Store ID\",title \"Item Title\",mobile_ios_app_link \"iOS App Link\",mobile_android_app_link \"Android App Link\",link \"Final URL\", image_link \"Image URL\", sale_price as \"Price\", google_product_category \"Item Category\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as \"Item Description\" from google_feed_bhd join bf_sale_sku on bf_sale_sku.sku=google_feed_bhd.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_bhd_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id ID, mobile_ios_app_store_id \"iOS App Store ID\",title \"Item Title\",mobile_ios_app_link \"iOS App Link\",mobile_android_app_link \"Android App Link\",link \"Final URL\", image_link \"Image URL\", sale_price as \"Price\", google_product_category \"Item Category\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as \"Item Description\" from google_feed_kwd join bf_sale_sku on bf_sale_sku.sku=google_feed_kwd.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_kwd_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id ID, mobile_ios_app_store_id \"iOS App Store ID\",title \"Item Title\",mobile_ios_app_link \"iOS App Link\",mobile_android_app_link \"Android App Link\",link \"Final URL\", image_link \"Image URL\", sale_price as \"Price\", google_product_category \"Item Category\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as \"Item Description\" from google_feed_omr join bf_sale_sku on bf_sale_sku.sku=google_feed_omr.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_omr_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id ID, mobile_ios_app_store_id \"iOS App Store ID\",title \"Item Title\",mobile_ios_app_link \"iOS App Link\",mobile_android_app_link \"Android App Link\",link \"Final URL\", image_link \"Image URL\", sale_price as \"Price\", google_product_category \"Item Category\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as \"Item Description\" from google_feed_qar join bf_sale_sku on bf_sale_sku.sku=google_feed_qar.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_qar_$(date +"%Y-%m-%d").tsv"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id, mobile_ios_app_store_id,title,mobile_ios_app_link,mobile_android_app_link,link,image_link,availability, price, sale_price,sale_price as effective_sale_price, google_product_category,IF(identifier_exists='Yes',gtin,'') as gtin,identifier_exists,brand_name brand,  \`condition\` as \"condition\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from google_feed_aed left join bf_sale_sku on bf_sale_sku.sku=google_feed_aed.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_aed_$(date +"%Y-%m-%d").txt"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select id, mobile_ios_app_store_id,title,mobile_ios_app_link,mobile_android_app_link,link,image_link,availability,price, sale_price,sale_price as effective_sale_price, google_product_category,IF(identifier_exists='Yes',gtin,'') as gtin,identifier_exists,brand_name brand,  \`condition\` as \"condition\", coalesce(replace(replace(replace(description,'\"',''),'\r\n',' '),'\n',' '),'') as description from google_feed_sar left join bf_sale_sku on bf_sale_sku.sku=google_feed_sar.id where image_link is not NULL and link is not NULL and availability is not NULL and price is not NULL and brand_name is not NULL and gtin is not NULL and google_product_category is not NULL and availability='in stock';" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_sar_$(date +"%Y-%m-%d").txt"

/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select * from google_feed_aed_index;" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_aed_index_$(date +"%Y-%m-%d").txt"
/usr/local/bin/mysql -B --host=$DWH_MYSQL_HOST --user=$DWH_MYSQL_USER --password=$DWH_MYSQL_PASSWD $DWH_MYSQL_DB -e "Select * from google_feed_sar_index;" | sed "s/NULL//;s/'/\'/;s/\t/\"\t\"/g;s/^/\"/;s/$/\"/;s/\n//g" > "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_sar_index_$(date +"%Y-%m-%d").txt"

yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_aed_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_aed.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_bhd_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_bhd.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_kwd_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_kwd.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_omr_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_omr.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_qar_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_qar.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_fb_feed_sar_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/fb_feed_sar.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_bhd_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/google_feed_bhd_bf.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_kwd_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/google_feed_kwd_bf.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_omr_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/google_feed_omr_bf.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_qar_$(date +"%Y-%m-%d").tsv" /var/mktg-feeds/google_feed_qar_bf.tsv
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_aed_$(date +"%Y-%m-%d").txt" /var/mktg-feeds/google_feed_aed.txt
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_sar_$(date +"%Y-%m-%d").txt" /var/mktg-feeds/google_feed_sar.txt

yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_aed_index_$(date +"%Y-%m-%d").txt" /var/mktg-feeds/google_feed_aed_index.txt
yes|cp -f "/opt/feeds/$(date +"%Y-%m-%d")/bf_sale_google_feed_sar_index_$(date +"%Y-%m-%d").txt" /var/mktg-feeds/google_feed_sar_index.txt

aws s3 cp /var/mktg-feeds/ s3://mktg-feeds/ --region ap-south-1 --recursive

