CREATE TABLE stock_details
    (
        id                      INT(11) NOT NULL auto_increment,
        report_date             date,
        sku                       VARCHAR(20),
        supplier_barcode            VARCHAR(50),
        product_name                VARCHAR(255),
        category1                VARCHAR(20),
        category2                VARCHAR(20),
        category3                VARCHAR(20),
        category4                VARCHAR(20),
        brand                    VARCHAR(100),
        grn_no                DECIMAL(15,0),
        vendor_code                INT(11),
        grn_date                    DATETIME,
        is_visible            BOOLEAN,
        location              VARCHAR(100), 
        url                        VARCHAR(255),
        payment_term                DECIMAL(38,0),
        unit_price                DECIMAL(30,6),
        list_price                DECIMAL(30,6),
        quantity                DECIMAL(30,6),
        total_cost                DECIMAL(30,6),
        is_exclusive                 BOOLEAN,
        is_celebexclusive        BOOLEAN,
        celebrity_name         VARCHAR(100),
        age                     VARCHAR(20),
        grossqtysold_lastday  INT(11),
        grossqtysold_7days     INT(11),
        grossqtysold_14days     INT(11),
        grossqtysold_30days     INT(11),
        grossqtysold_ytd      INT(11),
        grossqtysold_total     INT(11),
        grossrevenue_lastday     DECIMAL(30,6),
        grossrevenue_7days        DECIMAL(30,6),
        grossrevenue_14days        DECIMAL(30,6),
        grossrevenue_30days         DECIMAL(30,6),
        grossrevenue_ytd         DECIMAL(30,6),
        grossrevenue_total DECIMAL(30,6),
        grosscm1_lastday         DECIMAL(30,6),
        grosscm1_7days             DECIMAL(30,6),
        grosscm1_14days         DECIMAL(30,6),
        grosscm1_30days         DECIMAL(30,6),
        grosscm1_ytd             DECIMAL(30,6),
        grosscm1_total     DECIMAL(30,6),
        PRIMARY KEY (id)

  )