SELECT 
    sku,
    barcode,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(sku_name), '\r', ''),'\n',''),'\t',''),'\"', '') as sku_name,
    brand,
    department,
    category1,
    category2,
    vendor_code,
    supplier,
    first_grn_date,
    first_Order_Date,
    Last_Order_Date,
    soh,
    Open_PO_Qty,
    CRS_Available_Qty,
    First_Sale_in_60Days,
    days_sold_60days,
    sold_qty_07days,
    sold_qty_14days,
    Sold_QTY_30Days,
    Sold_QTY_60Days,
    Sold_QTY_90Days,
    Sold_QTY_180Days,
    lifetime_sold_qty,
    Gift_QTY,
    StockCover_60days_sale_Basis,
    StockCover_60days_Including_OpenPO,
    Stock_Cover_Flag,
    Stock_Cover_Flag_Including_OpenPO,
    Inventory_Category,
    Firt_GRN_to_First_Sale_Days,
    SKU_Live_Status,
    Events_Count_30days,
    Events_Count_60days,
    Events_Count_90days
FROM aoi.inventory_health
where \$CONDITIONS
