Select * from (SELECT 
 ROW_NUMBER() OVER(ORDER BY [Entry Type],[Web Order ID],[Item ID]) as rownum,
 [timestamp] as ts,
 [Entry Type] as entry_type,
 [Web Order ID] as web_order_id,
 [Item ID] as item_id,
 [Celebrity ID] as celebrity_id,
 CAST(convert(varchar, [Order Date], 112) as INT) as order_date,
 [Order Amount] as order_amount,
 [Commission Amount] as commission_amount,
 Shipped as shipped,
 [Shipped Date] as shipped_date,
 Delivered as delivered,
 [Delivered Date] as delivered_date,
 [Document No_] as document_no,
 [Document Created] as document_created,
 [Posted Document No_] as posted_document_no,
 [Posted Document Date] as posted_document_date,
 Country as country,
 [Currency Code] as currency_code,
 [Currency Factor] as currency_factor,
 [Item No_] as item_no,
 [Commission Calculated] as commission_calculated,
 [Type] as type,
 [OFS Commission Amount] as OFS_commission_amount,
 [NAV Celebrity ID] as nav_celebrity_id,
 [Is Difference] as is_difference,
 [Eligible For Commission] as eligible_for_commission,
 [Eligible Commission Date] as eligible_commission_date,
 [Commission Amount LCY] as commission_amount_lcy,
 [Commission Due Date] as commission_due_date,
 [Order Amount LCY] as order_amount_lcy,
 Quantity as quantity,
 [ERP Com_ Amount LCY] as erp_com_amount_lcy,
 [Order Type] as order_type,
 [Order Category] as order_category
FROM Boutiqaat_Live.dbo.[Boutiqaat Kuwait\$Celebrity Commission]
WHERE convert(varchar, [Order Date], 112) = '{{DATE}}') as sub
WHERE \$CONDITIONS