BEGIN;
DROP TABLE IF EXISTS tmp_sales_invoice_line;
CREATE TEMP TABLE tmp_sales_invoice_line(
	ts VARCHAR(40),
	document_no VARCHAR(40),
	line_no INTEGER,
	sell_to_customer_no VARCHAR(40),
	type INTEGER,
	no VARCHAR(40),
	location_code VARCHAR(20),
	posting_group VARCHAR(20),
	shipment_date timestamp,
	description VARCHAR(400),
	description_2 VARCHAR(400),
	unit_of_measure VARCHAR(20),
	quantity decimal(38,20),
	unit_price decimal(38,20),
	unit_cost_lcy decimal(38,20),
	vat decimal(38,20),
	line_discount decimal(38,20),
	line_discount_amount decimal(38,20),
	amount decimal(38,20),
	amount_including_vat decimal(38,20),
	allow_invoice_disc SMALLINT,
	gross_weight decimal(38,20),
	net_weight decimal(38,20),
	units_per_parcel decimal(38,20),
	unit_volume decimal(38,20),
	appl_to_item_entry INTEGER,
	shortcut_dimension_1_code VARCHAR(40),
	shortcut_dimension_2_code VARCHAR(40),
	customer_price_group VARCHAR(20),
	job_no VARCHAR(40),
	work_type_code VARCHAR(20),
	shipment_no VARCHAR(40),
	shipment_line_no INTEGER,
	bill_to_customer_no VARCHAR(40),
	inv_discount_amount decimal(38,20),
	drop_shipment SMALLINT,
	gen_bus_posting_group VARCHAR(20),
	gen_prod_posting_group VARCHAR(20),
	vat_calculation_type INTEGER,
	transaction_type VARCHAR(20),
	transport_method VARCHAR(20),
	attached_to_line_no INTEGER,
	exit_point VARCHAR(20),
	area VARCHAR(20),
	transaction_specification VARCHAR(20),
	tax_category VARCHAR(20),
	tax_area_code VARCHAR(40),
	tax_liable SMALLINT,
	tax_group_code VARCHAR(20),
	vat_clause_code VARCHAR(20),
	vat_bus_posting_group VARCHAR(20),
	vat_prod_posting_group VARCHAR(20),
	blanket_order_no VARCHAR(40),
	blanket_order_line_no INTEGER,
	vat_base_amount decimal(38,20),
	unit_cost decimal(38,20),
	system_created_entry SMALLINT,
	line_amount decimal(38,20),
	vat_difference decimal(38,20),
	vat_identifier VARCHAR(20),
	ic_partner_ref_type INTEGER,
	ic_partner_reference VARCHAR(40),
	prepayment_line SMALLINT,
	ic_partner_code VARCHAR(40),
	posting_date timestamp,
	dimension_set_id INTEGER,
	job_task_no VARCHAR(40),
	job_contract_entry_no INTEGER,
	deferral_code VARCHAR(20),
	variant_code VARCHAR(20),
	bin_code VARCHAR(40),
	qty_per_unit_of_measure decimal(38,20),
	unit_of_measure_code VARCHAR(20),
	quantity_base decimal(38,20),
	fa_posting_date timestamp,
	depreciation_book_code VARCHAR(20),
	depr_until_fa_posting_date SMALLINT,
	duplicate_in_depreciation_book VARCHAR(20),
	use_duplication_list SMALLINT,
	responsibility_center VARCHAR(20),
	cross_reference_no VARCHAR(40),
	unit_of_measure_cross_ref VARCHAR(20),
	cross_reference_type INTEGER,
	cross_reference_type_no VARCHAR(60),
	item_category_code VARCHAR(40),
	nonstock SMALLINT,
	purchasing_code VARCHAR(20),
	product_group_code VARCHAR(40),
	appl_from_item_entry INTEGER,
	return_reason_code VARCHAR(20),
	allow_line_disc SMALLINT,
	customer_disc_group VARCHAR(40),
	sales_order_no VARCHAR(40),
	box_id VARCHAR(40),
	item_id INTEGER,
	docket_no VARCHAR(40),
	dispatch_location VARCHAR(20),
	lot_no VARCHAR(40),
	docket_date timestamp,
	campaign_id VARCHAR(20)
);

copy tmp_sales_invoice_line from '{{S3PATH}}'
iam_role 'arn:aws:iam::652586300051:role/Redshift-athena-S3-readonly'
delimiter '\t'
region 'eu-west-1' 
acceptinvchars
CSV 
GZIP;


DROP TABLE IF EXISTS NAV.sales_invoice_line;
CREATE TABLE NAV.sales_invoice_line (
    ts VARCHAR(40) NOT NULL ENCODE LZO,
	document_no VARCHAR(40) NOT NULL ENCODE LZO,
	line_no INTEGER NOT NULL ENCODE DELTA,
	sell_to_customer_no VARCHAR(40) NOT NULL ENCODE LZO,
	type INTEGER NOT NULL ENCODE DELTA,
	no VARCHAR(40) NOT NULL ENCODE LZO,
	location_code VARCHAR(20) NOT NULL ENCODE LZO,
	posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	shipment_date timestamp NOT NULL ENCODE LZO,
	description VARCHAR(400) NOT NULL ENCODE LZO,
	description_2 VARCHAR(400) NOT NULL ENCODE LZO,
	unit_of_measure VARCHAR(20) NOT NULL ENCODE LZO,
	quantity decimal(38,20) NOT NULL ENCODE LZO,
	unit_price decimal(38,20) NOT NULL ENCODE LZO,
	unit_cost_lcy decimal(38,20) NOT NULL ENCODE LZO,
	vat decimal(38,20) NOT NULL ENCODE LZO,
	line_discount decimal(38,20) NOT NULL ENCODE LZO,
	line_discount_amount decimal(38,20) NOT NULL ENCODE LZO,
	amount decimal(38,20) NOT NULL ENCODE LZO,
	amount_including_vat decimal(38,20) NOT NULL ENCODE LZO,
	allow_invoice_disc SMALLINT NOT NULL ENCODE DELTA,
	gross_weight decimal(38,20) NOT NULL ENCODE LZO,
	net_weight decimal(38,20) NOT NULL ENCODE LZO,
	units_per_parcel decimal(38,20) NOT NULL ENCODE LZO,
	unit_volume decimal(38,20) NOT NULL ENCODE LZO,
	appl_to_item_entry INTEGER NOT NULL ENCODE DELTA,
	shortcut_dimension_1_code VARCHAR(40) NOT NULL ENCODE LZO,
	shortcut_dimension_2_code VARCHAR(40) NOT NULL ENCODE LZO,
	customer_price_group VARCHAR(20) NOT NULL ENCODE LZO,
	job_no VARCHAR(40) NOT NULL ENCODE LZO,
	work_type_code VARCHAR(20) NOT NULL ENCODE LZO,
	shipment_no VARCHAR(40) NOT NULL ENCODE LZO,
	shipment_line_no INTEGER NOT NULL ENCODE DELTA,
	bill_to_customer_no VARCHAR(40) NOT NULL ENCODE LZO,
	inv_discount_amount decimal(38,20) NOT NULL ENCODE LZO,
	drop_shipment SMALLINT NOT NULL ENCODE DELTA,
	gen_bus_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	gen_prod_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	vat_calculation_type INTEGER NOT NULL ENCODE DELTA,
	transaction_type VARCHAR(20) NOT NULL ENCODE LZO,
	transport_method VARCHAR(20) NOT NULL ENCODE LZO,
	attached_to_line_no INTEGER NOT NULL ENCODE DELTA,
	exit_point VARCHAR(20) NOT NULL ENCODE LZO,
	area VARCHAR(20) NOT NULL ENCODE LZO,
	transaction_specification VARCHAR(20) NOT NULL ENCODE LZO,
	tax_category VARCHAR(20) NOT NULL ENCODE LZO,
	tax_area_code VARCHAR(40) NOT NULL ENCODE LZO,
	tax_liable SMALLINT NOT NULL ENCODE DELTA,
	tax_group_code VARCHAR(20) NOT NULL ENCODE LZO,
	vat_clause_code VARCHAR(20) NOT NULL ENCODE LZO,
	vat_bus_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	vat_prod_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	blanket_order_no VARCHAR(40) NOT NULL ENCODE LZO,
	blanket_order_line_no INTEGER NOT NULL ENCODE DELTA,
	vat_base_amount decimal(38,20) NOT NULL ENCODE LZO,
	unit_cost decimal(38,20) NOT NULL ENCODE LZO,
	system_created_entry SMALLINT NOT NULL ENCODE DELTA,
	line_amount decimal(38,20) NOT NULL ENCODE LZO,
	vat_difference decimal(38,20) NOT NULL ENCODE LZO,
	vat_identifier VARCHAR(20) NOT NULL ENCODE LZO,
	ic_partner_ref_type INTEGER NOT NULL ENCODE DELTA,
	ic_partner_reference VARCHAR(40) NOT NULL ENCODE LZO,
	prepayment_line SMALLINT NOT NULL ENCODE DELTA,
	ic_partner_code VARCHAR(40) NOT NULL ENCODE LZO,
	posting_date timestamp NOT NULL ENCODE LZO,
	dimension_set_id INTEGER NOT NULL ENCODE DELTA,
	job_task_no VARCHAR(40) NOT NULL ENCODE LZO,
	job_contract_entry_no INTEGER NOT NULL ENCODE DELTA,
	deferral_code VARCHAR(20) NOT NULL ENCODE LZO,
	variant_code VARCHAR(20) NOT NULL ENCODE LZO,
	bin_code VARCHAR(40) NOT NULL ENCODE LZO,
	qty_per_unit_of_measure decimal(38,20) NOT NULL ENCODE LZO,
	unit_of_measure_code VARCHAR(20) NOT NULL ENCODE LZO,
	quantity_base decimal(38,20) NOT NULL ENCODE LZO,
	fa_posting_date timestamp NOT NULL ENCODE LZO,
	depreciation_book_code VARCHAR(20) NOT NULL ENCODE LZO,
	depr_until_fa_posting_date SMALLINT NOT NULL ENCODE DELTA,
	duplicate_in_depreciation_book VARCHAR(20) NOT NULL ENCODE LZO,
	use_duplication_list SMALLINT NOT NULL ENCODE DELTA,
	responsibility_center VARCHAR(20) NOT NULL ENCODE LZO,
	cross_reference_no VARCHAR(40) NOT NULL ENCODE LZO,
	unit_of_measure_cross_ref VARCHAR(20) NOT NULL ENCODE LZO,
	cross_reference_type INTEGER NOT NULL ENCODE DELTA,
	cross_reference_type_no VARCHAR(60) NOT NULL ENCODE LZO,
	item_category_code VARCHAR(40) NOT NULL ENCODE LZO,
	nonstock SMALLINT NOT NULL ENCODE DELTA,
	purchasing_code VARCHAR(20) NOT NULL ENCODE LZO,
	product_group_code VARCHAR(40) NOT NULL ENCODE LZO,
	appl_from_item_entry INTEGER NOT NULL ENCODE DELTA,
	return_reason_code VARCHAR(20) NOT NULL ENCODE LZO,
	allow_line_disc SMALLINT NOT NULL ENCODE DELTA,
	customer_disc_group VARCHAR(40) NOT NULL ENCODE LZO,
	sales_order_no VARCHAR(40) NOT NULL ENCODE LZO,
	box_id VARCHAR(40) NOT NULL ENCODE LZO,
	item_id INTEGER NOT NULL ENCODE DELTA,
	docket_no VARCHAR(40) NOT NULL ENCODE LZO,
	dispatch_location VARCHAR(20) NOT NULL ENCODE LZO,
	lot_no VARCHAR(40) NOT NULL ENCODE LZO,
	docket_date timestamp NOT NULL ENCODE LZO,
	campaign_id VARCHAR(20) NOT NULL ENCODE LZO
);


INSERT INTO NAV.sales_invoice_line 
SELECT ts, document_no, line_no, sell_to_customer_no, type, no, location_code, posting_group, shipment_date, description, description_2, unit_of_measure, quantity, unit_price, unit_cost_lcy, vat, line_discount, line_discount_amount, amount, amount_including_vat, allow_invoice_disc, gross_weight, net_weight, units_per_parcel, unit_volume, appl_to_item_entry, shortcut_dimension_1_code, shortcut_dimension_2_code, customer_price_group, job_no, work_type_code, shipment_no, shipment_line_no, bill_to_customer_no, inv_discount_amount, drop_shipment, gen_bus_posting_group, gen_prod_posting_group, vat_calculation_type, transaction_type, transport_method, attached_to_line_no, exit_point, area, transaction_specification, tax_category, tax_area_code, tax_liable, tax_group_code, vat_clause_code, vat_bus_posting_group, vat_prod_posting_group, blanket_order_no, blanket_order_line_no, vat_base_amount, unit_cost, system_created_entry, line_amount, vat_difference, vat_identifier, ic_partner_ref_type, ic_partner_reference, prepayment_line, ic_partner_code, posting_date, dimension_set_id, job_task_no, job_contract_entry_no, deferral_code, variant_code, bin_code, qty_per_unit_of_measure, unit_of_measure_code, quantity_base, fa_posting_date, depreciation_book_code, depr_until_fa_posting_date, duplicate_in_depreciation_book, use_duplication_list, responsibility_center, cross_reference_no, unit_of_measure_cross_ref, cross_reference_type, cross_reference_type_no, item_category_code, nonstock, purchasing_code, product_group_code, appl_from_item_entry, return_reason_code, allow_line_disc, customer_disc_group, sales_order_no, box_id, item_id, docket_no, dispatch_location, lot_no, docket_date, campaign_id
FROM tmp_sales_invoice_line;
COMMIT;