SELECT
    id,
    event_id,
    events_header_id,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(user_name), '\r', ''),'\n',''),'\t',''),'\"', '') as user_name,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(celebrity_name), '\r', ''),'\n',''),'\t',''),'\"', '') as celebrity_name,
    celebrity_id,
    generic,
    event_portal,
    event_type,
    event_class,
    bq_post,
    total_post,
    event_date,
    TIMESTAMP(CONCAT(event_date, ' ', event_time)) as event_time,
    created_at,
    updated_at,
    event_hours,
    event_minutes,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(remark), '\r', ''),'\n',''),'\t',''),'\"', '') as remark,
    labelid,
    productid,
    category1,
    category2,
    category3,
    category4,
    brand,
    purchase_type,
    account_manager,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(sku_name), '\r', ''),'\n',''),'\t',''),'\"', '') as sku_name,
    sku_code,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(sku_code_name), '\r', ''),'\n',''),'\t',''),'\"', '') as sku_code_name,
    alloc_bq_post
FROM aoi.events_report
WHERE \$CONDITIONS