SELECT
    [timestamp] as ts,
    Code as code,
    Name as name,
    [Default Bin Code] as default_bin_code,
    [Name 2] as name_2,
    Address as address,
    [Address 2] as address_2,
    City as city,
    [Phone No_] as phone_no,
    [Phone No_ 2] as phone_no_2,
    [Telex No_] as telex_no,
    [Fax No_] as fax_no,
    Contact as contact,
    [Post Code] as post_code,
    County as county,
    [E-Mail] as e_mail,
    [Home Page] as home_page,
    [Country_Region Code] as country_region_code,
    [Use As In-Transit] as use_as_in_transit,
    [Require Put-away] as require_put_away,
    [Require Pick] as require_pick,
    [Cross-Dock Due Date Calc_] as cross_dock_due_date_calc,
    [Use Cross-Docking] as use_cross_docking,
    [Require Receive] as require_receive,
    [Require Shipment] as require_shipment,
    [Bin Mandatory] as bin_mandatory,
    [Directed Put-away and Pick] as directed_put_away_and_pick,
    [Default Bin Selection] as default_bin_selection,
    [Outbound Whse_ Handling Time] as outbound_whse_handling_time,
    [Inbound Whse_ Handling Time] as inbound_whse_handling_time,
    [Put-away Template Code] as put_away_template_code,
    [Use Put-away Worksheet] as use_put_away_worksheet,
    [Pick According to FEFO] as pick_according_to_fefo,
    [Allow Breakbulk] as allow_breakbulk,
    [Bin Capacity Policy] as bin_capacity_policy,
    [Open Shop Floor Bin Code] as open_shop_floor_bin_code,
    [To-Production Bin Code] as to_production_bin_code,
    [From-Production Bin Code] as from_production_bin_code,
    [Adjustment Bin Code] as adjustment_bin_code,
    [Always Create Put-away Line] as always_create_put_away_line,
    [Always Create Pick Line] as always_create_pick_line,
    [Special Equipment] as special_equipment,
    [Receipt Bin Code] as receipt_bin_code,
    [Shipment Bin Code] as shipment_bin_code,
    [Cross-Dock Bin Code] as cross_dock_bin_code,
    [To-Assembly Bin Code] as to_assembly_bin_code,
    [From-Assembly Bin Code] as from_assembly_bin_code,
    [Asm_-to-Order Shpt_ Bin Code] as asm_to_order_shpt_bin_code,
    [Base Calendar Code] as base_calendar_code,
    [Use ADCS] as use_adcs,
    [Allowed Pick Lines] as allowed_pick_lines,
    [Allowed Put Away Line] as allowed_put_away_line,
    [PNA Count] as pna_count,
    [Pass Bin] as pass_bin,
    [Fail Bin] as fail_bin,
    [Excess Bin] as excess_bin,
    [Put Away Bin Suggetion WMS] as put_away_bin_suggetion_wms,
    [Pick Bin Suggetion WMS] as pick_bin_suggetion_wms,
    [Stock Update] as stock_update,
    [Assembly RM Tolerance] as assembly_rm_tolerance,
    [Suggest Serial No] as suggest_serial_no,
    [Fail Bin for Putaway] as fail_bin_for_putaway,
    Priority as priority,
    [Lot No_] as lot_no,
    [Default Bin] as default_bin,
    [Staging Bin] as staging_bin,
    [Minimum Expiry Period] as minimum_expiry_period,
    [Zone Code] as zone_code,
    [Bin Type Code] as bin_type_code,
    [Return Pass Bin] as return_pass_bin,
    [Return Fail Bin] as return_fail_bin,
    [Return Refurbish Bin] as return_refurbish_bin
FROM Boutiqaat_Live.dbo.[Boutiqaat Kuwait\$Location]
WHERE \$CONDITIONS
