SELECT 
    Id as id, 
    OrderJSONId as order_json_id, 
    WebOrderNo as web_order_no, 
    CustomerId as customer_id, 
    PaymentMethodCode as payment_method_code, 
    PaymentGateway as payment_gateway, 
    OrderDateTime as order_datetime, 
    OrderType as order_type, 
    Frequency as frequency, 
    Priority as priority, 
    IsExchange as is_exchange, 
    IsGiftWrap as is_gift_wrap, 
    Country as country, 
    ReadyForArchive as ready_for_archive, 
    InsertedOn as inserted_on, 
    InsertedBy as inserted_by, 
    UpdatedOn as updated_on, 
    UpdatedBy as updated_by, 
    OrderCategory as order_category, 
    Confirm as confirm, 
    ReferenceOrderNo as reference_order_no, 
    AppOrderNo as app_order_no, 
    OrderSource as order_source, 
    Company as company, 
    ErrorMessage as error_message, 
    IsSync as is_sync, 
    RetryCount as retry_count
FROM OFS.InboundSalesHeader
WHERE \$CONDITIONS