BEGIN;
DROP TABLE IF EXISTS tmp_sales_order_item;
CREATE TEMP TABLE tmp_sales_order_item(
    item_id INTEGER,
    order_id INTEGER,
    parent_item_id INTEGER,
    quote_item_id INTEGER,
    store_id SMALLINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    product_id INTEGER,
    product_type VARCHAR(255),
    product_options VARCHAR(max),
    weight DECIMAL(12,4),
    is_virtual SMALLINT,
    sku VARCHAR(255),
    name VARCHAR(1000),
    description TEXT,
    applied_rule_ids TEXT,
    additional_data TEXT,
    is_qty_DECIMAL SMALLINT,
    no_discount SMALLINT,
    qty_backordered DECIMAL(12,4),
    qty_canceled DECIMAL(12,4),
    qty_invoiced DECIMAL(12,4),
    qty_ordered DECIMAL(12,4),
    qty_refunded DECIMAL(12,4),
    qty_shipped DECIMAL(12,4),
    base_cost DECIMAL(12,4),
    price DECIMAL(12,4),
    base_price DECIMAL(12,4),
    original_price DECIMAL(12,4),
    base_original_price DECIMAL(12,4),
    tax_percent DECIMAL(12,4),
    tax_amount DECIMAL(20,4),
    base_tax_amount DECIMAL(20,4),
    tax_invoiced DECIMAL(20,4),
    base_tax_invoiced DECIMAL(20,4),
    discount_percent DECIMAL(12,4),
    discount_amount DECIMAL(20,4),
    base_discount_amount DECIMAL(20,4),
    discount_invoiced DECIMAL(20,4),
    base_discount_invoiced DECIMAL(20,4),
    amount_refunded DECIMAL(20,4),
    base_amount_refunded DECIMAL(20,4),
    row_total DECIMAL(20,4),
    base_row_total DECIMAL(20,4),
    row_invoiced DECIMAL(20,4),
    base_row_invoiced DECIMAL(20,4),
    row_weight DECIMAL(12,4),
    base_tax_before_discount DECIMAL(20,4),
    tax_before_discount DECIMAL(20,4),
    ext_order_item_id VARCHAR(255),
    locked_do_invoice SMALLINT,
    locked_do_ship SMALLINT,
    price_incl_tax DECIMAL(20,4),
    base_price_incl_tax DECIMAL(20,4),
    row_total_incl_tax DECIMAL(20,4),
    base_row_total_incl_tax DECIMAL(20,4),
    discount_tax_compensation_amount DECIMAL(20,4),
    base_discount_tax_compensation_amount DECIMAL(20,4),
    discount_tax_compensation_invoiced DECIMAL(20,4),
    base_discount_tax_compensation_invoiced DECIMAL(20,4),
    discount_tax_compensation_refunded DECIMAL(20,4),
    base_discount_tax_compensation_refunded DECIMAL(20,4),
    tax_canceled DECIMAL(12,4),
    discount_tax_compensation_canceled DECIMAL(20,4),
    tax_refunded DECIMAL(20,4),
    base_tax_refunded DECIMAL(20,4),
    discount_refunded DECIMAL(20,4),
    base_discount_refunded DECIMAL(20,4),
    qty_returned DECIMAL(12,4),
    free_shipping SMALLINT,
    gift_message_id INTEGER,
    gift_message_available INTEGER,
    weee_tax_applied TEXT,
    weee_tax_applied_amount DECIMAL(12,4),
    weee_tax_applied_row_amount DECIMAL(12,4),
    weee_tax_disposition DECIMAL(12,4),
    weee_tax_row_disposition DECIMAL(12,4),
    base_weee_tax_applied_amount DECIMAL(12,4),
    base_weee_tax_applied_row_amnt DECIMAL(12,4),
    base_weee_tax_disposition DECIMAL(12,4),
    base_weee_tax_row_disposition DECIMAL(12,4),
    gw_id INTEGER,
    gw_base_price DECIMAL(12,4),
    gw_price DECIMAL(12,4),
    gw_base_tax_amount DECIMAL(12,4),
    gw_tax_amount DECIMAL(12,4),
    gw_base_price_invoiced DECIMAL(12,4),
    gw_price_invoiced DECIMAL(12,4),
    gw_base_tax_amount_invoiced DECIMAL(12,4),
    gw_tax_amount_invoiced DECIMAL(12,4),
    gw_base_price_refunded DECIMAL(12,4),
    gw_price_refunded DECIMAL(12,4),
    gw_base_tax_amount_refunded DECIMAL(12,4),
    gw_tax_amount_refunded DECIMAL(12,4),
    event_id INTEGER,
    giftregistry_item_id INTEGER,
    category_id INTEGER,
    commision_percent DECIMAL(12,4),
    commision_amount DECIMAL(12,4),
    base_commision_amount DECIMAL(12,4),
    celebrity_ad_number VARCHAR(100),
    special_name VARCHAR(255),
    celebrity_special_price DECIMAL(12,4),
    celebrity_ad_date TIMESTAMP,
    video_id VARCHAR(255)
);

copy tmp_sales_order_item from '{{S3PATH}}'
iam_role 'arn:aws:iam::652586300051:role/Redshift-athena-S3-readonly'
delimiter '\t'
region 'eu-west-1' 
acceptinvchars
CSV 
GZIP 
emptyasnull
blanksasnull
NULL AS 'null';

DROP TABLE IF EXISTS magento.sales_order_item;
CREATE TABLE magento.sales_order_item (
    item_id INTEGER NOT NULL ENCODE ZSTD DISTKEY SORTKEY PRIMARY KEY,
    order_id INTEGER NOT NULL ENCODE ZSTD,
    parent_item_id INTEGER NULL ENCODE ZSTD,
    quote_item_id INTEGER NULL ENCODE ZSTD,
    store_id SMALLINT NULL ENCODE ZSTD,
    created_at TIMESTAMP NOT NULL ENCODE ZSTD,
    updated_at TIMESTAMP NOT NULL ENCODE ZSTD,
    product_id INTEGER NULL ENCODE ZSTD,
    product_type VARCHAR(255) NULL ENCODE ZSTD,
    product_options VARCHAR(max) NULL ENCODE ZSTD,
    weight DECIMAL(12,4) NULL ENCODE ZSTD,
    is_virtual SMALLINT NULL ENCODE ZSTD,
    sku VARCHAR(255) NULL ENCODE ZSTD,
    name VARCHAR(1000) NULL ENCODE ZSTD,
    description TEXT NULL ENCODE ZSTD,
    applied_rule_ids TEXT NULL ENCODE ZSTD,
    additional_data TEXT NULL ENCODE ZSTD,
    is_qty_DECIMAL SMALLINT NULL ENCODE ZSTD,
    no_discount SMALLINT NOT NULL ENCODE ZSTD,
    qty_backordered DECIMAL(12,4) NULL ENCODE ZSTD,
    qty_canceled DECIMAL(12,4) NOT NULL ENCODE ZSTD,
    qty_invoiced DECIMAL(12,4) NOT NULL ENCODE ZSTD,
    qty_ordered DECIMAL(12,4) NOT NULL ENCODE ZSTD,
    qty_refunded DECIMAL(12,4) NOT NULL ENCODE ZSTD,
    qty_shipped DECIMAL(12,4) NOT NULL ENCODE ZSTD,
    base_cost DECIMAL(12,4) NULL ENCODE ZSTD,
    price DECIMAL(12,4) NOT NULL ENCODE ZSTD,
    base_price DECIMAL(12,4) NOT NULL ENCODE ZSTD,
    original_price DECIMAL(12,4) NULL ENCODE ZSTD,
    base_original_price DECIMAL(12,4) NULL ENCODE ZSTD,
    tax_percent DECIMAL(12,4) NULL ENCODE ZSTD,
    tax_amount DECIMAL(20,4) NULL ENCODE ZSTD,
    base_tax_amount DECIMAL(20,4) NULL ENCODE ZSTD,
    tax_invoiced DECIMAL(20,4) NULL ENCODE ZSTD,
    base_tax_invoiced DECIMAL(20,4) NULL ENCODE ZSTD,
    discount_percent DECIMAL(12,4) NULL ENCODE ZSTD,
    discount_amount DECIMAL(20,4) NULL ENCODE ZSTD,
    base_discount_amount DECIMAL(20,4) NULL ENCODE ZSTD,
    discount_invoiced DECIMAL(20,4) NULL ENCODE ZSTD,
    base_discount_invoiced DECIMAL(20,4) NULL ENCODE ZSTD,
    amount_refunded DECIMAL(20,4) NULL ENCODE ZSTD,
    base_amount_refunded DECIMAL(20,4) NULL ENCODE ZSTD,
    row_total DECIMAL(20,4) NOT NULL ENCODE ZSTD,
    base_row_total DECIMAL(20,4) NOT NULL ENCODE ZSTD,
    row_invoiced DECIMAL(20,4) NOT NULL ENCODE ZSTD,
    base_row_invoiced DECIMAL(20,4) NOT NULL ENCODE ZSTD,
    row_weight DECIMAL(12,4) NULL ENCODE ZSTD,
    base_tax_before_discount DECIMAL(20,4) NULL ENCODE ZSTD,
    tax_before_discount DECIMAL(20,4) NULL ENCODE ZSTD,
    ext_order_item_id VARCHAR(255) NULL ENCODE ZSTD,
    locked_do_invoice SMALLINT NULL ENCODE ZSTD,
    locked_do_ship SMALLINT NULL ENCODE ZSTD,
    price_incl_tax DECIMAL(20,4) NULL ENCODE ZSTD,
    base_price_incl_tax DECIMAL(20,4) NULL ENCODE ZSTD,
    row_total_incl_tax DECIMAL(20,4) NULL ENCODE ZSTD,
    base_row_total_incl_tax DECIMAL(20,4) NULL ENCODE ZSTD,
    discount_tax_compensation_amount DECIMAL(20,4) NULL ENCODE ZSTD,
    base_discount_tax_compensation_amount DECIMAL(20,4) NULL ENCODE ZSTD,
    discount_tax_compensation_invoiced DECIMAL(20,4) NULL ENCODE ZSTD,
    base_discount_tax_compensation_invoiced DECIMAL(20,4) NULL ENCODE ZSTD,
    discount_tax_compensation_refunded DECIMAL(20,4) NULL ENCODE ZSTD,
    base_discount_tax_compensation_refunded DECIMAL(20,4) NULL ENCODE ZSTD,
    tax_canceled DECIMAL(12,4) NULL ENCODE ZSTD,
    discount_tax_compensation_canceled DECIMAL(20,4) NULL ENCODE ZSTD,
    tax_refunded DECIMAL(20,4) NULL ENCODE ZSTD,
    base_tax_refunded DECIMAL(20,4) NULL ENCODE ZSTD,
    discount_refunded DECIMAL(20,4) NULL ENCODE ZSTD,
    base_discount_refunded DECIMAL(20,4) NULL ENCODE ZSTD,
    qty_returned DECIMAL(12,4) NOT NULL ENCODE ZSTD,
    free_shipping SMALLINT NOT NULL ENCODE ZSTD,
    gift_message_id INTEGER NULL ENCODE ZSTD,
    gift_message_available INTEGER NULL ENCODE ZSTD,
    weee_tax_applied TEXT NULL ENCODE ZSTD,
    weee_tax_applied_amount DECIMAL(12,4) NULL ENCODE ZSTD,
    weee_tax_applied_row_amount DECIMAL(12,4) NULL ENCODE ZSTD,
    weee_tax_disposition DECIMAL(12,4) NULL ENCODE ZSTD,
    weee_tax_row_disposition DECIMAL(12,4) NULL ENCODE ZSTD,
    base_weee_tax_applied_amount DECIMAL(12,4) NULL ENCODE ZSTD,
    base_weee_tax_applied_row_amnt DECIMAL(12,4) NULL ENCODE ZSTD,
    base_weee_tax_disposition DECIMAL(12,4) NULL ENCODE ZSTD,
    base_weee_tax_row_disposition DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_id INTEGER NULL ENCODE ZSTD,
    gw_base_price DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_price DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_base_tax_amount DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_tax_amount DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_base_price_invoiced DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_price_invoiced DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_base_tax_amount_invoiced DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_tax_amount_invoiced DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_base_price_refunded DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_price_refunded DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_base_tax_amount_refunded DECIMAL(12,4) NULL ENCODE ZSTD,
    gw_tax_amount_refunded DECIMAL(12,4) NULL ENCODE ZSTD,
    event_id INTEGER NULL ENCODE ZSTD,
    giftregistry_item_id INTEGER NULL ENCODE ZSTD,
    category_id INTEGER NULL ENCODE ZSTD,
    commision_percent DECIMAL(12,4) NULL ENCODE ZSTD,
    commision_amount DECIMAL(12,4) NULL ENCODE ZSTD,
    base_commision_amount DECIMAL(12,4) NULL ENCODE ZSTD,
    celebrity_ad_number VARCHAR(100) NULL ENCODE ZSTD,
    special_name VARCHAR(255) NULL ENCODE ZSTD,
    celebrity_special_price DECIMAL(12,4) NOT NULL ENCODE ZSTD,
    celebrity_ad_date TIMESTAMP NULL ENCODE ZSTD,
    video_id VARCHAR(255) NULL ENCODE ZSTD
);

INSERT INTO magento.sales_order_item
SELECT item_id, order_id, parent_item_id, quote_item_id, store_id, created_at, updated_at, product_id, product_type, product_options, weight, is_virtual, sku, name, description, applied_rule_ids, additional_data, is_qty_DECIMAL, no_discount, qty_backordered, qty_canceled, qty_invoiced, qty_ordered, qty_refunded, qty_shipped, base_cost, price, base_price, original_price, base_original_price, tax_percent, tax_amount, base_tax_amount, tax_invoiced, base_tax_invoiced, discount_percent, discount_amount, base_discount_amount, discount_invoiced, base_discount_invoiced, amount_refunded, base_amount_refunded, row_total, base_row_total, row_invoiced, base_row_invoiced, row_weight, base_tax_before_discount, tax_before_discount, ext_order_item_id, locked_do_invoice, locked_do_ship, price_incl_tax, base_price_incl_tax, row_total_incl_tax, base_row_total_incl_tax, discount_tax_compensation_amount, base_discount_tax_compensation_amount, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, tax_canceled, discount_tax_compensation_canceled, tax_refunded, base_tax_refunded, discount_refunded, base_discount_refunded, qty_returned, free_shipping, gift_message_id, gift_message_available, weee_tax_applied, weee_tax_applied_amount, weee_tax_applied_row_amount, weee_tax_disposition, weee_tax_row_disposition, base_weee_tax_applied_amount, base_weee_tax_applied_row_amnt, base_weee_tax_disposition, base_weee_tax_row_disposition, gw_id, gw_base_price, gw_price, gw_base_tax_amount, gw_tax_amount, gw_base_price_invoiced, gw_price_invoiced, gw_base_tax_amount_invoiced, gw_tax_amount_invoiced, gw_base_price_refunded, gw_price_refunded, gw_base_tax_amount_refunded, gw_tax_amount_refunded, event_id, giftregistry_item_id, category_id, commision_percent, commision_amount, base_commision_amount, celebrity_ad_number, special_name, celebrity_special_price, celebrity_ad_date, video_id
FROM tmp_sales_order_item;
COMMIT;

