DROP TABLE IF EXISTS tmp_adjust;
CREATE TEMP TABLE tmp_adjust(
	app_id VARCHAR(max),
	app_name VARCHAR(max),
	app_name_dashboard VARCHAR(max),
	app_version VARCHAR(max),
	app_version_raw VARCHAR(max),
	app_version_short VARCHAR(max),
	store  VARCHAR(max),
	tracker VARCHAR(max),
	tracker_name VARCHAR(max),
	first_tracker VARCHAR(max),
	last_tracker VARCHAR(max),
	last_tracker_name VARCHAR(max),
	outdated_tracker VARCHAR(max),
	network_name VARCHAR(max),
	campaign_name VARCHAR(max),
	adgroup_name VARCHAR(max),
	creative_name VARCHAR(max),
	impression_based SMALLINT,
	is_organic SMALLINT,
	rejection_reason VARCHAR(max),
	click_referer VARCHAR(max),
	activity_kind VARCHAR(max),
	click_time BIGINT,
	click_time_hour BIGINT,
	impression_time BIGINT,
	impression_time_hour BIGINT,
	conversion_duration BIGINT,
	engagement_time BIGINT,
	engagement_time_hour BIGINT,
	installed_at BIGINT,
	installed_at_hour BIGINT,
	install_finish_time BIGINT,
	install_begin_time BIGINT,
	referral_time BIGINT,
	created_at BIGINT,
	created_at_milli BIGINT,
	created_at_hour BIGINT,
	reattributed_at BIGINT,
	reattributed_at_hour BIGINT,
	attribution_updated_at BIGINT,
	time_to_uninstall BIGINT,
	time_to_reinstall BIGINT,
	uninstalled_at BIGINT,
	reinstalled_at BIGINT,
	last_session_time BIGINT,
	connection_type VARCHAR(max),
	click_attribution_window INTEGER,
	impression_attribution_window INTEGER,
	reattribution_attribution_window INTEGER,
	inactive_user_definition INTEGER,
	fingerprint_attribution_window INTEGER,
	adid VARCHAR(max),
	idfa VARCHAR(max),
	android_id VARCHAR(max),
	android_id_md5 VARCHAR(max),
	mac_sha1 VARCHAR(max),
	mac_md5 VARCHAR(max),
	idfa_android_id VARCHAR(max),
	idfa_gps_adid VARCHAR(max),
	idfa_gps_adid_fire_adid VARCHAR(max),
	idfa_md5 VARCHAR(max),
	idfa_md5_hex VARCHAR(max),
	idfa_upper VARCHAR(max),
	idfv VARCHAR(max),
	gps_adid VARCHAR(max),
	gps_adid_md5 VARCHAR(max),
	win_udid VARCHAR(max),
	win_hwid VARCHAR(max),
	win_naid VARCHAR(max),
	win_adid VARCHAR(max),
	fire_adid VARCHAR(max),
	match_type VARCHAR(max),
	reftag VARCHAR(max),
	referrer VARCHAR(max),
	user_agent VARCHAR(max),
	mcc VARCHAR(max),
	mnc VARCHAR(max),
	ip_address VARCHAR(max),
	isp VARCHAR(max),
	region VARCHAR(max),
	country VARCHAR(max),
	country_subdivision VARCHAR(max),
	city VARCHAR(max),
	postal_code VARCHAR(max),
	language VARCHAR(max),
	device_name VARCHAR(max),
	device_type VARCHAR(max),
	os_name VARCHAR(max),
	api_level VARCHAR(max),
	sdk_version VARCHAR(max),
	os_version VARCHAR(max),
	random INTEGER,
	nonce VARCHAR(max),
	random_user_id VARCHAR(max),
	environment VARCHAR(max),
	tracking_enabled SMALLINT,
	tracking_limited SMALLINT,
	timezone VARCHAR(max),
	event VARCHAR(max),
	event_name VARCHAR(max),
	last_time_spent INTEGER,
	time_spent INTEGER,
	session_count INTEGER,
	lifetime_session_count INTEGER,
	is_reattributed SMALLINT,
	deeplink VARCHAR(max),
	partner_parameters VARCHAR(max),
	revenue_float decimal(38,20),
	revenue decimal(38,20),
	currency VARCHAR(max),
	revenue_usd decimal(38,20),
	revenue_usd_cents decimal(38,20),
	reporting_revenue decimal(38,20),
	reporting_currency VARCHAR(max),
	cost_type VARCHAR(max),
	cost_amount decimal(38,20),
	cost_currency VARCHAR(max),
	reporting_cost decimal(38,20),
	cost_id_md5 VARCHAR(max),
	push_token VARCHAR(max),
	publisher_parameters VARCHAR(max),
	label VARCHAR(max),
	gclid VARCHAR(max),
	adwords_campaign_type VARCHAR(max),
	adwords_campaign_name VARCHAR(max),
	adwords_campaign_id BIGINT,
	adwords_adgroup_id BIGINT,
	adwords_creative_id BIGINT,
	adwords_network_type VARCHAR(max),
	adwords_network_subtype VARCHAR(max),
	adwords_keyword VARCHAR(max),
	adwords_matchtype VARCHAR(max),
	adwords_placement VARCHAR(max),
	adwords_video_id VARCHAR(max),
	search_term VARCHAR(max),
	fb_campaign_group_name VARCHAR(max),
	fb_campaign_group_id VARCHAR(max),
	fb_campaign_name VARCHAR(max),
	fb_campaign_id VARCHAR(max),
	fb_adgroup_name VARCHAR(max),
	fb_adgroup_id VARCHAR(max),
	fb_ad_objective_name VARCHAR(max),
	fb_account_id VARCHAR(max),
	fb_platform_position VARCHAR(max),
	tweet_id VARCHAR(max),
	twitter_line_item_id VARCHAR(max),
	iad_creativeset_name VARCHAR(max),
	iad_creativeset_id VARCHAR(max),
	iad_conversion_type VARCHAR(max),
	iad_keyword_matchtype VARCHAR(max)
);

copy tmp_adjust from '{{S3PATH}}'
iam_role 'arn:aws:iam::652586300051:role/Redshift-athena-S3-readonly'
delimiter ','
region 'eu-west-1' 
CSV 
GZIP 
IGNOREHEADER 1 
emptyasnull
blanksasnull;

UNLOAD ('select  DATE(''{{DATE}}'') as ingestion_date,
	DATE(to_char(TIMESTAMP ''epoch'' + created_at *INTERVAL ''1 second'', ''YYYYMMDD'')) as  tracking_date,
 	to_char(TIMESTAMP ''epoch'' + created_at *INTERVAL ''1 second'', ''MM'') as tracking_month,
    to_char(TIMESTAMP ''epoch'' + created_at *INTERVAL ''1 second'', ''YYYY'')  as tracking_year,	
	* 
	from tmp_adjust')
TO 's3://btq-etl/adjust/parquet/'
iam_role 'arn:aws:iam::652586300051:role/redshift-s3-writeAccess'
FORMAT AS PARQUET
PARTITION BY (tracking_year, tracking_month, tracking_date, ingestion_date)
ALLOWOVERWRITE
MAXFILESIZE AS 500 MB;

DROP TABLE tmp_adjust;