SELECT
    [timestamp],
	No_,
	[No_ 2],
	REPLACE(REPLACE(REPLACE(REPLACE(Description, CHAR(13), ''), CHAR(10), ''), CHAR(9), ''),'\"', '') as Description,
	REPLACE(REPLACE(REPLACE(REPLACE([Search Description], CHAR(13), ''), CHAR(10), ''), CHAR(9), ''),'\"', '') as Search_Description,
	REPLACE(REPLACE(REPLACE(REPLACE([Description 2], CHAR(13), ''), CHAR(10), ''), CHAR(9), ''),'\"', '') as Description_2,
	[Base Unit of Measure],
	[Price Unit Conversion],
	[Type],
	[Inventory Posting Group],
	[Shelf No_],
	[Item Disc_ Group],
	[Allow Invoice Disc_],
	[Statistics Group],
	[Commission Group],
	[Unit Price],
	[Price_Profit Calculation],
	[Profit _],
	[Costing Method],
	[Unit Cost],
	[Standard Cost],
	[Last Direct Cost],
	[Indirect Cost _],
	[Cost is Adjusted],
	[Allow Online Adjustment],
	[Vendor No_],
	REPLACE(REPLACE(REPLACE(REPLACE([Vendor Item No_], CHAR(13), ''), CHAR(10), ''), CHAR(9), ''),'\"', '') as Vendor_Item_No,
	[Lead Time Calculation],
	[Reorder Point],
	[Maximum Inventory],
	[Reorder Quantity],
	[Alternative Item No_],
	[Unit List Price],
	[Duty Due _],
	[Duty Code],
	[Gross Weight],
	[Net Weight],
	[Units per Parcel],
	[Unit Volume],
	Durability,
	[Freight Type],
	[Tariff No_],
	[Duty Unit Conversion],
	[Country_Region Purchased Code],
	[Budget Quantity],
	[Budgeted Amount],
	[Budget Profit],
	Blocked,
	[Last Date Modified],
	[Last Time Modified],
	[Price Includes VAT],
	[VAT Bus_ Posting Gr_ (Price)],
	[Gen_ Prod_ Posting Group],
	[Country_Region of Origin Code],
	[Automatic Ext_ Texts],
	[No_ Series],
	[Tax Group Code],
	[VAT Prod_ Posting Group],
	Reserve,
	[Global Dimension 1 Code],
	[Global Dimension 2 Code],
	[Stockout Warning],
	[Prevent Negative Inventory],
	[Application Wksh_ User ID],
	[Assembly Policy],
	GTIN,
	[Default Deferral Template Code],
	[Low-Level Code],
	[Lot Size],
	[Serial Nos_],
	[Last Unit Cost Calc_ Date],
	[Rolled-up Material Cost],
	[Rolled-up Capacity Cost],
	[Scrap _],
	[Inventory Value Zero],
	[Discrete Order Quantity],
	[Minimum Order Quantity],
	[Maximum Order Quantity],
	[Safety Stock Quantity],
	[Order Multiple],
	[Safety Lead Time],
	[Flushing Method],
	[Replenishment System],
	[Rounding Precision],
	[Sales Unit of Measure],
	[Purch_ Unit of Measure],
	[Time Bucket],
	[Reordering Policy],
	[Include Inventory],
	[Manufacturing Policy],
	[Rescheduling Period],
	[Lot Accumulation Period],
	[Dampener Period],
	[Dampener Quantity],
	[Overflow Level],
	[Manufacturer Code],
	[Item Category Code],
	[Created From Nonstock Item],
	[Product Group Code],
	[Service Item Group],
	[Item Tracking Code],
	[Lot Nos_],
	[Expiration Calculation],
	[Warehouse Class Code],
	[Special Equipment Code],
	[Put-away Template Code],
	[Put-away Unit of Measure Code],
	[Phys Invt Counting Period Code],
	[Last Counting Period Update],
	[Use Cross-Docking],
	[Next Counting Start Date],
	[Next Counting End Date],
	[3rd Category],
	[4th Category],
	Brand,
	Color,
	[Size],
	Power,
	Thickness,
	Diameter,
	Packaging,
	[Default Zone Code(s)],
	[Default Bin Code(s)],
	Flavour,
	Gender,
	Class,
	Material,
	[EAN Code],
	REPLACE(REPLACE(REPLACE(REPLACE([Arabic Name], CHAR(13), ''), CHAR(10), ''), CHAR(9), ''),'\"', '') as Arabic_Name,
	[Created At],
	[Created By],
	[Expiry Lead Time],
	[Expiry Required],
	[Cost-Standard],
	[Cost-Labour],
	[Cost-Overhead],
	[Cost-Machine Hours],
	[Cost-Other 1],
	[Cost-Other 2],
	[Cost-Other 3],
	Status,
	[Item Type],
	[Parent Item No_],
	[Item Sub Type],
	[Attribute Value],
	[Item Contract Type],
	[Ref Doc Number],
	[Ref Doc Line No],
	[Cost Price Calculation],
	SYNC,
	[Synced DateTime],
	[Sync ID],
	REPLACE(REPLACE(REPLACE(REPLACE([Error Message], CHAR(13), ''), CHAR(10), ''), CHAR(9), ''),'\"', '') as Error_Message,
	[Retry Count],
	[Inventory Live],
	[Sync with Magento],
	Returnable,
	[Template Code],
	[Item Enabled],
	[Is Dangerous],
	[Is Fragile],
	[OFS Sync],
	[OFS Retry Count],
	REPLACE(REPLACE(REPLACE(REPLACE([OFS Error Message], CHAR(13), ''), CHAR(10), ''), CHAR(9), ''),'\"', '') as ofs_error_message,
	[OFS Sync Date Time],
	[Magento Sync Id],
	[Bin Size],
	[WMS Sync],
	[WMS Retry Count],
	[WMS Error Message],
	[Routing No_],
	[Production BOM No_],
	[Single-Level Material Cost],
	[Single-Level Capacity Cost],
	[Single-Level Subcontrd_ Cost],
	[Single-Level Cap_ Ovhd Cost],
	[Single-Level Mfg_ Ovhd Cost],
	[Overhead Rate],
	[Rolled-up Subcontracted Cost],
	[Rolled-up Mfg_ Ovhd Cost],
	[Rolled-up Cap_ Overhead Cost],
	[Order Tracking Policy],
	Critical,
	[Common Item No_],
	Department,
	[Category Manager]
FROM Boutiqaat_Live.dbo.[Boutiqaat Kuwait\$Item]
WHERE \$CONDITIONS