SELECT 
    WebOrderNo,
    ItemId,
    CouponCode,
    CampaignId,
    ProductId,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(Description), '\r', ''),'\n',''),'\t',''),'\"', '') as description,
    SKU,
    Quantity,
    BundleID,
    BundleQuantity,
    ExpectedDispatchDate,
    ItemNo,
    VendorID,
    DeliveryType,
    SpecialDeliveryDate,
    IsFragile,
    IsPrecious,
    IsSurface,
    IsCustomized,
    PickLocation,
    PackagingLocation,
    DspCode,
    IsProcessed,
    ReadyForArchive,
    InsertedOn,
    InsertedBy,
    UpdatedOn,
    UpdatedBy,
    LeafCategory,
    IsFOC,
    IsDanger,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(ArabicDescription), '\r', ''),'\n',''),'\t',''),'\"', '') as arabic_description
FROM OFS.InboundSalesLine
where DATE(InsertedOn) = DATE('{{DATE}}') AND \$CONDITIONS