BEGIN;
DROP TABLE IF EXISTS tmp_sales_order;
CREATE TEMP TABLE tmp_sales_order(
    entity_id INTEGER,
    state VARCHAR(32),
    status VARCHAR(32),
    coupon_code VARCHAR(255),
    protect_code VARCHAR(255),
    shipping_description VARCHAR(255),
    is_virtual INTEGER,
    store_id INTEGER,
    customer_id INTEGER,
    base_discount_amount DECIMAL(12,4),
    base_discount_canceled DECIMAL(12,4),
    base_discount_invoiced DECIMAL(12,4),
    base_discount_refunded DECIMAL(12,4),
    base_grand_total DECIMAL(12,4),
    base_shipping_amount DECIMAL(12,4),
    base_shipping_canceled DECIMAL(12,4),
    base_shipping_invoiced DECIMAL(12,4),
    base_shipping_refunded DECIMAL(12,4),
    base_shipping_tax_amount DECIMAL(12,4),
    base_shipping_tax_refunded DECIMAL(12,4),
    base_subtotal DECIMAL(12,4),
    base_subtotal_canceled DECIMAL(12,4),
    base_subtotal_invoiced DECIMAL(12,4),
    base_subtotal_refunded DECIMAL(12,4),
    base_tax_amount DECIMAL(12,4),
    base_tax_canceled DECIMAL(12,4),
    base_tax_invoiced DECIMAL(12,4),
    base_tax_refunded DECIMAL(12,4),
    base_to_global_rate DECIMAL(12,4),
    base_to_order_rate DECIMAL(12,4),
    base_total_canceled DECIMAL(12,4),
    base_total_invoiced DECIMAL(12,4),
    base_total_invoiced_cost DECIMAL(12,4),
    base_total_offline_refunded DECIMAL(12,4),
    base_total_online_refunded DECIMAL(12,4),
    base_total_paid DECIMAL(12,4),
    base_total_qty_ordered DECIMAL(12,4),
    base_total_refunded DECIMAL(12,4),
    discount_amount DECIMAL(12,4),
    discount_canceled DECIMAL(12,4),
    discount_invoiced DECIMAL(12,4),
    discount_refunded DECIMAL(12,4),
    grand_total DECIMAL(12,4),
    shipping_amount DECIMAL(12,4),
    shipping_canceled DECIMAL(12,4),
    shipping_invoiced DECIMAL(12,4),
    shipping_refunded DECIMAL(12,4),
    shipping_tax_amount DECIMAL(12,4),
    shipping_tax_refunded DECIMAL(12,4),
    store_to_base_rate DECIMAL(12,4),
    store_to_order_rate DECIMAL(12,4),
    subtotal DECIMAL(12,4),
    subtotal_canceled DECIMAL(12,4),
    subtotal_invoiced DECIMAL(12,4),
    subtotal_refunded DECIMAL(12,4),
    tax_amount DECIMAL(12,4),
    tax_canceled DECIMAL(12,4),
    tax_invoiced DECIMAL(12,4),
    tax_refunded DECIMAL(12,4),
    total_canceled DECIMAL(12,4),
    total_invoiced DECIMAL(12,4),
    total_offline_refunded DECIMAL(12,4),
    total_online_refunded DECIMAL(12,4),
    total_paid DECIMAL(12,4),
    total_qty_ordered DECIMAL(12,4),
    total_refunded DECIMAL(12,4),
    can_ship_partially INTEGER,
    can_ship_partially_item INTEGER,
    customer_is_guest INTEGER,
    customer_note_notify INTEGER,
    billing_address_id INTEGER,
    customer_group_id INTEGER,
    edit_increment INTEGER,
    email_sent INTEGER,
    send_email INTEGER,
    forced_shipment_with_invoice INTEGER,
    payment_auth_expiration INTEGER,
    quote_address_id INTEGER,
    quote_id INTEGER,
    shipping_address_id INTEGER,
    adjustment_negative DECIMAL(12,4),
    adjustment_positive DECIMAL(12,4),
    base_adjustment_negative DECIMAL(12,4),
    base_adjustment_positive DECIMAL(12,4),
    base_shipping_discount_amount DECIMAL(12,4),
    base_subtotal_incl_tax DECIMAL(12,4),
    base_total_due DECIMAL(12,4),
    payment_authorization_amount DECIMAL(12,4),
    shipping_discount_amount DECIMAL(12,4),
    subtotal_incl_tax DECIMAL(12,4),
    total_due DECIMAL(12,4),
    weight DECIMAL(12,4),
    customer_dob TIMESTAMP,
    increment_id VARCHAR(32),
    applied_rule_ids VARCHAR(128),
    base_currency_code VARCHAR(3),
    customer_email VARCHAR(128),
    customer_firstname VARCHAR(128),
    customer_lastname VARCHAR(128),
    customer_middlename VARCHAR(128),
    customer_prefix VARCHAR(32),
    customer_suffix VARCHAR(32),
    customer_taxvat VARCHAR(32),
    discount_description VARCHAR(255),
    ext_customer_id VARCHAR(32),
    ext_order_id VARCHAR(32),
    global_currency_code VARCHAR(3),
    hold_before_state VARCHAR(32),
    hold_before_status VARCHAR(32),
    order_currency_code VARCHAR(3),
    original_increment_id VARCHAR(32),
    relation_child_id VARCHAR(32),
    relation_child_real_id VARCHAR(32),
    relation_parent_id VARCHAR(32),
    relation_parent_real_id VARCHAR(32),
    remote_ip VARCHAR(32),
    shipping_method VARCHAR(120),
    store_currency_code VARCHAR(3),
    store_name VARCHAR(250),
    x_forwarded_for VARCHAR(32),
    customer_note TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    total_item_count INTEGER,
    customer_gender INTEGER,
    discount_tax_compensation_amount DECIMAL(12,4),
    base_discount_tax_compensation_amount DECIMAL(12,4),
    shipping_discount_tax_compensation_amount DECIMAL(12,4),
    base_shipping_discount_tax_compensation_amnt DECIMAL(12,4),
    discount_tax_compensation_invoiced DECIMAL(12,4),
    base_discount_tax_compensation_invoiced DECIMAL(12,4),
    discount_tax_compensation_refunded DECIMAL(12,4),
    base_discount_tax_compensation_refunded DECIMAL(12,4),
    shipping_incl_tax DECIMAL(12,4),
    base_shipping_incl_tax DECIMAL(12,4),
    coupon_rule_name VARCHAR(255),
    base_customer_balance_amount DECIMAL(12,4),
    customer_balance_amount DECIMAL(12,4),
    base_customer_balance_invoiced DECIMAL(12,4),
    customer_balance_invoiced DECIMAL(12,4),
    base_customer_balance_refunded DECIMAL(12,4),
    customer_balance_refunded DECIMAL(12,4),
    bs_customer_bal_total_refunded DECIMAL(12,4),
    customer_bal_total_refunded DECIMAL(12,4),
    gift_cards TEXT,
    base_gift_cards_amount DECIMAL(12,4),
    gift_cards_amount DECIMAL(12,4),
    base_gift_cards_invoiced DECIMAL(12,4),
    gift_cards_invoiced DECIMAL(12,4),
    base_gift_cards_refunded DECIMAL(12,4),
    gift_cards_refunded DECIMAL(12,4),
    gift_message_id INTEGER,
    gw_id INTEGER,
    gw_allow_gift_receipt INTEGER,
    gw_add_card INTEGER,
    gw_base_price DECIMAL(12,4),
    gw_price DECIMAL(12,4),
    gw_items_base_price DECIMAL(12,4),
    gw_items_price DECIMAL(12,4),
    gw_card_base_price DECIMAL(12,4),
    gw_card_price DECIMAL(12,4),
    gw_base_tax_amount DECIMAL(12,4),
    gw_tax_amount DECIMAL(12,4),
    gw_items_base_tax_amount DECIMAL(12,4),
    gw_items_tax_amount DECIMAL(12,4),
    gw_card_base_tax_amount DECIMAL(12,4),
    gw_card_tax_amount DECIMAL(12,4),
    gw_base_price_incl_tax DECIMAL(12,4),
    gw_price_incl_tax DECIMAL(12,4),
    gw_items_base_price_incl_tax DECIMAL(12,4),
    gw_items_price_incl_tax DECIMAL(12,4),
    gw_card_base_price_incl_tax DECIMAL(12,4),
    gw_card_price_incl_tax DECIMAL(12,4),
    gw_base_price_invoiced DECIMAL(12,4),
    gw_price_invoiced DECIMAL(12,4),
    gw_items_base_price_invoiced DECIMAL(12,4),
    gw_items_price_invoiced DECIMAL(12,4),
    gw_card_base_price_invoiced DECIMAL(12,4),
    gw_card_price_invoiced DECIMAL(12,4),
    gw_base_tax_amount_invoiced DECIMAL(12,4),
    gw_tax_amount_invoiced DECIMAL(12,4),
    gw_items_base_tax_invoiced DECIMAL(12,4),
    gw_items_tax_invoiced DECIMAL(12,4),
    gw_card_base_tax_invoiced DECIMAL(12,4),
    gw_card_tax_invoiced DECIMAL(12,4),
    gw_base_price_refunded DECIMAL(12,4),
    gw_price_refunded DECIMAL(12,4),
    gw_items_base_price_refunded DECIMAL(12,4),
    gw_items_price_refunded DECIMAL(12,4),
    gw_card_base_price_refunded DECIMAL(12,4),
    gw_card_price_refunded DECIMAL(12,4),
    gw_base_tax_amount_refunded DECIMAL(12,4),
    gw_tax_amount_refunded DECIMAL(12,4),
    gw_items_base_tax_refunded DECIMAL(12,4),
    gw_items_tax_refunded DECIMAL(12,4),
    gw_card_base_tax_refunded DECIMAL(12,4),
    gw_card_tax_refunded DECIMAL(12,4),
    paypal_ipn_customer_notified INTEGER,
    reward_points_balance INTEGER,
    base_reward_currency_amount DECIMAL(12,4),
    reward_currency_amount DECIMAL(12,4),
    base_rwrd_crrncy_amt_invoiced DECIMAL(12,4),
    rwrd_currency_amount_invoiced DECIMAL(12,4),
    base_rwrd_crrncy_amnt_refnded DECIMAL(12,4),
    rwrd_crrncy_amnt_refunded DECIMAL(12,4),
    reward_points_balance_refund INTEGER,
    reference_number VARCHAR(255),
    msp_cod_amount DECIMAL(12,4),
    base_msp_cod_amount DECIMAL(12,4),
    msp_cod_tax_amount DECIMAL(12,4),
    base_msp_cod_tax_amount DECIMAL(12,4),
    erp_update VARCHAR(255),
    erp_update_count VARCHAR(255),
    device_name VARCHAR(255),
    ebizmarts_abandonedcart_flag SMALLINT,
    ebizmarts_magemonkey_campaign_id VARCHAR(10),
    msp_base_cashondelivery DECIMAL(12,4),
    msp_cashondelivery DECIMAL(12,4),
    msp_base_cashondelivery_incl_tax DECIMAL(12,4),
    msp_cashondelivery_incl_tax DECIMAL(12,4),
    paymentid VARCHAR(255),
    tranid VARCHAR(255),
    result VARCHAR(255),
    payment_method VARCHAR(255),
    telephone VARCHAR(255),
    website_id VARCHAR(255),
    device_type VARCHAR(255),
    device_model VARCHAR(255),
    app_version VARCHAR(255),
    os_version VARCHAR(255),
    device_token_android TEXT,
    device_token_ios TEXT,
    sms_sent_status INTEGER,
    sms_customer_status INTEGER,
    new_erp_update_count VARCHAR(45),
    new_erp_update VARCHAR(45),
    telephone_no VARCHAR(255),
    custom_vat DECIMAL(12,4),
    fee DECIMAL(12,4),
    base_fee DECIMAL(12,4),
    base_custom_vat DECIMAL(12,4),
    clearance_charges DECIMAL(12,4),
    base_clearance_charges DECIMAL(12,4),
    created_time_ml TIMESTAMP,
    myfatoorah_payment VARCHAR(100),
    myfatoorah_orderid VARCHAR(100)
);

copy tmp_sales_order from '{{S3PATH}}'
iam_role 'arn:aws:iam::652586300051:role/Redshift-athena-S3-readonly'
delimiter '\t'
region 'eu-west-1' 
acceptinvchars
CSV 
GZIP 
emptyasnull
blanksasnull
NULL AS 'null';

DROP TABLE IF EXISTS magento.sales_order;
CREATE TABLE magento.sales_order (
    entity_id INTEGER NOT NULL ENCODE LZO PRIMARY KEY,
    state VARCHAR(32) NULL ENCODE LZO,
    status VARCHAR(32) NULL ENCODE LZO DISTKEY,
    coupon_code VARCHAR(255) NULL ENCODE LZO,
    protect_code VARCHAR(255) NULL ENCODE LZO,
    shipping_description VARCHAR(255) NULL ENCODE LZO,
    is_virtual INTEGER NULL ENCODE LZO,
    store_id INTEGER NULL ENCODE LZO,
    customer_id INTEGER NULL ENCODE LZO,
    base_discount_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_discount_canceled DECIMAL(12,4) NULL ENCODE LZO,
    base_discount_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    base_discount_refunded DECIMAL(12,4) NULL ENCODE LZO,
    base_grand_total DECIMAL(12,4) NULL ENCODE LZO,
    base_shipping_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_shipping_canceled DECIMAL(12,4) NULL ENCODE LZO,
    base_shipping_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    base_shipping_refunded DECIMAL(12,4) NULL ENCODE LZO,
    base_shipping_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_shipping_tax_refunded DECIMAL(12,4) NULL ENCODE LZO,
    base_subtotal DECIMAL(12,4) NULL ENCODE LZO,
    base_subtotal_canceled DECIMAL(12,4) NULL ENCODE LZO,
    base_subtotal_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    base_subtotal_refunded DECIMAL(12,4) NULL ENCODE LZO,
    base_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_tax_canceled DECIMAL(12,4) NULL ENCODE LZO,
    base_tax_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    base_tax_refunded DECIMAL(12,4) NULL ENCODE LZO,
    base_to_global_rate DECIMAL(12,4) NULL ENCODE LZO,
    base_to_order_rate DECIMAL(12,4) NULL ENCODE LZO,
    base_total_canceled DECIMAL(12,4) NULL ENCODE LZO,
    base_total_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    base_total_invoiced_cost DECIMAL(12,4) NULL ENCODE LZO,
    base_total_offline_refunded DECIMAL(12,4) NULL ENCODE LZO,
    base_total_online_refunded DECIMAL(12,4) NULL ENCODE LZO,
    base_total_paid DECIMAL(12,4) NULL ENCODE LZO,
    base_total_qty_ordered DECIMAL(12,4) NULL ENCODE LZO,
    base_total_refunded DECIMAL(12,4) NULL ENCODE LZO,
    discount_amount DECIMAL(12,4) NULL ENCODE LZO,
    discount_canceled DECIMAL(12,4) NULL ENCODE LZO,
    discount_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    discount_refunded DECIMAL(12,4) NULL ENCODE LZO,
    grand_total DECIMAL(12,4) NULL ENCODE LZO,
    shipping_amount DECIMAL(12,4) NULL ENCODE LZO,
    shipping_canceled DECIMAL(12,4) NULL ENCODE LZO,
    shipping_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    shipping_refunded DECIMAL(12,4) NULL ENCODE LZO,
    shipping_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    shipping_tax_refunded DECIMAL(12,4) NULL ENCODE LZO,
    store_to_base_rate DECIMAL(12,4) NULL ENCODE LZO,
    store_to_order_rate DECIMAL(12,4) NULL ENCODE LZO,
    subtotal DECIMAL(12,4) NULL ENCODE LZO,
    subtotal_canceled DECIMAL(12,4) NULL ENCODE LZO,
    subtotal_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    subtotal_refunded DECIMAL(12,4) NULL ENCODE LZO,
    tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    tax_canceled DECIMAL(12,4) NULL ENCODE LZO,
    tax_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    tax_refunded DECIMAL(12,4) NULL ENCODE LZO,
    total_canceled DECIMAL(12,4) NULL ENCODE LZO,
    total_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    total_offline_refunded DECIMAL(12,4) NULL ENCODE LZO,
    total_online_refunded DECIMAL(12,4) NULL ENCODE LZO,
    total_paid DECIMAL(12,4) NULL ENCODE LZO,
    total_qty_ordered DECIMAL(12,4) NULL ENCODE LZO,
    total_refunded DECIMAL(12,4) NULL ENCODE LZO,
    can_ship_partially INTEGER NULL ENCODE LZO,
    can_ship_partially_item INTEGER NULL ENCODE LZO,
    customer_is_guest INTEGER NULL ENCODE LZO,
    customer_note_notify INTEGER NULL ENCODE LZO,
    billing_address_id INTEGER NULL ENCODE LZO,
    customer_group_id INTEGER NULL ENCODE LZO,
    edit_increment INTEGER NULL ENCODE LZO,
    email_sent INTEGER NULL ENCODE LZO,
    send_email INTEGER NULL ENCODE LZO,
    forced_shipment_with_invoice INTEGER NULL ENCODE LZO,
    payment_auth_expiration INTEGER NULL ENCODE LZO,
    quote_address_id INTEGER NULL ENCODE LZO,
    quote_id INTEGER NULL ENCODE LZO,
    shipping_address_id INTEGER NULL ENCODE LZO,
    adjustment_negative DECIMAL(12,4) NULL ENCODE LZO,
    adjustment_positive DECIMAL(12,4) NULL ENCODE LZO,
    base_adjustment_negative DECIMAL(12,4) NULL ENCODE LZO,
    base_adjustment_positive DECIMAL(12,4) NULL ENCODE LZO,
    base_shipping_discount_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_subtotal_incl_tax DECIMAL(12,4) NULL ENCODE LZO,
    base_total_due DECIMAL(12,4) NULL ENCODE LZO,
    payment_authorization_amount DECIMAL(12,4) NULL ENCODE LZO,
    shipping_discount_amount DECIMAL(12,4) NULL ENCODE LZO,
    subtotal_incl_tax DECIMAL(12,4) NULL ENCODE LZO,
    total_due DECIMAL(12,4) NULL ENCODE LZO,
    weight DECIMAL(12,4) NULL ENCODE LZO,
    customer_dob DATE NULL ENCODE LZO,
    increment_id VARCHAR(32) NULL ENCODE LZO,
    applied_rule_ids VARCHAR(128) NULL ENCODE LZO,
    base_currency_code VARCHAR(3) NULL ENCODE LZO,
    customer_email VARCHAR(128) NULL ENCODE LZO,
    customer_firstname VARCHAR(128) NULL ENCODE LZO,
    customer_lastname VARCHAR(128) NULL ENCODE LZO,
    customer_middlename VARCHAR(128) NULL ENCODE LZO,
    customer_prefix VARCHAR(32) NULL ENCODE LZO,
    customer_suffix VARCHAR(32) NULL ENCODE LZO,
    customer_taxvat VARCHAR(32) NULL ENCODE LZO,
    discount_description VARCHAR(255) NULL ENCODE LZO,
    ext_customer_id VARCHAR(32) NULL ENCODE LZO,
    ext_order_id VARCHAR(32) NULL ENCODE LZO,
    global_currency_code VARCHAR(3) NULL ENCODE LZO,
    hold_before_state VARCHAR(32) NULL ENCODE LZO,
    hold_before_status VARCHAR(32) NULL ENCODE LZO,
    order_currency_code VARCHAR(3) NULL ENCODE LZO,
    original_increment_id VARCHAR(32) NULL ENCODE LZO,
    relation_child_id VARCHAR(32) NULL ENCODE LZO,
    relation_child_real_id VARCHAR(32) NULL ENCODE LZO,
    relation_parent_id VARCHAR(32) NULL ENCODE LZO,
    relation_parent_real_id VARCHAR(32) NULL ENCODE LZO,
    remote_ip VARCHAR(32) NULL ENCODE LZO,
    shipping_method VARCHAR(120) NULL ENCODE LZO,
    store_currency_code VARCHAR(3) NULL ENCODE LZO,
    store_name VARCHAR(250) NULL ENCODE LZO,
    x_forwarded_for VARCHAR(32) NULL ENCODE LZO,
    customer_note TEXT NULL ENCODE LZO,
    created_at TIMESTAMP NOT NULL ENCODE LZO,
    updated_at TIMESTAMP NOT NULL ENCODE LZO,
    total_item_count INTEGER NOT NULL ENCODE LZO,
    customer_gender INTEGER NULL ENCODE LZO,
    discount_tax_compensation_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_discount_tax_compensation_amount DECIMAL(12,4) NULL ENCODE LZO,
    shipping_discount_tax_compensation_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_shipping_discount_tax_compensation_amnt DECIMAL(12,4) NULL ENCODE LZO,
    discount_tax_compensation_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    base_discount_tax_compensation_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    discount_tax_compensation_refunded DECIMAL(12,4) NULL ENCODE LZO,
    base_discount_tax_compensation_refunded DECIMAL(12,4) NULL ENCODE LZO,
    shipping_incl_tax DECIMAL(12,4) NULL ENCODE LZO,
    base_shipping_incl_tax DECIMAL(12,4) NULL ENCODE LZO,
    coupon_rule_name VARCHAR(255) NULL ENCODE LZO,
    base_customer_balance_amount DECIMAL(12,4) NULL ENCODE LZO,
    customer_balance_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_customer_balance_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    customer_balance_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    base_customer_balance_refunded DECIMAL(12,4) NULL ENCODE LZO,
    customer_balance_refunded DECIMAL(12,4) NULL ENCODE LZO,
    bs_customer_bal_total_refunded DECIMAL(12,4) NULL ENCODE LZO,
    customer_bal_total_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gift_cards TEXT NULL ENCODE LZO,
    base_gift_cards_amount DECIMAL(12,4) NULL ENCODE LZO,
    gift_cards_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_gift_cards_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gift_cards_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    base_gift_cards_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gift_cards_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gift_message_id INTEGER NULL ENCODE LZO,
    gw_id INTEGER NULL ENCODE LZO,
    gw_allow_gift_receipt INTEGER NULL ENCODE LZO,
    gw_add_card INTEGER NULL ENCODE LZO,
    gw_base_price DECIMAL(12,4) NULL ENCODE LZO,
    gw_price DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_base_price DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_price DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_base_price DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_price DECIMAL(12,4) NULL ENCODE LZO,
    gw_base_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    gw_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_base_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_base_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    gw_base_price_incl_tax DECIMAL(12,4) NULL ENCODE LZO,
    gw_price_incl_tax DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_base_price_incl_tax DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_price_incl_tax DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_base_price_incl_tax DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_price_incl_tax DECIMAL(12,4) NULL ENCODE LZO,
    gw_base_price_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_price_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_base_price_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_price_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_base_price_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_price_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_base_tax_amount_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_tax_amount_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_base_tax_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_tax_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_base_tax_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_tax_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    gw_base_price_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_price_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_base_price_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_price_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_base_price_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_price_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_base_tax_amount_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_tax_amount_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_base_tax_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_items_tax_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_base_tax_refunded DECIMAL(12,4) NULL ENCODE LZO,
    gw_card_tax_refunded DECIMAL(12,4) NULL ENCODE LZO,
    paypal_ipn_customer_notified INTEGER NULL ENCODE LZO,
    reward_points_balance INTEGER NULL ENCODE LZO,
    base_reward_currency_amount DECIMAL(12,4) NULL ENCODE LZO,
    reward_currency_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_rwrd_crrncy_amt_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    rwrd_currency_amount_invoiced DECIMAL(12,4) NULL ENCODE LZO,
    base_rwrd_crrncy_amnt_refnded DECIMAL(12,4) NULL ENCODE LZO,
    rwrd_crrncy_amnt_refunded DECIMAL(12,4) NULL ENCODE LZO,
    reward_points_balance_refund INTEGER NULL ENCODE LZO,
    reference_number VARCHAR(255) NULL ENCODE LZO,
    msp_cod_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_msp_cod_amount DECIMAL(12,4) NULL ENCODE LZO,
    msp_cod_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    base_msp_cod_tax_amount DECIMAL(12,4) NULL ENCODE LZO,
    erp_update VARCHAR(255) NULL ENCODE LZO,
    erp_update_count VARCHAR(255) NULL ENCODE LZO,
    device_name VARCHAR(255) NULL ENCODE LZO,
    ebizmarts_abandonedcart_flag SMALLINT NULL ENCODE LZO,
    ebizmarts_magemonkey_campaign_id VARCHAR(10) NULL ENCODE LZO,
    msp_base_cashondelivery DECIMAL(12,4) NOT NULL ENCODE LZO,
    msp_cashondelivery DECIMAL(12,4) NOT NULL ENCODE LZO,
    msp_base_cashondelivery_incl_tax DECIMAL(12,4) NOT NULL ENCODE LZO,
    msp_cashondelivery_incl_tax DECIMAL(12,4) NOT NULL ENCODE LZO,
    paymentid VARCHAR(255) NULL ENCODE LZO,
    tranid VARCHAR(255) NULL ENCODE LZO,
    result VARCHAR(255) NULL ENCODE LZO,
    payment_method VARCHAR(255) NULL ENCODE LZO,
    telephone VARCHAR(255) NULL ENCODE LZO,
    website_id VARCHAR(255) NULL ENCODE LZO,
    device_type VARCHAR(255) NULL ENCODE LZO,
    device_model VARCHAR(255) NULL ENCODE LZO,
    app_version VARCHAR(255) NULL ENCODE LZO,
    os_version VARCHAR(255) NULL ENCODE LZO,
    device_token_android TEXT NULL ENCODE LZO,
    device_token_ios TEXT NULL ENCODE LZO,
    sms_sent_status INTEGER NOT NULL ENCODE LZO,
    sms_customer_status INTEGER NOT NULL ENCODE LZO,
    new_erp_update_count VARCHAR(45) NOT NULL ENCODE LZO,
    new_erp_update VARCHAR(45) NULL ENCODE LZO,
    telephone_no VARCHAR(255) NULL ENCODE LZO,
    custom_vat DECIMAL(12,4) NULL ENCODE LZO,
    fee DECIMAL(12,4) NULL ENCODE LZO,
    base_fee DECIMAL(12,4) NULL ENCODE LZO,
    base_custom_vat DECIMAL(12,4) NULL ENCODE LZO,
    clearance_charges DECIMAL(12,4) NULL ENCODE LZO,
    base_clearance_charges DECIMAL(12,4) NULL ENCODE LZO,
    created_time_ml TIMESTAMP NULL ENCODE LZO,
    myfatoorah_payment VARCHAR(100) NULL ENCODE LZO,
    myfatoorah_orderid VARCHAR(100) NULL ENCODE LZO
);

INSERT INTO magento.sales_order
SELECT entity_id, state, status, coupon_code, protect_code, shipping_description, is_virtual, store_id, customer_id, base_discount_amount, base_discount_canceled, base_discount_invoiced, base_discount_refunded, base_grand_total, base_shipping_amount, base_shipping_canceled, base_shipping_invoiced, base_shipping_refunded, base_shipping_tax_amount, base_shipping_tax_refunded, base_subtotal, base_subtotal_canceled, base_subtotal_invoiced, base_subtotal_refunded, base_tax_amount, base_tax_canceled, base_tax_invoiced, base_tax_refunded, base_to_global_rate, base_to_order_rate, base_total_canceled, base_total_invoiced, base_total_invoiced_cost, base_total_offline_refunded, base_total_online_refunded, base_total_paid, base_total_qty_ordered, base_total_refunded, discount_amount, discount_canceled, discount_invoiced, discount_refunded, grand_total, shipping_amount, shipping_canceled, shipping_invoiced, shipping_refunded, shipping_tax_amount, shipping_tax_refunded, store_to_base_rate, store_to_order_rate, subtotal, subtotal_canceled, subtotal_invoiced, subtotal_refunded, tax_amount, tax_canceled, tax_invoiced, tax_refunded, total_canceled, total_invoiced, total_offline_refunded, total_online_refunded, total_paid, total_qty_ordered, total_refunded, can_ship_partially, can_ship_partially_item, customer_is_guest, customer_note_notify, billing_address_id, customer_group_id, edit_increment, email_sent, send_email, forced_shipment_with_invoice, payment_auth_expiration, quote_address_id, quote_id, shipping_address_id, adjustment_negative, adjustment_positive, base_adjustment_negative, base_adjustment_positive, base_shipping_discount_amount, base_subtotal_incl_tax, base_total_due, payment_authorization_amount, shipping_discount_amount, subtotal_incl_tax, total_due, weight, DATE(customer_dob), increment_id, applied_rule_ids, base_currency_code, customer_email, customer_firstname, customer_lastname, customer_middlename, customer_prefix, customer_suffix, customer_taxvat, discount_description, ext_customer_id, ext_order_id, global_currency_code, hold_before_state, hold_before_status, order_currency_code, original_increment_id, relation_child_id, relation_child_real_id, relation_parent_id, relation_parent_real_id, remote_ip, shipping_method, store_currency_code, store_name, x_forwarded_for, customer_note, created_at, updated_at, total_item_count, customer_gender, discount_tax_compensation_amount, base_discount_tax_compensation_amount, shipping_discount_tax_compensation_amount, base_shipping_discount_tax_compensation_amnt, discount_tax_compensation_invoiced, base_discount_tax_compensation_invoiced, discount_tax_compensation_refunded, base_discount_tax_compensation_refunded, shipping_incl_tax, base_shipping_incl_tax, coupon_rule_name, base_customer_balance_amount, customer_balance_amount, base_customer_balance_invoiced, customer_balance_invoiced, base_customer_balance_refunded, customer_balance_refunded, bs_customer_bal_total_refunded, customer_bal_total_refunded, gift_cards, base_gift_cards_amount, gift_cards_amount, base_gift_cards_invoiced, gift_cards_invoiced, base_gift_cards_refunded, gift_cards_refunded, gift_message_id, gw_id, gw_allow_gift_receipt, gw_add_card, gw_base_price, gw_price, gw_items_base_price, gw_items_price, gw_card_base_price, gw_card_price, gw_base_tax_amount, gw_tax_amount, gw_items_base_tax_amount, gw_items_tax_amount, gw_card_base_tax_amount, gw_card_tax_amount, gw_base_price_incl_tax, gw_price_incl_tax, gw_items_base_price_incl_tax, gw_items_price_incl_tax, gw_card_base_price_incl_tax, gw_card_price_incl_tax, gw_base_price_invoiced, gw_price_invoiced, gw_items_base_price_invoiced, gw_items_price_invoiced, gw_card_base_price_invoiced, gw_card_price_invoiced, gw_base_tax_amount_invoiced, gw_tax_amount_invoiced, gw_items_base_tax_invoiced, gw_items_tax_invoiced, gw_card_base_tax_invoiced, gw_card_tax_invoiced, gw_base_price_refunded, gw_price_refunded, gw_items_base_price_refunded, gw_items_price_refunded, gw_card_base_price_refunded, gw_card_price_refunded, gw_base_tax_amount_refunded, gw_tax_amount_refunded, gw_items_base_tax_refunded, gw_items_tax_refunded, gw_card_base_tax_refunded, gw_card_tax_refunded, paypal_ipn_customer_notified, reward_points_balance, base_reward_currency_amount, reward_currency_amount, base_rwrd_crrncy_amt_invoiced, rwrd_currency_amount_invoiced, base_rwrd_crrncy_amnt_refnded, rwrd_crrncy_amnt_refunded, reward_points_balance_refund, reference_number, msp_cod_amount, base_msp_cod_amount, msp_cod_tax_amount, base_msp_cod_tax_amount, erp_update, erp_update_count, device_name, ebizmarts_abandonedcart_flag, ebizmarts_magemonkey_campaign_id, msp_base_cashondelivery, msp_cashondelivery, msp_base_cashondelivery_incl_tax, msp_cashondelivery_incl_tax, paymentid, tranid, result, payment_method, telephone, website_id, device_type, device_model, app_version, os_version, device_token_android, device_token_ios, sms_sent_status, sms_customer_status, new_erp_update_count, new_erp_update, telephone_no, custom_vat, fee, base_fee, base_custom_vat, clearance_charges, base_clearance_charges, created_time_ml, myfatoorah_payment, myfatoorah_orderid
FROM tmp_sales_order;
COMMIT;

