SELECT 
    ID as id, 
    WebOrderNo as web_order_no, 
    OrderStatus as order_status, 
    OrderDateTime as order_datetime, 
    PaymentMethod as payment_method, 
    UserAssign as user_assign, 
    OrderCategory as order_category, 
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(FirstName), '\r', ''),'\n',''),'\t',''),'\"', '') as first_name, 
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(MiddleName), '\r', ''),'\n',''),'\t',''),'\"', '') as middle_name, 
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(LastName), '\r', ''),'\n',''),'\t',''),'\"', '') as last_name, 
    CustomerId as customer_id, 
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(CustomerEmail), '\r', ''),'\n',''),'\t',''),'\"', '') as customer_email, 
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(CustomerPhone), '\r', ''),'\n',''),'\t',''),'\"', '') as customer_phone, 
    PackagingLocation as packaging_location, 
    InsertedOn as inserted_on, 
    InsertedBy as inserted_by, 
    UpdatedOn as updated_on, 
    UpdatedBy as updated_by, 
    ReadyForArchive as ready_for_archive, 
    Country as country, 
    OrderSource as order_source, 
    OrderAmount as order_amount, 
    Currency as currency, 
    OrderType as order_type, 
    ReferenceOrderNo as reference_order_no, 
    AppOrderNo as app_order_no, 
    Company as company, 
    IsRuleRun as is_rule_run,
    AssigndByUserId as assignd_by_user_id 
FROM OFS.CRMOrders
WHERE \$CONDITIONS