SELECT
    entity_id,
    attribute_set_id,
    type_id,
    row_id,
    accessories_size,
    accessories_size_value,
    allow_open_amount,
    boutiqaat_homepicks,
    cost,
    created_at,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(description), '\r', ''),'\n',''),'\t',''),'\"', '') as description,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(email_template), '\r', ''),'\n',''),'\t',''),'\"', '') as email_template,
    exclusive,
    footwear_size,
    footwear_size_value,
    gender,
    giftcard_amounts,
    giftcard_type,
    gift_message_available,
    gift_wrapping_available,
    gift_wrapping_price,
    has_options,
    image_label,
    is_featured,
    is_new,
    is_redeemable,
    lifetime,
    links_exist,
    links_purchased_separately,
    links_title,
    lp_custom,
    lp_custom_value,
    lp_custom_category,
    lp_custom_category_value,
    manufacturer,
    manufacturer_value,
    msrp,
    msrp_display_actual_price_type,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(name), '\r', ''),'\n',''),'\t',''),'\"', '') as name,
    news_from_date,
    news_to_date,
    open_amount_max,
    open_amount_min,
    ordered_qty,
    price,
    price_type,
    price_view,
    required_options,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(short_description), '\r', ''),'\n',''),'\t',''),'\"', '') as short_description,
    sku,
    sku_type,
    small_image,
    small_image_label,
    special_from_date,
    special_price,
    special_to_date,
    swatch_image,
    tax_class_id,
    thumbnail,
    thumbnail_label,
    updated_at,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(url_key), '\r', ''),'\n',''),'\t',''),'\"', '') as url_key,
    REPLACE(REPLACE(REPLACE(REPLACE(TRIM(url_path), '\r', ''),'\n',''),'\t',''),'\"', '') as url_path,
    use_config_email_template,
    use_config_is_redeemable,
    use_config_lifetime,
    visibility,
    weight,
    weight_type
FROM boutiqaat_v2.catalog_product_flat_1
WHERE \$CONDITIONS