version: '2.1'
services:
  redis:
    image: 'redis:5.0.5'
  postgres:
    image: 'postgres:9.6'
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  webserver:
    image: 'btq-airflow:latest'
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - AIRFLOW__WEBSERVER__RBAC=true
    volumes:
      - './dags:/usr/local/airflow/dags'
    ports:
      - '8080:8080'
    command: webserver
    healthcheck:
      test:
        - CMD-SHELL
        - '[ -f /usr/local/airflow/airflow-webserver.pid ]'
      interval: 30s
      timeout: 30s
      retries: 3
  flower:
    image: 'btq-airflow:latest'
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
    ports:
      - '5555:5555'
    command: flower
  scheduler:
    image: 'btq-airflow:latest'
    restart: always
    depends_on:
      - webserver
    volumes:
      - './dags:/usr/local/airflow/dags'
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
    command: scheduler
  worker:
    image: 'btq-airflow:latest'
    restart: always
    depends_on:
      - scheduler
    volumes:
      - './dags:/usr/local/airflow/dags'
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
    command: worker
