BEGIN;
DROP TABLE IF EXISTS tmp_item_ledger_entry;
CREATE TEMP TABLE tmp_item_ledger_entry(
	ts varchar(40),
	entry_no INTEGER,
	item_no VARCHAR(40),
	posting_date timestamp,
	entry_type INTEGER,
	source_no VARCHAR(40),
	document_no VARCHAR(40),
	description VARCHAR(400),
	location_code VARCHAR(20),
	quantity decimal(38,20),
	remaining_quantity decimal(38,20),
	invoiced_quantity decimal(38,20),
	applies_to_entry INTEGER,
	is_open SMALLINT,
	global_dimension_1_code VARCHAR(40),
	global_dimension_2_code VARCHAR(40),
	positive SMALLINT,
	source_type INTEGER,
	drop_shipment SMALLINT,
	transaction_type VARCHAR(20),
	transport_method VARCHAR(20),
	country_region_code VARCHAR(20),
	entry_exit_point VARCHAR(20),
	document_date timestamp,
	external_document_no VARCHAR(70),
	area VARCHAR(20),
	transaction_specification VARCHAR(20),
	no_series VARCHAR(20),
	document_type INTEGER,
	document_line_no INTEGER,
	order_type INTEGER,
	order_no VARCHAR(40),
	order_line_no INTEGER,
	dimension_set_id INTEGER,
	assemble_to_order SMALLINT,
	job_no VARCHAR(40),
	job_task_no VARCHAR(40),
	job_purchase SMALLINT,
	variant_code VARCHAR(20),
	qty_per_unit_of_measure decimal(38,20),
	unit_of_measure_code VARCHAR(20),
	derived_from_blanket_order SMALLINT,
	cross_reference_no VARCHAR(40),
	originally_ordered_no VARCHAR(40),
	originally_ordered_var_code VARCHAR(20),
	out_of_stock_substitution SMALLINT,
	item_category_code VARCHAR(40),
	nonstock SMALLINT,
	purchasing_code VARCHAR(20),
	product_group_code VARCHAR(40),
	completely_invoiced SMALLINT,
	last_invoice_date timestamp,
	applied_entry_to_adjust SMALLINT,
	correction SMALLINT,
	shipped_qty_not_returned decimal(38,20),
	prod_order_comp_line_no INTEGER,
	serial_no VARCHAR(40),
	lot_no VARCHAR(40),
	warranty_date timestamp,
	expiration_date timestamp,
	item_tracking INTEGER,
	return_reason_code VARCHAR(20),
	web_order_id VARCHAR(40),
	foc SMALLINT,
	foc_reason VARCHAR(40),
	purchase_order_type INTEGER,
	tester SMALLINT,
	vendor_no VARCHAR(40),
	posted_on INTEGER,
	inventory_type INTEGER,
	sales_entry_type INTEGER
);

copy tmp_item_ledger_entry from '{{S3PATH}}'
iam_role 'arn:aws:iam::652586300051:role/Redshift-athena-S3-readonly'
delimiter '\t'
region 'eu-west-1' 
acceptinvchars
CSV 
GZIP 
emptyasnull
blanksasnull
NULL AS 'null';


DROP TABLE IF EXISTS NAV.item_ledger_entry;
CREATE TABLE NAV.item_ledger_entry (	
	ts varchar(40) NULL ENCODE LZO,
	entry_no INTEGER NULL ENCODE DELTA DISTKEY SORTKEY PRIMARY KEY,
	item_no VARCHAR(40) NULL ENCODE LZO,
	posting_date timestamp NULL ENCODE LZO,
	entry_type INTEGER NULL ENCODE DELTA,
	source_no VARCHAR(40) NULL ENCODE LZO,
	document_no VARCHAR(40) NULL ENCODE LZO,
	description VARCHAR(400) NULL ENCODE LZO,
	location_code VARCHAR(20) NULL ENCODE LZO,
	quantity decimal(38,20) NULL ENCODE LZO,
	remaining_quantity decimal(38,20) NULL ENCODE LZO,
	invoiced_quantity decimal(38,20) NULL ENCODE LZO,
	applies_to_entry INTEGER NULL ENCODE DELTA,
	is_open SMALLINT NULL ENCODE DELTA,
	global_dimension_1_code VARCHAR(40) NULL ENCODE LZO,
	global_dimension_2_code VARCHAR(40) NULL ENCODE LZO,
	positive SMALLINT NULL ENCODE DELTA,
	source_type INTEGER NULL ENCODE DELTA,
	drop_shipment SMALLINT NULL ENCODE DELTA,
	transaction_type VARCHAR(20) NULL ENCODE LZO,
	transport_method VARCHAR(20) NULL ENCODE LZO,
	country_region_code VARCHAR(20) NULL ENCODE LZO,
	entry_exit_point VARCHAR(20) NULL ENCODE LZO,
	document_date timestamp NULL ENCODE LZO,
	external_document_no VARCHAR(70) NULL ENCODE LZO,
	area VARCHAR(20) NULL ENCODE LZO,
	transaction_specification VARCHAR(20) NULL ENCODE LZO,
	no_series VARCHAR(20) NULL ENCODE LZO,
	document_type INTEGER NULL ENCODE DELTA,
	document_line_no INTEGER NULL ENCODE DELTA,
	order_type INTEGER NULL ENCODE DELTA,
	order_no VARCHAR(40) NULL ENCODE LZO,
	order_line_no INTEGER NULL ENCODE DELTA,
	dimension_set_id INTEGER NULL ENCODE DELTA,
	assemble_to_order SMALLINT NULL ENCODE DELTA,
	job_no VARCHAR(40) NULL ENCODE LZO,
	job_task_no VARCHAR(40) NULL ENCODE LZO,
	job_purchase SMALLINT NULL ENCODE DELTA,
	variant_code VARCHAR(20) NULL ENCODE LZO,
	qty_per_unit_of_measure decimal(38,20) NULL ENCODE LZO,
	unit_of_measure_code VARCHAR(20) NULL ENCODE LZO,
	derived_from_blanket_order SMALLINT NULL ENCODE DELTA,
	cross_reference_no VARCHAR(40) NULL ENCODE LZO,
	originally_ordered_no VARCHAR(40) NULL ENCODE LZO,
	originally_ordered_var_code VARCHAR(20) NULL ENCODE LZO,
	out_of_stock_substitution SMALLINT NULL ENCODE DELTA,
	item_category_code VARCHAR(40) NULL ENCODE LZO,
	nonstock SMALLINT NULL ENCODE DELTA,
	purchasing_code VARCHAR(20) NULL ENCODE LZO,
	product_group_code VARCHAR(40) NULL ENCODE LZO,
	completely_invoiced SMALLINT NULL ENCODE DELTA,
	last_invoice_date timestamp NULL ENCODE LZO,
	applied_entry_to_adjust SMALLINT NULL ENCODE DELTA,
	correction SMALLINT NULL ENCODE DELTA,
	shipped_qty_not_returned decimal(38,20) NULL ENCODE LZO,
	prod_order_comp_line_no INTEGER NULL ENCODE DELTA,
	serial_no VARCHAR(40) NULL ENCODE LZO,
	lot_no VARCHAR(40) NULL ENCODE LZO,
	warranty_date timestamp NULL ENCODE LZO,
	expiration_date timestamp NULL ENCODE LZO,
	item_tracking INTEGER NULL ENCODE DELTA,
	return_reason_code VARCHAR(20) NULL ENCODE LZO,
	web_order_id VARCHAR(40) NULL ENCODE LZO,
	foc SMALLINT NULL ENCODE DELTA,
	foc_reason VARCHAR(40) NULL ENCODE LZO,
	purchase_order_type INTEGER NULL ENCODE DELTA,
	tester SMALLINT NULL ENCODE DELTA,
	vendor_no VARCHAR(40) NULL ENCODE LZO,
	posted_on INTEGER NULL ENCODE DELTA,
	inventory_type INTEGER NULL ENCODE DELTA,
	sales_entry_type INTEGER NULL ENCODE DELTA
);


INSERT INTO NAV.item_ledger_entry
SELECT ts, entry_no, item_no, posting_date, entry_type, source_no, document_no, description, location_code, quantity, remaining_quantity, invoiced_quantity, applies_to_entry, is_open, global_dimension_1_code, global_dimension_2_code, positive, source_type, drop_shipment, transaction_type, transport_method, country_region_code, entry_exit_point, document_date, external_document_no, area, transaction_specification, no_series, document_type, document_line_no, order_type, order_no, order_line_no, dimension_set_id, assemble_to_order, job_no, job_task_no, job_purchase, variant_code, qty_per_unit_of_measure, unit_of_measure_code, derived_from_blanket_order, cross_reference_no, originally_ordered_no, originally_ordered_var_code, out_of_stock_substitution, item_category_code, nonstock, purchasing_code, product_group_code, completely_invoiced, last_invoice_date, applied_entry_to_adjust, correction, shipped_qty_not_returned, prod_order_comp_line_no, serial_no, lot_no, warranty_date, expiration_date, item_tracking, return_reason_code, web_order_id, foc, foc_reason, purchase_order_type, tester, vendor_no, posted_on, inventory_type, sales_entry_type
FROM tmp_item_ledger_entry;
COMMIT;