BEGIN;
DROP TABLE IF EXISTS tmp_purchase_line;
CREATE TEMP TABLE tmp_purchase_line(
	ts VARCHAR(40),
	document_type INTEGER,
	document_no VARCHAR(40),
	line_no INTEGER,
	buy_from_vendor_no VARCHAR(40),
	type INTEGER,
	no VARCHAR(40),
	location_code VARCHAR(20),
	posting_group VARCHAR(20),
	expected_receipt_date timestamp,
	description VARCHAR(400),
	description_2 VARCHAR(400),
	unit_of_measure VARCHAR(20),
	quantity decimal(38,20),
	outstanding_quantity decimal(38,20),
	qty_to_invoice decimal(38,20),
	qty_to_receive decimal(38,20),
	direct_unit_cost decimal(38,20),
	unit_cost_lcy decimal(38,20),
	vat decimal(38,20),
	line_discount decimal(38,20),
	line_discount_amount decimal(38,20),
	amount decimal(38,20),
	amount_including_vat decimal(38,20),
	unit_price_lcy decimal(38,20),
	allow_invoice_disc SMALLINT,
	gross_weight decimal(38,20),
	net_weight decimal(38,20),
	units_per_parcel decimal(38,20),
	unit_volume decimal(38,20),
	appl_to_item_entry INTEGER,
	shortcut_dimension_1_code VARCHAR(40),
	shortcut_dimension_2_code VARCHAR(40),
	job_no VARCHAR(40),
	indirect_cost decimal(38,20),
	recalculate_invoice_disc SMALLINT,
	outstanding_amount decimal(38,20),
	qty_rcd_not_invoiced decimal(38,20),
	amt_rcd_not_invoiced decimal(38,20),
	quantity_received decimal(38,20),
	quantity_invoiced decimal(38,20),
	receipt_no VARCHAR(40),
	receipt_line_no INTEGER,
	profit decimal(38,20),
	pay_to_vendor_no VARCHAR(40),
	inv_discount_amount decimal(38,20),
	vendor_item_no VARCHAR(40),
	sales_order_no VARCHAR(40),
	sales_order_line_no INTEGER,
	drop_shipment SMALLINT,
	gen_bus_posting_group VARCHAR(20),
	gen_prod_posting_group VARCHAR(20),
	vat_calculation_type INTEGER,
	transaction_type VARCHAR(20),
	transport_method VARCHAR(20),
	attached_to_line_no INTEGER,
	entry_point VARCHAR(20),
	area VARCHAR(20),
	transaction_specification VARCHAR(20),
	tax_area_code VARCHAR(40),
	tax_liable SMALLINT,
	tax_group_code VARCHAR(20),
	use_tax SMALLINT,
	vat_bus_posting_group VARCHAR(20),
	vat_prod_posting_group VARCHAR(20),
	currency_code VARCHAR(20),
	outstanding_amount_lcy decimal(38,20),
	amt_rcd_not_invoiced_lcy decimal(38,20),
	blanket_order_no VARCHAR(40),
	blanket_order_line_no INTEGER,
	vat_base_amount decimal(38,20),
	unit_cost decimal(38,20),
	system_created_entry SMALLINT,
	line_amount decimal(38,20),
	vat_difference decimal(38,20),
	inv_disc_amount_to_invoice decimal(38,20),
	vat_identifier VARCHAR(20),
	ic_partner_ref_type INTEGER,
	ic_partner_reference VARCHAR(40),
	prepayment decimal(38,20),
	prepmt_line_amount decimal(38,20),
	prepmt_amt_inv decimal(38,20),
	prepmt_amt_incl_vat decimal(38,20),
	prepayment_amount decimal(38,20),
	prepmt_vat_base_amt decimal(38,20),
	prepayment_vat decimal(38,20),
	prepmt_vat_calc_type INTEGER,
	prepayment_vat_identifier VARCHAR(20),
	prepayment_tax_area_code VARCHAR(40),
	prepayment_tax_liable SMALLINT,
	prepayment_tax_group_code VARCHAR(20),
	prepmt_amt_to_deduct decimal(38,20),
	prepmt_amt_deducted decimal(38,20),
	prepayment_line SMALLINT,
	prepmt_amount_inv_incl_vat decimal(38,20),
	prepmt_amount_inv_lcy decimal(38,20),
	ic_partner_code VARCHAR(40),
	prepmt_vat_amount_inv_lcy decimal(38,20),
	prepayment_vat_difference decimal(38,20),
	prepmt_vat_diff_to_deduct decimal(38,20),
	prepmt_vat_diff_deducted decimal(38,20),
	outstanding_amt_ex_vat_lcy decimal(38,20),
	a_rcd_not_inv_ex_vat_lcy decimal(38,20),
	dimension_set_id INTEGER,
	job_task_no VARCHAR(40),
	job_line_type INTEGER,
	job_unit_price decimal(38,20),
	job_total_price decimal(38,20),
	job_line_amount decimal(38,20),
	job_line_discount_amount decimal(38,20),
	job_line_discount decimal(38,20),
	job_unit_price_lcy decimal(38,20),
	job_total_price_lcy decimal(38,20),
	job_line_amount_lcy decimal(38,20),
	job_line_disc_amount_lcy decimal(38,20),
	job_currency_factor decimal(38,20),
	job_currency_code VARCHAR(40),
	job_planning_line_no INTEGER,
	job_remaining_qty decimal(38,20),
	job_remaining_qty_base decimal(38,20),
	deferral_code VARCHAR(20),
	returns_deferral_start_date timestamp,
	prod_order_no VARCHAR(40),
	variant_code VARCHAR(20),
	bin_code VARCHAR(40),
	qty_per_unit_of_measure decimal(38,20),
	unit_of_measure_code VARCHAR(20),
	quantity_base decimal(38,20),
	outstanding_qty_base decimal(38,20),
	qty_to_invoice_base decimal(38,20),
	qty_to_receive_base decimal(38,20),
	qty_rcd_not_invoiced_base decimal(38,20),
	qty_received_base decimal(38,20),
	qty_invoiced_base decimal(38,20),
	fa_posting_date timestamp,
	fa_posting_type INTEGER,
	depreciation_book_code VARCHAR(20),
	salvage_value decimal(38,20),
	depr_until_fa_posting_date SMALLINT,
	depr_acquisition_cost SMALLINT,
	maintenance_code VARCHAR(20),
	insurance_no VARCHAR(40),
	budgeted_fa_no VARCHAR(40),
	duplicate_in_depreciation_book VARCHAR(20),
	use_duplication_list SMALLINT,
	responsibility_center VARCHAR(20),
	cross_reference_no VARCHAR(40),
	unit_of_measure_cross_ref VARCHAR(20),
	cross_reference_type INTEGER,
	cross_reference_type_no VARCHAR(60),
	item_category_code VARCHAR(40),
	nonstock SMALLINT,
	purchasing_code VARCHAR(20),
	product_group_code VARCHAR(40),
	special_order SMALLINT,
	special_order_sales_no VARCHAR(40),
	special_order_sales_line_no INTEGER,
	completely_received SMALLINT,
	requested_receipt_date timestamp,
	promised_receipt_date timestamp,
	lead_time_calculation varchar(32),
	inbound_whse_handling_time varchar(32),
	planned_receipt_date timestamp,
	order_date timestamp,
	allow_item_charge_assignment SMALLINT,
	return_qty_to_ship decimal(38,20),
	return_qty_to_ship_base decimal(38,20),
	return_qty_shipped_not_invd decimal(38,20),
	ret_qty_shpd_not_invd_base decimal(38,20),
	return_shpd_not_invd decimal(38,20),
	return_shpd_not_invd_lcy decimal(38,20),
	return_qty_shipped decimal(38,20),
	return_qty_shipped_base decimal(38,20),
	return_shipment_no VARCHAR(40),
	return_shipment_line_no INTEGER,
	return_reason_code VARCHAR(20),
	foc SMALLINT,
	amount_inc_tax_lcy decimal(38,20),
	ret_doc_no VARCHAR(40),
	ret_doc_line_no INTEGER,
	contract_no VARCHAR(40),
	margin decimal(38,20),
	add_margin decimal(38,20),
	add_foc_quantity decimal(38,20),
	purchase_cost decimal(38,20),
	tester SMALLINT,
	ean_code VARCHAR(60),
	narration VARCHAR(500),
	inventory_type INTEGER,
	item_category_3 VARCHAR(40),
	item_category_4 VARCHAR(40),
	brand VARCHAR(40),
	original_purchase_cost decimal(38,20),
	cost_updated_by VARCHAR(100),
	focpo SMALLINT,
	system_calculated_foc SMALLINT,
	routing_no VARCHAR(40),
	operation_no VARCHAR(20),
	work_center_no VARCHAR(40),
	finished SMALLINT,
	prod_order_line_no INTEGER,
	overhead_rate decimal(38,20),
	mps_order SMALLINT,
	planning_flexibility INTEGER,
	safety_lead_time varchar(32),
	routing_reference_no INTEGER
);

copy tmp_purchase_line from '{{S3PATH}}'
iam_role 'arn:aws:iam::652586300051:role/Redshift-athena-S3-readonly'
delimiter '\t'
region 'eu-west-1' 
acceptinvchars
CSV 
GZIP 
NULL AS 'null';


DROP TABLE IF EXISTS NAV.purchase_line;
CREATE TABLE NAV.purchase_line (
	ts VARCHAR(40) NOT NULL ENCODE LZO,
	document_type INTEGER NOT NULL ENCODE DELTA,
	document_no VARCHAR(40) NOT NULL ENCODE LZO,
	line_no INTEGER NOT NULL ENCODE DELTA,
	buy_from_vendor_no VARCHAR(40) NOT NULL ENCODE LZO,
	type INTEGER NOT NULL ENCODE DELTA,
	no VARCHAR(40) NOT NULL ENCODE LZO,
	location_code VARCHAR(20) NOT NULL ENCODE LZO,
	posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	expected_receipt_date timestamp NOT NULL ENCODE LZO,
	description VARCHAR(400) NOT NULL ENCODE LZO,
	description_2 VARCHAR(400) NOT NULL ENCODE LZO,
	unit_of_measure VARCHAR(20) NOT NULL ENCODE LZO,
	quantity decimal(38,20) NOT NULL ENCODE LZO,
	outstanding_quantity decimal(38,20) NOT NULL ENCODE LZO,
	qty_to_invoice decimal(38,20) NOT NULL ENCODE LZO,
	qty_to_receive decimal(38,20) NOT NULL ENCODE LZO,
	direct_unit_cost decimal(38,20) NOT NULL ENCODE LZO,
	unit_cost_lcy decimal(38,20) NOT NULL ENCODE LZO,
	vat decimal(38,20) NOT NULL ENCODE LZO,
	line_discount decimal(38,20) NOT NULL ENCODE LZO,
	line_discount_amount decimal(38,20) NOT NULL ENCODE LZO,
	amount decimal(38,20) NOT NULL ENCODE LZO,
	amount_including_vat decimal(38,20) NOT NULL ENCODE LZO,
	unit_price_lcy decimal(38,20) NOT NULL ENCODE LZO,
	allow_invoice_disc SMALLINT NOT NULL ENCODE DELTA,
	gross_weight decimal(38,20) NOT NULL ENCODE LZO,
	net_weight decimal(38,20) NOT NULL ENCODE LZO,
	units_per_parcel decimal(38,20) NOT NULL ENCODE LZO,
	unit_volume decimal(38,20) NOT NULL ENCODE LZO,
	appl_to_item_entry INTEGER NOT NULL ENCODE DELTA,
	shortcut_dimension_1_code VARCHAR(40) NOT NULL ENCODE LZO,
	shortcut_dimension_2_code VARCHAR(40) NOT NULL ENCODE LZO,
	job_no VARCHAR(40) NOT NULL ENCODE LZO,
	indirect_cost decimal(38,20) NOT NULL ENCODE LZO,
	recalculate_invoice_disc SMALLINT NOT NULL ENCODE DELTA,
	outstanding_amount decimal(38,20) NOT NULL ENCODE LZO,
	qty_rcd_not_invoiced decimal(38,20) NOT NULL ENCODE LZO,
	amt_rcd_not_invoiced decimal(38,20) NOT NULL ENCODE LZO,
	quantity_received decimal(38,20) NOT NULL ENCODE LZO,
	quantity_invoiced decimal(38,20) NOT NULL ENCODE LZO,
	receipt_no VARCHAR(40) NOT NULL ENCODE LZO,
	receipt_line_no INTEGER NOT NULL ENCODE DELTA,
	profit decimal(38,20) NOT NULL ENCODE LZO,
	pay_to_vendor_no VARCHAR(40) NOT NULL ENCODE LZO,
	inv_discount_amount decimal(38,20) NOT NULL ENCODE LZO,
	vendor_item_no VARCHAR(40) NOT NULL ENCODE LZO,
	sales_order_no VARCHAR(40) NOT NULL ENCODE LZO,
	sales_order_line_no INTEGER NOT NULL ENCODE DELTA,
	drop_shipment SMALLINT NOT NULL ENCODE DELTA,
	gen_bus_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	gen_prod_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	vat_calculation_type INTEGER NOT NULL ENCODE DELTA,
	transaction_type VARCHAR(20) NOT NULL ENCODE LZO,
	transport_method VARCHAR(20) NOT NULL ENCODE LZO,
	attached_to_line_no INTEGER NOT NULL ENCODE DELTA,
	entry_point VARCHAR(20) NOT NULL ENCODE LZO,
	area VARCHAR(20) NOT NULL ENCODE LZO,
	transaction_specification VARCHAR(20) NOT NULL ENCODE LZO,
	tax_area_code VARCHAR(40) NOT NULL ENCODE LZO,
	tax_liable SMALLINT NOT NULL ENCODE DELTA,
	tax_group_code VARCHAR(20) NOT NULL ENCODE LZO,
	use_tax SMALLINT NOT NULL ENCODE DELTA,
	vat_bus_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	vat_prod_posting_group VARCHAR(20) NOT NULL ENCODE LZO,
	currency_code VARCHAR(20) NOT NULL ENCODE LZO,
	outstanding_amount_lcy decimal(38,20) NOT NULL ENCODE LZO,
	amt_rcd_not_invoiced_lcy decimal(38,20) NOT NULL ENCODE LZO,
	blanket_order_no VARCHAR(40) NOT NULL ENCODE LZO,
	blanket_order_line_no INTEGER NOT NULL ENCODE DELTA,
	vat_base_amount decimal(38,20) NOT NULL ENCODE LZO,
	unit_cost decimal(38,20) NOT NULL ENCODE LZO,
	system_created_entry SMALLINT NOT NULL ENCODE DELTA,
	line_amount decimal(38,20) NOT NULL ENCODE LZO,
	vat_difference decimal(38,20) NOT NULL ENCODE LZO,
	inv_disc_amount_to_invoice decimal(38,20) NOT NULL ENCODE LZO,
	vat_identifier VARCHAR(20) NOT NULL ENCODE LZO,
	ic_partner_ref_type INTEGER NOT NULL ENCODE DELTA,
	ic_partner_reference VARCHAR(40) NOT NULL ENCODE LZO,
	prepayment decimal(38,20) NOT NULL ENCODE LZO,
	prepmt_line_amount decimal(38,20) NOT NULL ENCODE LZO,
	prepmt_amt_inv decimal(38,20) NOT NULL ENCODE LZO,
	prepmt_amt_incl_vat decimal(38,20) NOT NULL ENCODE LZO,
	prepayment_amount decimal(38,20) NOT NULL ENCODE LZO,
	prepmt_vat_base_amt decimal(38,20) NOT NULL ENCODE LZO,
	prepayment_vat decimal(38,20) NOT NULL ENCODE LZO,
	prepmt_vat_calc_type INTEGER NOT NULL ENCODE DELTA,
	prepayment_vat_identifier VARCHAR(20) NOT NULL ENCODE LZO,
	prepayment_tax_area_code VARCHAR(40) NOT NULL ENCODE LZO,
	prepayment_tax_liable SMALLINT NOT NULL ENCODE DELTA,
	prepayment_tax_group_code VARCHAR(20) NOT NULL ENCODE LZO,
	prepmt_amt_to_deduct decimal(38,20) NOT NULL ENCODE LZO,
	prepmt_amt_deducted decimal(38,20) NOT NULL ENCODE LZO,
	prepayment_line SMALLINT NOT NULL ENCODE DELTA,
	prepmt_amount_inv_incl_vat decimal(38,20) NOT NULL ENCODE LZO,
	prepmt_amount_inv_lcy decimal(38,20) NOT NULL ENCODE LZO,
	ic_partner_code VARCHAR(40) NOT NULL ENCODE LZO,
	prepmt_vat_amount_inv_lcy decimal(38,20) NOT NULL ENCODE LZO,
	prepayment_vat_difference decimal(38,20) NOT NULL ENCODE LZO,
	prepmt_vat_diff_to_deduct decimal(38,20) NOT NULL ENCODE LZO,
	prepmt_vat_diff_deducted decimal(38,20) NOT NULL ENCODE LZO,
	outstanding_amt_ex_vat_lcy decimal(38,20) NOT NULL ENCODE LZO,
	a_rcd_not_inv_ex_vat_lcy decimal(38,20) NOT NULL ENCODE LZO,
	dimension_set_id INTEGER NOT NULL ENCODE DELTA,
	job_task_no VARCHAR(40) NOT NULL ENCODE LZO,
	job_line_type INTEGER NOT NULL ENCODE DELTA,
	job_unit_price decimal(38,20) NOT NULL ENCODE LZO,
	job_total_price decimal(38,20) NOT NULL ENCODE LZO,
	job_line_amount decimal(38,20) NOT NULL ENCODE LZO,
	job_line_discount_amount decimal(38,20) NOT NULL ENCODE LZO,
	job_line_discount decimal(38,20) NOT NULL ENCODE LZO,
	job_unit_price_lcy decimal(38,20) NOT NULL ENCODE LZO,
	job_total_price_lcy decimal(38,20) NOT NULL ENCODE LZO,
	job_line_amount_lcy decimal(38,20) NOT NULL ENCODE LZO,
	job_line_disc_amount_lcy decimal(38,20) NOT NULL ENCODE LZO,
	job_currency_factor decimal(38,20) NOT NULL ENCODE LZO,
	job_currency_code VARCHAR(40) NOT NULL ENCODE LZO,
	job_planning_line_no INTEGER NOT NULL ENCODE DELTA,
	job_remaining_qty decimal(38,20) NOT NULL ENCODE LZO,
	job_remaining_qty_base decimal(38,20) NOT NULL ENCODE LZO,
	deferral_code VARCHAR(20) NOT NULL ENCODE LZO,
	returns_deferral_start_date timestamp NOT NULL ENCODE LZO,
	prod_order_no VARCHAR(40) NOT NULL ENCODE LZO,
	variant_code VARCHAR(20) NOT NULL ENCODE LZO,
	bin_code VARCHAR(40) NOT NULL ENCODE LZO,
	qty_per_unit_of_measure decimal(38,20) NOT NULL ENCODE LZO,
	unit_of_measure_code VARCHAR(20) NOT NULL ENCODE LZO,
	quantity_base decimal(38,20) NOT NULL ENCODE LZO,
	outstanding_qty_base decimal(38,20) NOT NULL ENCODE LZO,
	qty_to_invoice_base decimal(38,20) NOT NULL ENCODE LZO,
	qty_to_receive_base decimal(38,20) NOT NULL ENCODE LZO,
	qty_rcd_not_invoiced_base decimal(38,20) NOT NULL ENCODE LZO,
	qty_received_base decimal(38,20) NOT NULL ENCODE LZO,
	qty_invoiced_base decimal(38,20) NOT NULL ENCODE LZO,
	fa_posting_date timestamp NOT NULL ENCODE LZO,
	fa_posting_type INTEGER NOT NULL ENCODE DELTA,
	depreciation_book_code VARCHAR(20) NOT NULL ENCODE LZO,
	salvage_value decimal(38,20) NOT NULL ENCODE LZO,
	depr_until_fa_posting_date SMALLINT NOT NULL ENCODE DELTA,
	depr_acquisition_cost SMALLINT NOT NULL ENCODE DELTA,
	maintenance_code VARCHAR(20) NOT NULL ENCODE LZO,
	insurance_no VARCHAR(40) NOT NULL ENCODE LZO,
	budgeted_fa_no VARCHAR(40) NOT NULL ENCODE LZO,
	duplicate_in_depreciation_book VARCHAR(20) NOT NULL ENCODE LZO,
	use_duplication_list SMALLINT NOT NULL ENCODE DELTA,
	responsibility_center VARCHAR(20) NOT NULL ENCODE LZO,
	cross_reference_no VARCHAR(40) NOT NULL ENCODE LZO,
	unit_of_measure_cross_ref VARCHAR(20) NOT NULL ENCODE LZO,
	cross_reference_type INTEGER NOT NULL ENCODE DELTA,
	cross_reference_type_no VARCHAR(60) NOT NULL ENCODE LZO,
	item_category_code VARCHAR(40) NOT NULL ENCODE LZO,
	nonstock SMALLINT NOT NULL ENCODE DELTA,
	purchasing_code VARCHAR(20) NOT NULL ENCODE LZO,
	product_group_code VARCHAR(40) NOT NULL ENCODE LZO,
	special_order SMALLINT NOT NULL ENCODE DELTA,
	special_order_sales_no VARCHAR(40) NOT NULL ENCODE LZO,
	special_order_sales_line_no INTEGER NOT NULL ENCODE DELTA,
	completely_received SMALLINT NOT NULL ENCODE DELTA,
	requested_receipt_date timestamp NOT NULL ENCODE LZO,
	promised_receipt_date timestamp NOT NULL ENCODE LZO,
	lead_time_calculation varchar(32) NOT NULL ENCODE LZO,
	inbound_whse_handling_time varchar(32) NOT NULL ENCODE LZO,
	planned_receipt_date timestamp NOT NULL ENCODE LZO,
	order_date timestamp NOT NULL ENCODE LZO,
	allow_item_charge_assignment SMALLINT NOT NULL ENCODE DELTA,
	return_qty_to_ship decimal(38,20) NOT NULL ENCODE LZO,
	return_qty_to_ship_base decimal(38,20) NOT NULL ENCODE LZO,
	return_qty_shipped_not_invd decimal(38,20) NOT NULL ENCODE LZO,
	ret_qty_shpd_not_invd_base decimal(38,20) NOT NULL ENCODE LZO,
	return_shpd_not_invd decimal(38,20) NOT NULL ENCODE LZO,
	return_shpd_not_invd_lcy decimal(38,20) NOT NULL ENCODE LZO,
	return_qty_shipped decimal(38,20) NOT NULL ENCODE LZO,
	return_qty_shipped_base decimal(38,20) NOT NULL ENCODE LZO,
	return_shipment_no VARCHAR(40) NOT NULL ENCODE LZO,
	return_shipment_line_no INTEGER NOT NULL ENCODE DELTA,
	return_reason_code VARCHAR(20) NOT NULL ENCODE LZO,
	foc SMALLINT NOT NULL ENCODE DELTA,
	amount_inc_tax_lcy decimal(38,20) NOT NULL ENCODE LZO,
	ret_doc_no VARCHAR(40) NOT NULL ENCODE LZO,
	ret_doc_line_no INTEGER NOT NULL ENCODE DELTA,
	contract_no VARCHAR(40) NOT NULL ENCODE LZO,
	margin decimal(38,20) NOT NULL ENCODE LZO,
	add_margin decimal(38,20) NOT NULL ENCODE LZO,
	add_foc_quantity decimal(38,20) NOT NULL ENCODE LZO,
	purchase_cost decimal(38,20) NOT NULL ENCODE LZO,
	tester SMALLINT NOT NULL ENCODE DELTA,
	ean_code VARCHAR(60) NOT NULL ENCODE LZO,
	narration VARCHAR(500) NOT NULL ENCODE LZO,
	inventory_type INTEGER NOT NULL ENCODE DELTA,
	item_category_3 VARCHAR(40) NOT NULL ENCODE LZO,
	item_category_4 VARCHAR(40) NOT NULL ENCODE LZO,
	brand VARCHAR(40) NOT NULL ENCODE LZO,
	original_purchase_cost decimal(38,20) NOT NULL ENCODE LZO,
	cost_updated_by VARCHAR(100) NOT NULL ENCODE LZO,
	focpo SMALLINT NOT NULL ENCODE DELTA,
	system_calculated_foc SMALLINT NOT NULL ENCODE DELTA,
	routing_no VARCHAR(40) NOT NULL ENCODE LZO,
	operation_no VARCHAR(20) NOT NULL ENCODE LZO,
	work_center_no VARCHAR(40) NOT NULL ENCODE LZO,
	finished SMALLINT NOT NULL ENCODE DELTA,
	prod_order_line_no INTEGER NOT NULL ENCODE DELTA,
	overhead_rate decimal(38,20) NOT NULL ENCODE LZO,
	mps_order SMALLINT NOT NULL ENCODE DELTA,
	planning_flexibility INTEGER NOT NULL ENCODE DELTA,
	safety_lead_time varchar(32) NOT NULL ENCODE LZO,
	routing_reference_no INTEGER NOT NULL ENCODE DELTA
);


INSERT INTO NAV.purchase_line 
SELECT ts, document_type, document_no, line_no, buy_from_vendor_no, type, no, location_code, posting_group, expected_receipt_date, description, description_2, unit_of_measure, quantity, outstanding_quantity, qty_to_invoice, qty_to_receive, direct_unit_cost, unit_cost_lcy, vat, line_discount, line_discount_amount, amount, amount_including_vat, unit_price_lcy, allow_invoice_disc, gross_weight, net_weight, units_per_parcel, unit_volume, appl_to_item_entry, shortcut_dimension_1_code, shortcut_dimension_2_code, job_no, indirect_cost, recalculate_invoice_disc, outstanding_amount, qty_rcd_not_invoiced, amt_rcd_not_invoiced, quantity_received, quantity_invoiced, receipt_no, receipt_line_no, profit, pay_to_vendor_no, inv_discount_amount, vendor_item_no, sales_order_no, sales_order_line_no, drop_shipment, gen_bus_posting_group, gen_prod_posting_group, vat_calculation_type, transaction_type, transport_method, attached_to_line_no, entry_point, area, transaction_specification, tax_area_code, tax_liable, tax_group_code, use_tax, vat_bus_posting_group, vat_prod_posting_group, currency_code, outstanding_amount_lcy, amt_rcd_not_invoiced_lcy, blanket_order_no, blanket_order_line_no, vat_base_amount, unit_cost, system_created_entry, line_amount, vat_difference, inv_disc_amount_to_invoice, vat_identifier, ic_partner_ref_type, ic_partner_reference, prepayment, prepmt_line_amount, prepmt_amt_inv, prepmt_amt_incl_vat, prepayment_amount, prepmt_vat_base_amt, prepayment_vat, prepmt_vat_calc_type, prepayment_vat_identifier, prepayment_tax_area_code, prepayment_tax_liable, prepayment_tax_group_code, prepmt_amt_to_deduct, prepmt_amt_deducted, prepayment_line, prepmt_amount_inv_incl_vat, prepmt_amount_inv_lcy, ic_partner_code, prepmt_vat_amount_inv_lcy, prepayment_vat_difference, prepmt_vat_diff_to_deduct, prepmt_vat_diff_deducted, outstanding_amt_ex_vat_lcy, a_rcd_not_inv_ex_vat_lcy, dimension_set_id, job_task_no, job_line_type, job_unit_price, job_total_price, job_line_amount, job_line_discount_amount, job_line_discount, job_unit_price_lcy, job_total_price_lcy, job_line_amount_lcy, job_line_disc_amount_lcy, job_currency_factor, job_currency_code, job_planning_line_no, job_remaining_qty, job_remaining_qty_base, deferral_code, returns_deferral_start_date, prod_order_no, variant_code, bin_code, qty_per_unit_of_measure, unit_of_measure_code, quantity_base, outstanding_qty_base, qty_to_invoice_base, qty_to_receive_base, qty_rcd_not_invoiced_base, qty_received_base, qty_invoiced_base, fa_posting_date, fa_posting_type, depreciation_book_code, salvage_value, depr_until_fa_posting_date, depr_acquisition_cost, maintenance_code, insurance_no, budgeted_fa_no, duplicate_in_depreciation_book, use_duplication_list, responsibility_center, cross_reference_no, unit_of_measure_cross_ref, cross_reference_type, cross_reference_type_no, item_category_code, nonstock, purchasing_code, product_group_code, special_order, special_order_sales_no, special_order_sales_line_no, completely_received, requested_receipt_date, promised_receipt_date, lead_time_calculation, inbound_whse_handling_time, planned_receipt_date, order_date, allow_item_charge_assignment, return_qty_to_ship, return_qty_to_ship_base, return_qty_shipped_not_invd, ret_qty_shpd_not_invd_base, return_shpd_not_invd, return_shpd_not_invd_lcy, return_qty_shipped, return_qty_shipped_base, return_shipment_no, return_shipment_line_no, return_reason_code, foc, amount_inc_tax_lcy, ret_doc_no, ret_doc_line_no, contract_no, margin, add_margin, add_foc_quantity, purchase_cost, tester, ean_code, narration, inventory_type, item_category_3, item_category_4, brand, original_purchase_cost, cost_updated_by, focpo, system_calculated_foc, routing_no, operation_no, work_center_no, finished, prod_order_line_no, overhead_rate, mps_order, planning_flexibility, safety_lead_time, routing_reference_no
FROM tmp_purchase_line;
COMMIT;